#pragma checksum "TestFiles\IntegrationTests\CSharp9LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "7ca74a2405915ed4e7f6acc1aaf066581ca1762f1e2772eb0d7f8e4d0c325868"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharp9LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"7ca74a2405915ed4e7f6acc1aaf066581ca1762f1e2772eb0d7f8e4d0c325868", @"/TestFiles/IntegrationTests/CSharp9LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharp9LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line (3,3)-(7,1) "TestFiles\IntegrationTests\CSharp9LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    var useArgumentException = true;
    System.Exception value = useArgumentException ? new System.ArgumentException() : new System.InvalidOperationException();
    _ = value.Message;

#line default
#line hidden
#nullable disable

        }
    }
}
#pragma warning restore 1591
