
// This file is automatically generated when you do `Build.ps1 prepare`, but it must be stored in  source control.

import jetbrains.buildServer.configs.kotlin.v2019_2.*
import jetbrains.buildServer.configs.kotlin.v2019_2.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2019_2.triggers.*

version = "2019.2"

project {

buildType(DebugBuild)
buildType(ReleaseBuild)
buildType(PublicBuild)

   buildType(Deploy)
}

   object DebugBuild : BuildType({
    name = "Build [Debug]"

    artifactRules = "+:artifacts/publish/**/*=>artifacts/publish"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            scriptMode = file {
                path = "Build.ps1"
            }
            noProfile = false
            param("jetbrains_powershell_scriptArguments", "test --configuration Debug --buildNumber %build.number%")
        }
    }

    requirements {
        equals("env.BuildAgentType", "caravela02")
    }



    triggers {

        vcs {
            watchChangesInDependencies = true
            branchFilter = "+:<default>"
        }        

    }

  dependencies {

        snapshot(AbsoluteId("Metalama_PostSharpBackstageSettings_DebugBuild")) {
                     onDependencyFailure = FailureAction.FAIL_TO_START
                }


    }
  })

   object ReleaseBuild : BuildType({
    name = "Build [Release]"

    artifactRules = "+:artifacts/publish/**/*=>artifacts/publish"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            scriptMode = file {
                path = "Build.ps1"
            }
            noProfile = false
            param("jetbrains_powershell_scriptArguments", "test --configuration Release --buildNumber %build.number%")
        }
    }

    requirements {
        equals("env.BuildAgentType", "caravela02")
    }



  dependencies {

        snapshot(AbsoluteId("Metalama_PostSharpBackstageSettings_ReleaseBuild")) {
                     onDependencyFailure = FailureAction.FAIL_TO_START
                }


    }
  })

   object PublicBuild : BuildType({
    name = "Build [Public]"

    artifactRules = "+:artifacts/publish/**/*=>artifacts/publish"

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            scriptMode = file {
                path = "Build.ps1"
            }
            noProfile = false
            param("jetbrains_powershell_scriptArguments", "test --configuration Public --buildNumber %build.number%")
        }
    }

    requirements {
        equals("env.BuildAgentType", "caravela02")
    }



  dependencies {

        snapshot(AbsoluteId("Metalama_PostSharpBackstageSettings_PublicBuild")) {
                     onDependencyFailure = FailureAction.FAIL_TO_START
                }


    }
  })

// Publish the release build to public feeds
object Deploy : BuildType({
    name = "Deploy [Public]"
    type = Type.DEPLOYMENT

    vcs {
        root(DslContext.settingsRoot)
    }

    steps {
        powerShell {
            scriptMode = file {
                path = "Build.ps1"
            }
            noProfile = false
            param("jetbrains_powershell_scriptArguments", "publish --configuration Public")
        }
    }
    
    dependencies {
        dependency(PublicBuild) {
            snapshot {
            }

            artifacts {
                cleanDestination = true
                artifactRules = "+:artifacts/publish/**/*=>artifacts/publish"
            }
        }
    }
    
    requirements {
        equals("env.BuildAgentType", "caravela02")
    }
})


