' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

' Baselined for the port, we should revisit these, see: https://github.com/dotnet/roslyn/issues/8183.
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.DTEUtils.ApplyListViewThemeStyles(System.IntPtr)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.DTEUtils.ApplyTreeViewThemeStyles(System.IntPtr)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.Common.Utils.FocusFirstOrLastTabItem(System.IntPtr,System.Boolean)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndoing(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndone(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DesignerToolbarPanel.WndProc(System.Windows.Forms.Message@)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.DesignerTypeDiscoveryService.GetProjectOutputs(System.IServiceProvider,Microsoft.VisualStudio.Shell.Interop.IVsHierarchy)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.DesignerFramework.GenericComponentSerializationStore.SerializedObjectData.SerializeObject(System.Object)~System.Byte[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyApplication.MyApplicationProperties.FilesToCheckOut(System.Boolean)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPageVBWinForms.GetFormEntryPoints(System.Boolean)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.EnsureNotConflictingSettings(System.Object,System.Windows.Forms.DataGridViewCellCancelEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.RemoveItems(System.Int32[],System.Int32[])~System.Int32[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.CompilePropPage2.UpdatePropertiesFromCurrentState")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.DelayPostingMessage(System.Object)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.GetCurrentImportsList(VSLangProj.Imports)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.GetReferencedNamespaceList~System.Collections.Generic.IList{System.String}")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.ImportList_ItemCheck(System.Object,System.Windows.Forms.ItemCheckEventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshImportListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshReferenceListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.PostRefreshServiceReferenceListMessage")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.ReferencePropPage.SetReferenceListColumnWidths(System.Windows.Forms.Control@,System.Windows.Forms.ListView@,System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.UserPropertyDescriptor.#ctor(System.String,System.Type)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.Category.#ctor(System.String,System.String,Microsoft.VisualStudio.Editors.ResourceEditor.Category.Display,System.ComponentModel.Design.MenuCommand,System.EventHandler,Microsoft.VisualStudio.Editors.ResourceEditor.ResourceTypeEditor[])")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.AddOrUpdateResourcesFromFiles(System.String[],System.Boolean,System.Boolean,System.Boolean,System.Boolean)~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.GetSelectedResources~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.HandleViewHelperCommandExec(System.Guid,System.UInt32,System.Boolean@)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.PropertyGridUnselectAll")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceEditorView.PropertyGridUpdate")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.BeginLabelEdit(Microsoft.VisualStudio.Editors.ResourceEditor.Resource)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.ClearColumnSortImage(System.Int32)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceListView.SetColumnSortImage(System.Int32,System.Boolean)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceStringTable.GetSelectedResources~Microsoft.VisualStudio.Editors.ResourceEditor.Resource[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance.DesignTimeSettingInstanceCustomPropertyDescriptorBase.#ctor(Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.DesignTimeSettingInstance.GetEvents~System.ComponentModel.EventDescriptorCollection")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGeneratorBase.AddMyModule(System.CodeDom.CodeCompileUnit,System.String,System.String)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsDesigner.TypeEditorHostControl.DropDownControl(System.Windows.Forms.Control)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsGlobalObjects.SettingsFileGlobalObject.BuildType~System.Type")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.SettingsGlobalObjects.SettingsFileGlobalObject.CreateInstance~System.Object")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0003:Do not directly await a Task", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.XmlIntellisense.XmlIntellisenseSchemas.CompileCallBack(Microsoft.VisualStudio.Editors.XmlIntellisense.XmlIntellisenseSchemasData)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.DesignerFramework.GenericComponentSerializationStore.Errors")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPage.ControlData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.ApplicationPropPageVBBase.ApplicationTypeInfo.References")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.ResourceEditor.ResourceSerializationService.ResourceSerializationStore.Errors")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0009:Override Object.Equals(object) when implementing IEquatable<T> ", Justification:="<Pending>", Scope:="type", Target:="~T:Microsoft.VisualStudio.Editors.PropertyPages.ImportIdentity")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.Runtime.Hosting.StrongNameHelpers.StrongNameFreeBuffer(System.IntPtr)")>
