' Licensed to the .NET Foundation under one or more agreements.
' The .NET Foundation licenses this file to you under the MIT license.
' See the LICENSE file in the project root for more information.

Option Strict Off

Imports System

Module Module1

    Sub Main()
        Dim BoFalse As Boolean
        Dim BoTrue As Boolean
        Dim SB As SByte
        Dim By As Byte
        Dim Sh As Short
        Dim US As UShort
        Dim [In] As Integer
        Dim UI As UInteger
        Dim Lo As Long
        Dim UL As ULong
        Dim De As Decimal
        Dim Si As Single
        Dim [Do] As Double
        Dim St As String
        Dim Ob As Object
        Dim Tc As System.TypeCode
        Dim Da As Date
        Dim Ch As Char
        Dim ChArray() As Char

        BoFalse = False
        BoTrue = True
        SB = -1
        Sh = -3
        [In] = -5
        Lo = -7
        De = -9D
        Si = 10
        [Do] = -11
        St = "12"
        Ob = "-13"
        Da = #8:30:00 AM#
        Ch = "c"c
        Tc = TypeCode.Double
        ChArray = "14"
        By = 22
        US = 24
        UI = 26
        UL = 28

        Dim result As Object

        result = Da + BoFalse
        result = Da + BoTrue
        result = Da + SB
        result = Da + By
        result = Da + Sh
        result = Da + US
        result = Da + [In]
        result = Da + UI
        result = Da + Lo
        result = Da + UL
        result = Da + De
        result = Da + Si
        result = Da + [Do]
        result = Da + Tc
        result = Da + Ch
        result = Ch + BoFalse
        result = Ch + BoTrue
        result = Ch + SB
        result = Ch + By
        result = Ch + Sh
        result = Ch + US
        result = Ch + [In]
        result = Ch + UI
        result = Ch + Lo
        result = Ch + UL
        result = Ch + De
        result = Ch + Si
        result = Ch + [Do]
        result = Ch + Tc
        result = Ch + Da
        result = BoFalse + Da
        result = BoFalse + Ch
        result = BoTrue + Da
        result = BoTrue + Ch
        result = SB + Da
        result = SB + Ch
        result = By + Da
        result = By + Ch
        result = Sh + Da
        result = Sh + Ch
        result = US + Da
        result = US + Ch
        result = [In] + Da
        result = [In] + Ch
        result = UI + Da
        result = UI + Ch
        result = Lo + Da
        result = Lo + Ch
        result = UL + Da
        result = UL + Ch
        result = De + Da
        result = De + Ch
        result = Si + Da
        result = Si + Ch
        result = [Do] + Da
        result = [Do] + Ch
        result = Tc + Da
        result = Tc + Ch
        result = Da - BoFalse
        result = Da - BoTrue
        result = Da - SB
        result = Da - By
        result = Da - Sh
        result = Da - US
        result = Da - [In]
        result = Da - UI
        result = Da - Lo
        result = Da - UL
        result = Da - De
        result = Da - Si
        result = Da - [Do]
        result = Da - St
        result = Da - Ob
        result = Da - Tc
        result = Da - Ch
        result = Da - ChArray
        result = Ch - BoFalse
        result = Ch - BoTrue
        result = Ch - SB
        result = Ch - By
        result = Ch - Sh
        result = Ch - US
        result = Ch - [In]
        result = Ch - UI
        result = Ch - Lo
        result = Ch - UL
        result = Ch - De
        result = Ch - Si
        result = Ch - [Do]
        result = Ch - St
        result = Ch - Ob
        result = Ch - Tc
        result = Ch - Da
        result = Ch - Ch
        result = Ch - ChArray
        result = ChArray - Ch
        result = BoFalse - Da
        result = BoFalse - Ch
        result = BoTrue - Da
        result = BoTrue - Ch
        result = SB - Da
        result = SB - Ch
        result = By - Da
        result = By - Ch
        result = Sh - Da
        result = Sh - Ch
        result = US - Da
        result = US - Ch
        result = [In] - Da
        result = [In] - Ch
        result = UI - Da
        result = UI - Ch
        result = Lo - Da
        result = Lo - Ch
        result = UL - Da
        result = UL - Ch
        result = De - Da
        result = De - Ch
        result = Si - Da
        result = Si - Ch
        result = [Do] - Da
        result = [Do] - Ch
        result = St - Da
        result = St - Ch
        result = Ob - Da
        result = Ob - Ch
        result = Tc - Da
        result = Tc - Ch
        result = Da * BoFalse
        result = Da * BoTrue
        result = Da * SB
        result = Da * By
        result = Da * Sh
        result = Da * US
        result = Da * [In]
        result = Da * UI
        result = Da * Lo
        result = Da * UL
        result = Da * De
        result = Da * Si
        result = Da * [Do]
        result = Da * St
        result = Da * Ob
        result = Da * Tc
        result = Da * Da
        result = Da * Ch
        result = Da * ChArray
        result = Ch * BoFalse
        result = Ch * BoTrue
        result = Ch * SB
        result = Ch * By
        result = Ch * Sh
        result = Ch * US
        result = Ch * [In]
        result = Ch * UI
        result = Ch * Lo
        result = Ch * UL
        result = Ch * De
        result = Ch * Si
        result = Ch * [Do]
        result = Ch * St
        result = Ch * Ob
        result = Ch * Tc
        result = Ch * Da
        result = Ch * Ch
        result = Ch * ChArray
        result = ChArray * Da
        result = ChArray * Ch
        result = BoFalse * Da
        result = BoFalse * Ch
        result = BoTrue * Da
        result = BoTrue * Ch
        result = SB * Da
        result = SB * Ch
        result = By * Da
        result = By * Ch
        result = Sh * Da
        result = Sh * Ch
        result = US * Da
        result = US * Ch
        result = [In] * Da
        result = [In] * Ch
        result = UI * Da
        result = UI * Ch
        result = Lo * Da
        result = Lo * Ch
        result = UL * Da
        result = UL * Ch
        result = De * Da
        result = De * Ch
        result = Si * Da
        result = Si * Ch
        result = [Do] * Da
        result = [Do] * Ch
        result = St * Da
        result = St * Ch
        result = Ob * Da
        result = Ob * Ch
        result = Tc * Da
        result = Tc * Ch
        result = Da / BoFalse
        result = Da / BoTrue
        result = Da / SB
        result = Da / By
        result = Da / Sh
        result = Da / US
        result = Da / [In]
        result = Da / UI
        result = Da / Lo
        result = Da / UL
        result = Da / De
        result = Da / Si
        result = Da / [Do]
        result = Da / St
        result = Da / Ob
        result = Da / Tc
        result = Da / Da
        result = Da / Ch
        result = Da / ChArray
        result = Ch / BoFalse
        result = Ch / BoTrue
        result = Ch / SB
        result = Ch / By
        result = Ch / Sh
        result = Ch / US
        result = Ch / [In]
        result = Ch / UI
        result = Ch / Lo
        result = Ch / UL
        result = Ch / De
        result = Ch / Si
        result = Ch / [Do]
        result = Ch / St
        result = Ch / Ob
        result = Ch / Tc
        result = Ch / Da
        result = Ch / Ch
        result = Ch / ChArray
        result = ChArray / Da
        result = ChArray / Ch
        result = BoFalse / Da
        result = BoFalse / Ch
        result = BoTrue / Da
        result = BoTrue / Ch
        result = SB / Da
        result = SB / Ch
        result = By / Da
        result = By / Ch
        result = Sh / Da
        result = Sh / Ch
        result = US / Da
        result = US / Ch
        result = [In] / Da
        result = [In] / Ch
        result = UI / Da
        result = UI / Ch
        result = Lo / Da
        result = Lo / Ch
        result = UL / Da
        result = UL / Ch
        result = De / Da
        result = De / Ch
        result = Si / Da
        result = Si / Ch
        result = [Do] / Da
        result = [Do] / Ch
        result = St / Da
        result = St / Ch
        result = Ob / Da
        result = Ob / Ch
        result = Tc / Da
        result = Tc / Ch
        result = Da \ BoTrue
        result = Da \ SB
        result = Da \ By
        result = Da \ Sh
        result = Da \ US
        result = Da \ [In]
        result = Da \ UI
        result = Da \ Lo
        result = Da \ UL
        result = Da \ De
        result = Da \ Si
        result = Da \ [Do]
        result = Da \ St
        result = Da \ Ob
        result = Da \ Tc
        result = Da \ Da
        result = Da \ Ch
        result = Da \ ChArray
        result = Ch \ BoTrue
        result = Ch \ SB
        result = Ch \ By
        result = Ch \ Sh
        result = Ch \ US
        result = Ch \ [In]
        result = Ch \ UI
        result = Ch \ Lo
        result = Ch \ UL
        result = Ch \ De
        result = Ch \ Si
        result = Ch \ [Do]
        result = Ch \ St
        result = Ch \ Ob
        result = Ch \ Tc
        result = Ch \ Da
        result = Ch \ Ch
        result = Ch \ ChArray
        result = ChArray \ Da
        result = ChArray \ Ch
        result = BoFalse \ Da
        result = BoFalse \ Ch
        result = BoTrue \ Da
        result = BoTrue \ Ch
        result = SB \ Da
        result = SB \ Ch
        result = By \ Da
        result = By \ Ch
        result = Sh \ Da
        result = Sh \ Ch
        result = US \ Da
        result = US \ Ch
        result = [In] \ Da
        result = [In] \ Ch
        result = UI \ Da
        result = UI \ Ch
        result = Lo \ Da
        result = Lo \ Ch
        result = UL \ Da
        result = UL \ Ch
        result = De \ Da
        result = De \ Ch
        result = Si \ Da
        result = Si \ Ch
        result = [Do] \ Da
        result = [Do] \ Ch
        result = St \ Da
        result = St \ Ch
        result = Ob \ Da
        result = Ob \ Ch
        result = Tc \ Da
        result = Tc \ Ch
        result = Da Mod BoTrue
        result = Da Mod SB
        result = Da Mod By
        result = Da Mod Sh
        result = Da Mod US
        result = Da Mod [In]
        result = Da Mod UI
        result = Da Mod Lo
        result = Da Mod UL
        result = Da Mod De
        result = Da Mod Si
        result = Da Mod [Do]
        result = Da Mod St
        result = Da Mod Ob
        result = Da Mod Tc
        result = Da Mod Da
        result = Da Mod Ch
        result = Da Mod ChArray
        result = Ch Mod BoTrue
        result = Ch Mod SB
        result = Ch Mod By
        result = Ch Mod Sh
        result = Ch Mod US
        result = Ch Mod [In]
        result = Ch Mod UI
        result = Ch Mod Lo
        result = Ch Mod UL
        result = Ch Mod De
        result = Ch Mod Si
        result = Ch Mod [Do]
        result = Ch Mod St
        result = Ch Mod Ob
        result = Ch Mod Tc
        result = Ch Mod Da
        result = Ch Mod Ch
        result = Ch Mod ChArray
        result = ChArray Mod Da
        result = ChArray Mod Ch
        result = BoFalse Mod Da
        result = BoFalse Mod Ch
        result = BoTrue Mod Da
        result = BoTrue Mod Ch
        result = SB Mod Da
        result = SB Mod Ch
        result = By Mod Da
        result = By Mod Ch
        result = Sh Mod Da
        result = Sh Mod Ch
        result = US Mod Da
        result = US Mod Ch
        result = [In] Mod Da
        result = [In] Mod Ch
        result = UI Mod Da
        result = UI Mod Ch
        result = Lo Mod Da
        result = Lo Mod Ch
        result = UL Mod Da
        result = UL Mod Ch
        result = De Mod Da
        result = De Mod Ch
        result = Si Mod Da
        result = Si Mod Ch
        result = [Do] Mod Da
        result = [Do] Mod Ch
        result = St Mod Da
        result = St Mod Ch
        result = Ob Mod Da
        result = Ob Mod Ch
        result = Tc Mod Da
        result = Tc Mod Ch
        result = Da ^ BoFalse
        result = Da ^ BoTrue
        result = Da ^ SB
        result = Da ^ By
        result = Da ^ Sh
        result = Da ^ US
        result = Da ^ [In]
        result = Da ^ UI
        result = Da ^ Lo
        result = Da ^ UL
        result = Da ^ De
        result = Da ^ Si
        result = Da ^ [Do]
        result = Da ^ St
        result = Da ^ Ob
        result = Da ^ Tc
        result = Da ^ Da
        result = Da ^ Ch
        result = Da ^ ChArray
        result = Ch ^ BoFalse
        result = Ch ^ BoTrue
        result = Ch ^ SB
        result = Ch ^ By
        result = Ch ^ Sh
        result = Ch ^ US
        result = Ch ^ [In]
        result = Ch ^ UI
        result = Ch ^ Lo
        result = Ch ^ UL
        result = Ch ^ De
        result = Ch ^ Si
        result = Ch ^ [Do]
        result = Ch ^ St
        result = Ch ^ Ob
        result = Ch ^ Tc
        result = Ch ^ Da
        result = Ch ^ Ch
        result = Ch ^ ChArray
        result = ChArray ^ Da
        result = ChArray ^ Ch
        result = BoFalse ^ Da
        result = BoFalse ^ Ch
        result = BoTrue ^ Da
        result = BoTrue ^ Ch
        result = SB ^ Da
        result = SB ^ Ch
        result = By ^ Da
        result = By ^ Ch
        result = Sh ^ Da
        result = Sh ^ Ch
        result = US ^ Da
        result = US ^ Ch
        result = [In] ^ Da
        result = [In] ^ Ch
        result = UI ^ Da
        result = UI ^ Ch
        result = Lo ^ Da
        result = Lo ^ Ch
        result = UL ^ Da
        result = UL ^ Ch
        result = De ^ Da
        result = De ^ Ch
        result = Si ^ Da
        result = Si ^ Ch
        result = [Do] ^ Da
        result = [Do] ^ Ch
        result = St ^ Da
        result = St ^ Ch
        result = Ob ^ Da
        result = Ob ^ Ch
        result = Tc ^ Da
        result = Tc ^ Ch
        result = Da << BoFalse
        result = Da << BoTrue
        result = Da << SB
        result = Da << By
        result = Da << Sh
        result = Da << US
        result = Da << [In]
        result = Da << UI
        result = Da << Lo
        result = Da << UL
        result = Da << De
        result = Da << Si
        result = Da << [Do]
        result = Da << St
        result = Da << Ob
        result = Da << Tc
        result = Da << Da
        result = Da << Ch
        result = Da << ChArray
        result = Ch << BoFalse
        result = Ch << BoTrue
        result = Ch << SB
        result = Ch << By
        result = Ch << Sh
        result = Ch << US
        result = Ch << [In]
        result = Ch << UI
        result = Ch << Lo
        result = Ch << UL
        result = Ch << De
        result = Ch << Si
        result = Ch << [Do]
        result = Ch << St
        result = Ch << Ob
        result = Ch << Tc
        result = Ch << Da
        result = Ch << Ch
        result = Ch << ChArray
        result = Da >> BoFalse
        result = Da >> BoTrue
        result = Da >> SB
        result = Da >> By
        result = Da >> Sh
        result = Da >> US
        result = Da >> [In]
        result = Da >> UI
        result = Da >> Lo
        result = Da >> UL
        result = Da >> De
        result = Da >> Si
        result = Da >> [Do]
        result = Da >> St
        result = Da >> Ob
        result = Da >> Tc
        result = Da >> Da
        result = Da >> Ch
        result = Da >> ChArray
        result = Ch >> BoFalse
        result = Ch >> BoTrue
        result = Ch >> SB
        result = Ch >> By
        result = Ch >> Sh
        result = Ch >> US
        result = Ch >> [In]
        result = Ch >> UI
        result = Ch >> Lo
        result = Ch >> UL
        result = Ch >> De
        result = Ch >> Si
        result = Ch >> [Do]
        result = Ch >> St
        result = Ch >> Ob
        result = Ch >> Tc
        result = Ch >> Da
        result = Ch >> Ch
        result = Ch >> ChArray
        result = Da OrElse BoFalse
        result = Da OrElse BoTrue
        result = Da OrElse SB
        result = Da OrElse By
        result = Da OrElse Sh
        result = Da OrElse US
        result = Da OrElse [In]
        result = Da OrElse UI
        result = Da OrElse Lo
        result = Da OrElse UL
        result = Da OrElse De
        result = Da OrElse Si
        result = Da OrElse [Do]
        result = Da OrElse St
        result = Da OrElse Ob
        result = Da OrElse Tc
        result = Da OrElse Da
        result = Da OrElse Ch
        result = Da OrElse ChArray
        result = Ch OrElse BoFalse
        result = Ch OrElse BoTrue
        result = Ch OrElse SB
        result = Ch OrElse By
        result = Ch OrElse Sh
        result = Ch OrElse US
        result = Ch OrElse [In]
        result = Ch OrElse UI
        result = Ch OrElse Lo
        result = Ch OrElse UL
        result = Ch OrElse De
        result = Ch OrElse Si
        result = Ch OrElse [Do]
        result = Ch OrElse St
        result = Ch OrElse Ob
        result = Ch OrElse Tc
        result = Ch OrElse Da
        result = Ch OrElse Ch
        result = Ch OrElse ChArray
        result = ChArray OrElse Da
        result = ChArray OrElse Ch
        result = BoFalse OrElse Da
        result = BoFalse OrElse Ch
        result = BoTrue OrElse Da
        result = BoTrue OrElse Ch
        result = SB OrElse Da
        result = SB OrElse Ch
        result = By OrElse Da
        result = By OrElse Ch
        result = Sh OrElse Da
        result = Sh OrElse Ch
        result = US OrElse Da
        result = US OrElse Ch
        result = [In] OrElse Da
        result = [In] OrElse Ch
        result = UI OrElse Da
        result = UI OrElse Ch
        result = Lo OrElse Da
        result = Lo OrElse Ch
        result = UL OrElse Da
        result = UL OrElse Ch
        result = De OrElse Da
        result = De OrElse Ch
        result = Si OrElse Da
        result = Si OrElse Ch
        result = [Do] OrElse Da
        result = [Do] OrElse Ch
        result = St OrElse Da
        result = St OrElse Ch
        result = Ob OrElse Da
        result = Ob OrElse Ch
        result = Tc OrElse Da
        result = Tc OrElse Ch
        result = Da AndAlso BoFalse
        result = Da AndAlso BoTrue
        result = Da AndAlso SB
        result = Da AndAlso By
        result = Da AndAlso Sh
        result = Da AndAlso US
        result = Da AndAlso [In]
        result = Da AndAlso UI
        result = Da AndAlso Lo
        result = Da AndAlso UL
        result = Da AndAlso De
        result = Da AndAlso Si
        result = Da AndAlso [Do]
        result = Da AndAlso St
        result = Da AndAlso Ob
        result = Da AndAlso Tc
        result = Da AndAlso Da
        result = Da AndAlso Ch
        result = Da AndAlso ChArray
        result = Ch AndAlso BoFalse
        result = Ch AndAlso BoTrue
        result = Ch AndAlso SB
        result = Ch AndAlso By
        result = Ch AndAlso Sh
        result = Ch AndAlso US
        result = Ch AndAlso [In]
        result = Ch AndAlso UI
        result = Ch AndAlso Lo
        result = Ch AndAlso UL
        result = Ch AndAlso De
        result = Ch AndAlso Si
        result = Ch AndAlso [Do]
        result = Ch AndAlso St
        result = Ch AndAlso Ob
        result = Ch AndAlso Tc
        result = Ch AndAlso Da
        result = Ch AndAlso Ch
        result = Ch AndAlso ChArray
        result = ChArray AndAlso Da
        result = ChArray AndAlso Ch
        result = BoFalse AndAlso Da
        result = BoFalse AndAlso Ch
        result = BoTrue AndAlso Da
        result = BoTrue AndAlso Ch
        result = SB AndAlso Da
        result = SB AndAlso Ch
        result = By AndAlso Da
        result = By AndAlso Ch
        result = Sh AndAlso Da
        result = Sh AndAlso Ch
        result = US AndAlso Da
        result = US AndAlso Ch
        result = [In] AndAlso Da
        result = [In] AndAlso Ch
        result = UI AndAlso Da
        result = UI AndAlso Ch
        result = Lo AndAlso Da
        result = Lo AndAlso Ch
        result = UL AndAlso Da
        result = UL AndAlso Ch
        result = De AndAlso Da
        result = De AndAlso Ch
        result = Si AndAlso Da
        result = Si AndAlso Ch
        result = [Do] AndAlso Da
        result = [Do] AndAlso Ch
        result = St AndAlso Da
        result = St AndAlso Ch
        result = Ob AndAlso Da
        result = Ob AndAlso Ch
        result = Tc AndAlso Da
        result = Tc AndAlso Ch
        result = Da = BoFalse
        result = Da = BoTrue
        result = Da = SB
        result = Da = By
        result = Da = Sh
        result = Da = US
        result = Da = [In]
        result = Da = UI
        result = Da = Lo
        result = Da = UL
        result = Da = De
        result = Da = Si
        result = Da = [Do]
        result = Da = Tc
        result = Da = Ch
        result = Ch = BoFalse
        result = Ch = BoTrue
        result = Ch = SB
        result = Ch = By
        result = Ch = Sh
        result = Ch = US
        result = Ch = [In]
        result = Ch = UI
        result = Ch = Lo
        result = Ch = UL
        result = Ch = De
        result = Ch = Si
        result = Ch = [Do]
        result = Ch = Tc
        result = Ch = Da
        result = BoFalse = Da
        result = BoFalse = Ch
        result = BoTrue = Da
        result = BoTrue = Ch
        result = SB = Da
        result = SB = Ch
        result = By = Da
        result = By = Ch
        result = Sh = Da
        result = Sh = Ch
        result = US = Da
        result = US = Ch
        result = [In] = Da
        result = [In] = Ch
        result = UI = Da
        result = UI = Ch
        result = Lo = Da
        result = Lo = Ch
        result = UL = Da
        result = UL = Ch
        result = De = Da
        result = De = Ch
        result = Si = Da
        result = Si = Ch
        result = [Do] = Da
        result = [Do] = Ch
        result = Tc = Da
        result = Tc = Ch
        result = Da <> BoFalse
        result = Da <> BoTrue
        result = Da <> SB
        result = Da <> By
        result = Da <> Sh
        result = Da <> US
        result = Da <> [In]
        result = Da <> UI
        result = Da <> Lo
        result = Da <> UL
        result = Da <> De
        result = Da <> Si
        result = Da <> [Do]
        result = Da <> Tc
        result = Da <> Ch
        result = Ch <> BoFalse
        result = Ch <> BoTrue
        result = Ch <> SB
        result = Ch <> By
        result = Ch <> Sh
        result = Ch <> US
        result = Ch <> [In]
        result = Ch <> UI
        result = Ch <> Lo
        result = Ch <> UL
        result = Ch <> De
        result = Ch <> Si
        result = Ch <> [Do]
        result = Ch <> Tc
        result = Ch <> Da
        result = BoFalse <> Da
        result = BoFalse <> Ch
        result = BoTrue <> Da
        result = BoTrue <> Ch
        result = SB <> Da
        result = SB <> Ch
        result = By <> Da
        result = By <> Ch
        result = Sh <> Da
        result = Sh <> Ch
        result = US <> Da
        result = US <> Ch
        result = [In] <> Da
        result = [In] <> Ch
        result = UI <> Da
        result = UI <> Ch
        result = Lo <> Da
        result = Lo <> Ch
        result = UL <> Da
        result = UL <> Ch
        result = De <> Da
        result = De <> Ch
        result = Si <> Da
        result = Si <> Ch
        result = [Do] <> Da
        result = [Do] <> Ch
        result = Tc <> Da
        result = Tc <> Ch
        result = Da <= BoFalse
        result = Da <= BoTrue
        result = Da <= SB
        result = Da <= By
        result = Da <= Sh
        result = Da <= US
        result = Da <= [In]
        result = Da <= UI
        result = Da <= Lo
        result = Da <= UL
        result = Da <= De
        result = Da <= Si
        result = Da <= [Do]
        result = Da <= Tc
        result = Da <= Ch
        result = Ch <= BoFalse
        result = Ch <= BoTrue
        result = Ch <= SB
        result = Ch <= By
        result = Ch <= Sh
        result = Ch <= US
        result = Ch <= [In]
        result = Ch <= UI
        result = Ch <= Lo
        result = Ch <= UL
        result = Ch <= De
        result = Ch <= Si
        result = Ch <= [Do]
        result = Ch <= Tc
        result = Ch <= Da
        result = BoFalse <= Da
        result = BoFalse <= Ch
        result = BoTrue <= Da
        result = BoTrue <= Ch
        result = SB <= Da
        result = SB <= Ch
        result = By <= Da
        result = By <= Ch
        result = Sh <= Da
        result = Sh <= Ch
        result = US <= Da
        result = US <= Ch
        result = [In] <= Da
        result = [In] <= Ch
        result = UI <= Da
        result = UI <= Ch
        result = Lo <= Da
        result = Lo <= Ch
        result = UL <= Da
        result = UL <= Ch
        result = De <= Da
        result = De <= Ch
        result = Si <= Da
        result = Si <= Ch
        result = [Do] <= Da
        result = [Do] <= Ch
        result = Tc <= Da
        result = Tc <= Ch
        result = Da >= BoFalse
        result = Da >= BoTrue
        result = Da >= SB
        result = Da >= By
        result = Da >= Sh
        result = Da >= US
        result = Da >= [In]
        result = Da >= UI
        result = Da >= Lo
        result = Da >= UL
        result = Da >= De
        result = Da >= Si
        result = Da >= [Do]
        result = Da >= Tc
        result = Da >= Ch
        result = Ch >= BoFalse
        result = Ch >= BoTrue
        result = Ch >= SB
        result = Ch >= By
        result = Ch >= Sh
        result = Ch >= US
        result = Ch >= [In]
        result = Ch >= UI
        result = Ch >= Lo
        result = Ch >= UL
        result = Ch >= De
        result = Ch >= Si
        result = Ch >= [Do]
        result = Ch >= Tc
        result = Ch >= Da
        result = BoFalse >= Da
        result = BoFalse >= Ch
        result = BoTrue >= Da
        result = BoTrue >= Ch
        result = SB >= Da
        result = SB >= Ch
        result = By >= Da
        result = By >= Ch
        result = Sh >= Da
        result = Sh >= Ch
        result = US >= Da
        result = US >= Ch
        result = [In] >= Da
        result = [In] >= Ch
        result = UI >= Da
        result = UI >= Ch
        result = Lo >= Da
        result = Lo >= Ch
        result = UL >= Da
        result = UL >= Ch
        result = De >= Da
        result = De >= Ch
        result = Si >= Da
        result = Si >= Ch
        result = [Do] >= Da
        result = [Do] >= Ch
        result = Tc >= Da
        result = Tc >= Ch
        result = Da < BoFalse
        result = Da < BoTrue
        result = Da < SB
        result = Da < By
        result = Da < Sh
        result = Da < US
        result = Da < [In]
        result = Da < UI
        result = Da < Lo
        result = Da < UL
        result = Da < De
        result = Da < Si
        result = Da < [Do]
        result = Da < Tc
        result = Da < Ch
        result = Ch < BoFalse
        result = Ch < BoTrue
        result = Ch < SB
        result = Ch < By
        result = Ch < Sh
        result = Ch < US
        result = Ch < [In]
        result = Ch < UI
        result = Ch < Lo
        result = Ch < UL
        result = Ch < De
        result = Ch < Si
        result = Ch < [Do]
        result = Ch < Tc
        result = Ch < Da
        result = BoFalse < Da
        result = BoFalse < Ch
        result = BoTrue < Da
        result = BoTrue < Ch
        result = SB < Da
        result = SB < Ch
        result = By < Da
        result = By < Ch
        result = Sh < Da
        result = Sh < Ch
        result = US < Da
        result = US < Ch
        result = [In] < Da
        result = [In] < Ch
        result = UI < Da
        result = UI < Ch
        result = Lo < Da
        result = Lo < Ch
        result = UL < Da
        result = UL < Ch
        result = De < Da
        result = De < Ch
        result = Si < Da
        result = Si < Ch
        result = [Do] < Da
        result = [Do] < Ch
        result = Tc < Da
        result = Tc < Ch
        result = Da > BoFalse
        result = Da > BoTrue
        result = Da > SB
        result = Da > By
        result = Da > Sh
        result = Da > US
        result = Da > [In]
        result = Da > UI
        result = Da > Lo
        result = Da > UL
        result = Da > De
        result = Da > Si
        result = Da > [Do]
        result = Da > Tc
        result = Da > Ch
        result = Ch > BoFalse
        result = Ch > BoTrue
        result = Ch > SB
        result = Ch > By
        result = Ch > Sh
        result = Ch > US
        result = Ch > [In]
        result = Ch > UI
        result = Ch > Lo
        result = Ch > UL
        result = Ch > De
        result = Ch > Si
        result = Ch > [Do]
        result = Ch > Tc
        result = Ch > Da
        result = BoFalse > Da
        result = BoFalse > Ch
        result = BoTrue > Da
        result = BoTrue > Ch
        result = SB > Da
        result = SB > Ch
        result = By > Da
        result = By > Ch
        result = Sh > Da
        result = Sh > Ch
        result = US > Da
        result = US > Ch
        result = [In] > Da
        result = [In] > Ch
        result = UI > Da
        result = UI > Ch
        result = Lo > Da
        result = Lo > Ch
        result = UL > Da
        result = UL > Ch
        result = De > Da
        result = De > Ch
        result = Si > Da
        result = Si > Ch
        result = [Do] > Da
        result = [Do] > Ch
        result = Tc > Da
        result = Tc > Ch
        result = Da Xor BoFalse
        result = Da Xor BoTrue
        result = Da Xor SB
        result = Da Xor By
        result = Da Xor Sh
        result = Da Xor US
        result = Da Xor [In]
        result = Da Xor UI
        result = Da Xor Lo
        result = Da Xor UL
        result = Da Xor De
        result = Da Xor Si
        result = Da Xor [Do]
        result = Da Xor St
        result = Da Xor Ob
        result = Da Xor Tc
        result = Da Xor Da
        result = Da Xor Ch
        result = Da Xor ChArray
        result = Ch Xor BoFalse
        result = Ch Xor BoTrue
        result = Ch Xor SB
        result = Ch Xor By
        result = Ch Xor Sh
        result = Ch Xor US
        result = Ch Xor [In]
        result = Ch Xor UI
        result = Ch Xor Lo
        result = Ch Xor UL
        result = Ch Xor De
        result = Ch Xor Si
        result = Ch Xor [Do]
        result = Ch Xor St
        result = Ch Xor Ob
        result = Ch Xor Tc
        result = Ch Xor Da
        result = Ch Xor Ch
        result = Ch Xor ChArray
        result = ChArray Xor Da
        result = ChArray Xor Ch
        result = BoFalse Xor Da
        result = BoFalse Xor Ch
        result = BoTrue Xor Da
        result = BoTrue Xor Ch
        result = SB Xor Da
        result = SB Xor Ch
        result = By Xor Da
        result = By Xor Ch
        result = Sh Xor Da
        result = Sh Xor Ch
        result = US Xor Da
        result = US Xor Ch
        result = [In] Xor Da
        result = [In] Xor Ch
        result = UI Xor Da
        result = UI Xor Ch
        result = Lo Xor Da
        result = Lo Xor Ch
        result = UL Xor Da
        result = UL Xor Ch
        result = De Xor Da
        result = De Xor Ch
        result = Si Xor Da
        result = Si Xor Ch
        result = [Do] Xor Da
        result = [Do] Xor Ch
        result = St Xor Da
        result = St Xor Ch
        result = Ob Xor Da
        result = Ob Xor Ch
        result = Tc Xor Da
        result = Tc Xor Ch
        result = Da Or BoFalse
        result = Da Or BoTrue
        result = Da Or SB
        result = Da Or By
        result = Da Or Sh
        result = Da Or US
        result = Da Or [In]
        result = Da Or UI
        result = Da Or Lo
        result = Da Or UL
        result = Da Or De
        result = Da Or Si
        result = Da Or [Do]
        result = Da Or St
        result = Da Or Ob
        result = Da Or Tc
        result = Da Or Da
        result = Da Or Ch
        result = Da Or ChArray
        result = Ch Or BoFalse
        result = Ch Or BoTrue
        result = Ch Or SB
        result = Ch Or By
        result = Ch Or Sh
        result = Ch Or US
        result = Ch Or [In]
        result = Ch Or UI
        result = Ch Or Lo
        result = Ch Or UL
        result = Ch Or De
        result = Ch Or Si
        result = Ch Or [Do]
        result = Ch Or St
        result = Ch Or Ob
        result = Ch Or Tc
        result = Ch Or Da
        result = Ch Or Ch
        result = Ch Or ChArray
        result = ChArray Or Da
        result = ChArray Or Ch
        result = BoFalse Or Da
        result = BoFalse Or Ch
        result = BoTrue Or Da
        result = BoTrue Or Ch
        result = SB Or Da
        result = SB Or Ch
        result = By Or Da
        result = By Or Ch
        result = Sh Or Da
        result = Sh Or Ch
        result = US Or Da
        result = US Or Ch
        result = [In] Or Da
        result = [In] Or Ch
        result = UI Or Da
        result = UI Or Ch
        result = Lo Or Da
        result = Lo Or Ch
        result = UL Or Da
        result = UL Or Ch
        result = De Or Da
        result = De Or Ch
        result = Si Or Da
        result = Si Or Ch
        result = [Do] Or Da
        result = [Do] Or Ch
        result = St Or Da
        result = St Or Ch
        result = Ob Or Da
        result = Ob Or Ch
        result = Tc Or Da
        result = Tc Or Ch
        result = Da And BoFalse
        result = Da And BoTrue
        result = Da And SB
        result = Da And By
        result = Da And Sh
        result = Da And US
        result = Da And [In]
        result = Da And UI
        result = Da And Lo
        result = Da And UL
        result = Da And De
        result = Da And Si
        result = Da And [Do]
        result = Da And St
        result = Da And Ob
        result = Da And Tc
        result = Da And Da
        result = Da And Ch
        result = Da And ChArray
        result = Ch And BoFalse
        result = Ch And BoTrue
        result = Ch And SB
        result = Ch And By
        result = Ch And Sh
        result = Ch And US
        result = Ch And [In]
        result = Ch And UI
        result = Ch And Lo
        result = Ch And UL
        result = Ch And De
        result = Ch And Si
        result = Ch And [Do]
        result = Ch And St
        result = Ch And Ob
        result = Ch And Tc
        result = Ch And Da
        result = Ch And Ch
        result = Ch And ChArray
        result = ChArray And Da
        result = ChArray And Ch
        result = BoFalse And Da
        result = BoFalse And Ch
        result = BoTrue And Da
        result = BoTrue And Ch
        result = SB And Da
        result = SB And Ch
        result = By And Da
        result = By And Ch
        result = Sh And Da
        result = Sh And Ch
        result = US And Da
        result = US And Ch
        result = [In] And Da
        result = [In] And Ch
        result = UI And Da
        result = UI And Ch
        result = Lo And Da
        result = Lo And Ch
        result = UL And Da
        result = UL And Ch
        result = De And Da
        result = De And Ch
        result = Si And Da
        result = Si And Ch
        result = [Do] And Da
        result = [Do] And Ch
        result = St And Da
        result = St And Ch
        result = Ob And Da
        result = Ob And Ch
        result = Tc And Da
        result = Tc And Ch


        result = [In] + DBNull.Value
        result = Nothing + DBNull.Value
        result = DBNull.Value + Nothing
        result = DBNull.Value + DBNull.Value
        result = DBNull.Value + [In]
        result = [In] - DBNull.Value
        result = St - DBNull.Value
        result = Nothing - DBNull.Value
        result = DBNull.Value - Nothing
        result = DBNull.Value - DBNull.Value
        result = DBNull.Value - [In]
        result = DBNull.Value - St
        result = [In] * DBNull.Value
        result = St * DBNull.Value
        result = Nothing * DBNull.Value
        result = DBNull.Value * Nothing
        result = DBNull.Value * DBNull.Value
        result = DBNull.Value * [In]
        result = DBNull.Value * St
        result = [In] / DBNull.Value
        result = St / DBNull.Value
        result = Nothing / DBNull.Value
        result = DBNull.Value / Nothing
        result = DBNull.Value / DBNull.Value
        result = DBNull.Value / [In]
        result = DBNull.Value / St
        result = [In] \ DBNull.Value
        result = St \ DBNull.Value
        result = Nothing \ DBNull.Value
        result = DBNull.Value \ Nothing
        result = DBNull.Value \ DBNull.Value
        result = DBNull.Value \ [In]
        result = DBNull.Value \ St
        result = [In] Mod DBNull.Value
        result = St Mod DBNull.Value
        result = Nothing Mod DBNull.Value
        result = DBNull.Value Mod Nothing
        result = DBNull.Value Mod DBNull.Value
        result = DBNull.Value Mod [In]
        result = DBNull.Value Mod St
        result = [In] ^ DBNull.Value
        result = St ^ DBNull.Value
        result = Nothing ^ DBNull.Value
        result = DBNull.Value ^ Nothing
        result = DBNull.Value ^ DBNull.Value
        result = DBNull.Value ^ [In]
        result = DBNull.Value ^ St
        result = [In] << DBNull.Value
        result = St << DBNull.Value
        result = Nothing << DBNull.Value
        result = DBNull.Value << Nothing
        result = DBNull.Value << DBNull.Value
        result = DBNull.Value << [In]
        result = DBNull.Value << St
        result = [In] >> DBNull.Value
        result = St >> DBNull.Value
        result = Nothing >> DBNull.Value
        result = DBNull.Value >> Nothing
        result = DBNull.Value >> DBNull.Value
        result = DBNull.Value >> [In]
        result = DBNull.Value >> St
        result = [In] OrElse DBNull.Value
        result = St OrElse DBNull.Value
        result = Nothing OrElse DBNull.Value
        result = DBNull.Value OrElse Nothing
        result = DBNull.Value OrElse DBNull.Value
        result = DBNull.Value OrElse [In]
        result = DBNull.Value OrElse St
        result = [In] AndAlso DBNull.Value
        result = St AndAlso DBNull.Value
        result = Nothing AndAlso DBNull.Value
        result = DBNull.Value AndAlso Nothing
        result = DBNull.Value AndAlso DBNull.Value
        result = DBNull.Value AndAlso [In]
        result = DBNull.Value AndAlso St
        result = DBNull.Value & DBNull.Value
        result = [In] Like DBNull.Value
        result = St Like DBNull.Value
        result = Nothing Like DBNull.Value
        result = DBNull.Value Like Nothing
        result = DBNull.Value Like DBNull.Value
        result = DBNull.Value Like [In]
        result = DBNull.Value Like St
        result = [In] = DBNull.Value
        result = Nothing = DBNull.Value
        result = DBNull.Value = Nothing
        result = DBNull.Value = DBNull.Value
        result = DBNull.Value = [In]
        result = [In] <> DBNull.Value
        result = Nothing <> DBNull.Value
        result = DBNull.Value <> Nothing
        result = DBNull.Value <> DBNull.Value
        result = DBNull.Value <> [In]
        result = [In] <= DBNull.Value
        result = St <= DBNull.Value
        result = Nothing <= DBNull.Value
        result = DBNull.Value <= Nothing
        result = DBNull.Value <= DBNull.Value
        result = DBNull.Value <= [In]
        result = DBNull.Value <= St
        result = [In] >= DBNull.Value
        result = St >= DBNull.Value
        result = Nothing >= DBNull.Value
        result = DBNull.Value >= Nothing
        result = DBNull.Value >= DBNull.Value
        result = DBNull.Value >= [In]
        result = DBNull.Value >= St
        result = [In] < DBNull.Value
        result = St < DBNull.Value
        result = Nothing < DBNull.Value
        result = DBNull.Value < Nothing
        result = DBNull.Value < DBNull.Value
        result = DBNull.Value < [In]
        result = DBNull.Value < St
        result = [In] > DBNull.Value
        result = St > DBNull.Value
        result = Nothing > DBNull.Value
        result = DBNull.Value > Nothing
        result = DBNull.Value > DBNull.Value
        result = DBNull.Value > [In]
        result = DBNull.Value > St
        result = [In] Xor DBNull.Value
        result = St Xor DBNull.Value
        result = Nothing Xor DBNull.Value
        result = DBNull.Value Xor Nothing
        result = DBNull.Value Xor DBNull.Value
        result = DBNull.Value Xor [In]
        result = DBNull.Value Xor St
        result = [In] Or DBNull.Value
        result = St Or DBNull.Value
        result = Nothing Or DBNull.Value
        result = DBNull.Value Or Nothing
        result = DBNull.Value Or DBNull.Value
        result = DBNull.Value Or [In]
        result = DBNull.Value Or St
        result = [In] And DBNull.Value
        result = St And DBNull.Value
        result = Nothing And DBNull.Value
        result = DBNull.Value And Nothing
        result = DBNull.Value And DBNull.Value
        result = DBNull.Value And [In]
        result = DBNull.Value And St
        result = ChArray + DBNull.Value
        result = DBNull.Value + ChArray
        result = ChArray - DBNull.Value
        result = DBNull.Value - ChArray
        result = ChArray * DBNull.Value
        result = DBNull.Value * ChArray
        result = ChArray / DBNull.Value
        result = DBNull.Value / ChArray
        result = ChArray \ DBNull.Value
        result = DBNull.Value \ ChArray
        result = ChArray Mod DBNull.Value
        result = DBNull.Value Mod ChArray
        result = ChArray ^ DBNull.Value
        result = DBNull.Value ^ ChArray
        result = ChArray << DBNull.Value
        result = DBNull.Value << ChArray
        result = ChArray >> DBNull.Value
        result = DBNull.Value >> ChArray
        result = ChArray OrElse DBNull.Value
        result = DBNull.Value OrElse ChArray
        result = ChArray AndAlso DBNull.Value
        result = DBNull.Value AndAlso ChArray
        result = ChArray Like DBNull.Value
        result = DBNull.Value Like ChArray
        result = ChArray = DBNull.Value
        result = DBNull.Value = ChArray
        result = ChArray <> DBNull.Value
        result = DBNull.Value <> ChArray
        result = ChArray <= DBNull.Value
        result = DBNull.Value <= ChArray
        result = ChArray >= DBNull.Value
        result = DBNull.Value >= ChArray
        result = ChArray < DBNull.Value
        result = DBNull.Value < ChArray
        result = ChArray > DBNull.Value
        result = DBNull.Value > ChArray
        result = ChArray Xor DBNull.Value
        result = DBNull.Value Xor ChArray
        result = ChArray Or DBNull.Value
        result = DBNull.Value Or ChArray
        result = ChArray And DBNull.Value
        result = DBNull.Value And ChArray

        ' Conversion errors as opposed to unsupported operator error

        'result = ChArray + BoFalse
        'result = ChArray + BoTrue
        'result = ChArray + SB
        'result = ChArray + By
        'result = ChArray + Sh
        'result = ChArray + US
        'result = ChArray + [In]
        'result = ChArray + UI
        'result = ChArray + Lo
        'result = ChArray + UL
        'result = ChArray + De
        'result = ChArray + Si
        'result = ChArray + [Do]
        'result = ChArray + Tc
        'result = BoFalse + ChArray
        'result = BoTrue + ChArray
        'result = SB + ChArray
        'result = By + ChArray
        'result = Sh + ChArray
        'result = US + ChArray
        'result = [In] + ChArray
        'result = UI + ChArray
        'result = Lo + ChArray
        'result = UL + ChArray
        'result = De + ChArray
        'result = Si + ChArray
        'result = [Do] + ChArray
        'result = Tc + ChArray
        'result = ChArray - BoFalse
        'result = ChArray - BoTrue
        'result = ChArray - SB
        'result = ChArray - By
        'result = ChArray - Sh
        'result = ChArray - US
        'result = ChArray - [In]
        'result = ChArray - UI
        'result = ChArray - Lo
        'result = ChArray - UL
        'result = ChArray - De
        'result = ChArray - Si
        'result = ChArray - [Do]
        'result = ChArray - St
        'result = ChArray - Tc
        'result = ChArray - ChArray
        'result = BoFalse - ChArray
        'result = BoTrue - ChArray
        'result = SB - ChArray
        'result = By - ChArray
        'result = Sh - ChArray
        'result = US - ChArray
        'result = [In] - ChArray
        'result = UI - ChArray
        'result = Lo - ChArray
        'result = UL - ChArray
        'result = De - ChArray
        'result = Si - ChArray
        'result = [Do] - ChArray
        'result = St - ChArray
        'result = Tc - ChArray
        'result = ChArray * BoFalse
        'result = ChArray * BoTrue
        'result = ChArray * SB
        'result = ChArray * By
        'result = ChArray * Sh
        'result = ChArray * US
        'result = ChArray * [In]
        'result = ChArray * UI
        'result = ChArray * Lo
        'result = ChArray * UL
        'result = ChArray * De
        'result = ChArray * Si
        'result = ChArray * [Do]
        'result = ChArray * St
        'result = ChArray * Tc
        'result = ChArray * ChArray
        'result = BoFalse * ChArray
        'result = BoTrue * ChArray
        'result = SB * ChArray
        'result = By * ChArray
        'result = Sh * ChArray
        'result = US * ChArray
        'result = [In] * ChArray
        'result = UI * ChArray
        'result = Lo * ChArray
        'result = UL * ChArray
        'result = De * ChArray
        'result = Si * ChArray
        'result = [Do] * ChArray
        'result = St * ChArray
        'result = Tc * ChArray
        'result = ChArray / BoFalse
        'result = ChArray / BoTrue
        'result = ChArray / SB
        'result = ChArray / By
        'result = ChArray / Sh
        'result = ChArray / US
        'result = ChArray / [In]
        'result = ChArray / UI
        'result = ChArray / Lo
        'result = ChArray / UL
        'result = ChArray / De
        'result = ChArray / Si
        'result = ChArray / [Do]
        'result = ChArray / St
        'result = ChArray / Tc
        'result = ChArray / ChArray
        'result = BoFalse / ChArray
        'result = BoTrue / ChArray
        'result = SB / ChArray
        'result = By / ChArray
        'result = Sh / ChArray
        'result = US / ChArray
        'result = [In] / ChArray
        'result = UI / ChArray
        'result = Lo / ChArray
        'result = UL / ChArray
        'result = De / ChArray
        'result = Si / ChArray
        'result = [Do] / ChArray
        'result = St / ChArray
        'result = Tc / ChArray
        'result = ChArray \ BoTrue
        'result = ChArray \ SB
        'result = ChArray \ By
        'result = ChArray \ Sh
        'result = ChArray \ US
        'result = ChArray \ [In]
        'result = ChArray \ UI
        'result = ChArray \ Lo
        'result = ChArray \ UL
        'result = ChArray \ De
        'result = ChArray \ Si
        'result = ChArray \ [Do]
        'result = ChArray \ St
        'result = ChArray \ Tc
        'result = ChArray \ ChArray
        'result = BoFalse \ ChArray
        'result = BoTrue \ ChArray
        'result = SB \ ChArray
        'result = By \ ChArray
        'result = Sh \ ChArray
        'result = US \ ChArray
        'result = [In] \ ChArray
        'result = UI \ ChArray
        'result = Lo \ ChArray
        'result = UL \ ChArray
        'result = De \ ChArray
        'result = Si \ ChArray
        'result = [Do] \ ChArray
        'result = St \ ChArray
        'result = Tc \ ChArray
        'result = ChArray Mod BoTrue
        'result = ChArray Mod SB
        'result = ChArray Mod By
        'result = ChArray Mod Sh
        'result = ChArray Mod US
        'result = ChArray Mod [In]
        'result = ChArray Mod UI
        'result = ChArray Mod Lo
        'result = ChArray Mod UL
        'result = ChArray Mod De
        'result = ChArray Mod Si
        'result = ChArray Mod [Do]
        'result = ChArray Mod St
        'result = ChArray Mod Tc
        'result = ChArray Mod ChArray
        'result = BoFalse Mod ChArray
        'result = BoTrue Mod ChArray
        'result = SB Mod ChArray
        'result = By Mod ChArray
        'result = Sh Mod ChArray
        'result = US Mod ChArray
        'result = [In] Mod ChArray
        'result = UI Mod ChArray
        'result = Lo Mod ChArray
        'result = UL Mod ChArray
        'result = De Mod ChArray
        'result = Si Mod ChArray
        'result = [Do] Mod ChArray
        'result = St Mod ChArray
        'result = Tc Mod ChArray
        'result = ChArray ^ BoFalse
        'result = ChArray ^ BoTrue
        'result = ChArray ^ SB
        'result = ChArray ^ By
        'result = ChArray ^ Sh
        'result = ChArray ^ US
        'result = ChArray ^ [In]
        'result = ChArray ^ UI
        'result = ChArray ^ Lo
        'result = ChArray ^ UL
        'result = ChArray ^ De
        'result = ChArray ^ Si
        'result = ChArray ^ [Do]
        'result = ChArray ^ St
        'result = ChArray ^ Tc
        'result = ChArray ^ ChArray
        'result = BoFalse ^ ChArray
        'result = BoTrue ^ ChArray
        'result = SB ^ ChArray
        'result = By ^ ChArray
        'result = Sh ^ ChArray
        'result = US ^ ChArray
        'result = [In] ^ ChArray
        'result = UI ^ ChArray
        'result = Lo ^ ChArray
        'result = UL ^ ChArray
        'result = De ^ ChArray
        'result = Si ^ ChArray
        'result = [Do] ^ ChArray
        'result = St ^ ChArray
        'result = Tc ^ ChArray
        'result = ChArray << BoFalse
        'result = ChArray << BoTrue
        'result = ChArray << SB
        'result = ChArray << By
        'result = ChArray << Sh
        'result = ChArray << US
        'result = ChArray << [In]
        'result = ChArray << UI
        'result = ChArray << Lo
        'result = ChArray << UL
        'result = ChArray << De
        'result = ChArray << Si
        'result = ChArray << [Do]
        'result = ChArray << St
        'result = ChArray << Tc
        'result = ChArray << Da
        'result = ChArray << Ch
        'result = ChArray << ChArray
        'result = BoFalse << Da
        'result = BoFalse << Ch
        'result = BoFalse << ChArray
        'result = BoTrue << Da
        'result = BoTrue << Ch
        'result = BoTrue << ChArray
        'result = SB << Da
        'result = SB << Ch
        'result = SB << ChArray
        'result = By << Da
        'result = By << Ch
        'result = By << ChArray
        'result = Sh << Da
        'result = Sh << Ch
        'result = Sh << ChArray
        'result = US << Da
        'result = US << Ch
        'result = US << ChArray
        'result = [In] << Da
        'result = [In] << Ch
        'result = [In] << ChArray
        'result = UI << Da
        'result = UI << Ch
        'result = UI << ChArray
        'result = Lo << Da
        'result = Lo << Ch
        'result = Lo << ChArray
        'result = UL << Da
        'result = UL << Ch
        'result = UL << ChArray
        'result = De << Da
        'result = De << Ch
        'result = De << ChArray
        'result = Si << Da
        'result = Si << Ch
        'result = Si << ChArray
        'result = [Do] << Da
        'result = [Do] << Ch
        'result = [Do] << ChArray
        'result = St << Da
        'result = St << Ch
        'result = St << ChArray
        'result = Tc << Da
        'result = Tc << Ch
        'result = Tc << ChArray
        'result = ChArray >> BoFalse
        'result = ChArray >> BoTrue
        'result = ChArray >> SB
        'result = ChArray >> By
        'result = ChArray >> Sh
        'result = ChArray >> US
        'result = ChArray >> [In]
        'result = ChArray >> UI
        'result = ChArray >> Lo
        'result = ChArray >> UL
        'result = ChArray >> De
        'result = ChArray >> Si
        'result = ChArray >> [Do]
        'result = ChArray >> St
        'result = ChArray >> Tc
        'result = ChArray >> Da
        'result = ChArray >> Ch
        'result = ChArray >> ChArray
        'result = BoFalse >> Da
        'result = BoFalse >> Ch
        'result = BoFalse >> ChArray
        'result = BoTrue >> Da
        'result = BoTrue >> Ch
        'result = BoTrue >> ChArray
        'result = SB >> Da
        'result = SB >> Ch
        'result = SB >> ChArray
        'result = By >> Da
        'result = By >> Ch
        'result = By >> ChArray
        'result = Sh >> Da
        'result = Sh >> Ch
        'result = Sh >> ChArray
        'result = US >> Da
        'result = US >> Ch
        'result = US >> ChArray
        'result = [In] >> Da
        'result = [In] >> Ch
        'result = [In] >> ChArray
        'result = UI >> Da
        'result = UI >> Ch
        'result = UI >> ChArray
        'result = Lo >> Da
        'result = Lo >> Ch
        'result = Lo >> ChArray
        'result = UL >> Da
        'result = UL >> Ch
        'result = UL >> ChArray
        'result = De >> Da
        'result = De >> Ch
        'result = De >> ChArray
        'result = Si >> Da
        'result = Si >> Ch
        'result = Si >> ChArray
        'result = [Do] >> Da
        'result = [Do] >> Ch
        'result = [Do] >> ChArray
        'result = St >> Da
        'result = St >> Ch
        'result = St >> ChArray
        'result = Tc >> Da
        'result = Tc >> Ch
        'result = Tc >> ChArray
        'result = ChArray OrElse BoFalse
        'result = ChArray OrElse BoTrue
        'result = ChArray OrElse SB
        'result = ChArray OrElse By
        'result = ChArray OrElse Sh
        'result = ChArray OrElse US
        'result = ChArray OrElse [In]
        'result = ChArray OrElse UI
        'result = ChArray OrElse Lo
        'result = ChArray OrElse UL
        'result = ChArray OrElse De
        'result = ChArray OrElse Si
        'result = ChArray OrElse [Do]
        'result = ChArray OrElse St
        'result = ChArray OrElse Tc
        'result = ChArray OrElse ChArray
        'result = BoFalse OrElse ChArray
        'result = BoTrue OrElse ChArray
        'result = SB OrElse ChArray
        'result = By OrElse ChArray
        'result = Sh OrElse ChArray
        'result = US OrElse ChArray
        'result = [In] OrElse ChArray
        'result = UI OrElse ChArray
        'result = Lo OrElse ChArray
        'result = UL OrElse ChArray
        'result = De OrElse ChArray
        'result = Si OrElse ChArray
        'result = [Do] OrElse ChArray
        'result = St OrElse ChArray
        'result = Tc OrElse ChArray
        'result = ChArray AndAlso BoFalse
        'result = ChArray AndAlso BoTrue
        'result = ChArray AndAlso SB
        'result = ChArray AndAlso By
        'result = ChArray AndAlso Sh
        'result = ChArray AndAlso US
        'result = ChArray AndAlso [In]
        'result = ChArray AndAlso UI
        'result = ChArray AndAlso Lo
        'result = ChArray AndAlso UL
        'result = ChArray AndAlso De
        'result = ChArray AndAlso Si
        'result = ChArray AndAlso [Do]
        'result = ChArray AndAlso St
        'result = ChArray AndAlso Tc
        'result = ChArray AndAlso ChArray
        'result = BoFalse AndAlso ChArray
        'result = BoTrue AndAlso ChArray
        'result = SB AndAlso ChArray
        'result = By AndAlso ChArray
        'result = Sh AndAlso ChArray
        'result = US AndAlso ChArray
        'result = [In] AndAlso ChArray
        'result = UI AndAlso ChArray
        'result = Lo AndAlso ChArray
        'result = UL AndAlso ChArray
        'result = De AndAlso ChArray
        'result = Si AndAlso ChArray
        'result = [Do] AndAlso ChArray
        'result = St AndAlso ChArray
        'result = Tc AndAlso ChArray
        'result = Da = ChArray
        'result = ChArray = BoFalse
        'result = ChArray = BoTrue
        'result = ChArray = SB
        'result = ChArray = By
        'result = ChArray = Sh
        'result = ChArray = US
        'result = ChArray = [In]
        'result = ChArray = UI
        'result = ChArray = Lo
        'result = ChArray = UL
        'result = ChArray = De
        'result = ChArray = Si
        'result = ChArray = [Do]
        'result = ChArray = Tc
        'result = ChArray = Da
        'result = BoFalse = ChArray
        'result = BoTrue = ChArray
        'result = SB = ChArray
        'result = By = ChArray
        'result = Sh = ChArray
        'result = US = ChArray
        'result = [In] = ChArray
        'result = UI = ChArray
        'result = Lo = ChArray
        'result = UL = ChArray
        'result = De = ChArray
        'result = Si = ChArray
        'result = [Do] = ChArray
        'result = Tc = ChArray
        'result = Da <> ChArray
        'result = ChArray <> BoFalse
        'result = ChArray <> BoTrue
        'result = ChArray <> SB
        'result = ChArray <> By
        'result = ChArray <> Sh
        'result = ChArray <> US
        'result = ChArray <> [In]
        'result = ChArray <> UI
        'result = ChArray <> Lo
        'result = ChArray <> UL
        'result = ChArray <> De
        'result = ChArray <> Si
        'result = ChArray <> [Do]
        'result = ChArray <> Tc
        'result = ChArray <> Da
        'result = BoFalse <> ChArray
        'result = BoTrue <> ChArray
        'result = SB <> ChArray
        'result = By <> ChArray
        'result = Sh <> ChArray
        'result = US <> ChArray
        'result = [In] <> ChArray
        'result = UI <> ChArray
        'result = Lo <> ChArray
        'result = UL <> ChArray
        'result = De <> ChArray
        'result = Si <> ChArray
        'result = [Do] <> ChArray
        'result = Tc <> ChArray
        'result = Da <= ChArray
        'result = ChArray <= BoFalse
        'result = ChArray <= BoTrue
        'result = ChArray <= SB
        'result = ChArray <= By
        'result = ChArray <= Sh
        'result = ChArray <= US
        'result = ChArray <= [In]
        'result = ChArray <= UI
        'result = ChArray <= Lo
        'result = ChArray <= UL
        'result = ChArray <= De
        'result = ChArray <= Si
        'result = ChArray <= [Do]
        'result = ChArray <= Tc
        'result = ChArray <= Da
        'result = BoFalse <= ChArray
        'result = BoTrue <= ChArray
        'result = SB <= ChArray
        'result = By <= ChArray
        'result = Sh <= ChArray
        'result = US <= ChArray
        'result = [In] <= ChArray
        'result = UI <= ChArray
        'result = Lo <= ChArray
        'result = UL <= ChArray
        'result = De <= ChArray
        'result = Si <= ChArray
        'result = [Do] <= ChArray
        'result = Tc <= ChArray
        'result = Da >= ChArray
        'result = ChArray >= BoFalse
        'result = ChArray >= BoTrue
        'result = ChArray >= SB
        'result = ChArray >= By
        'result = ChArray >= Sh
        'result = ChArray >= US
        'result = ChArray >= [In]
        'result = ChArray >= UI
        'result = ChArray >= Lo
        'result = ChArray >= UL
        'result = ChArray >= De
        'result = ChArray >= Si
        'result = ChArray >= [Do]
        'result = ChArray >= Tc
        'result = ChArray >= Da
        'result = BoFalse >= ChArray
        'result = BoTrue >= ChArray
        'result = SB >= ChArray
        'result = By >= ChArray
        'result = Sh >= ChArray
        'result = US >= ChArray
        'result = [In] >= ChArray
        'result = UI >= ChArray
        'result = Lo >= ChArray
        'result = UL >= ChArray
        'result = De >= ChArray
        'result = Si >= ChArray
        'result = [Do] >= ChArray
        'result = Tc >= ChArray
        'result = Da < ChArray
        'result = ChArray < BoFalse
        'result = ChArray < BoTrue
        'result = ChArray < SB
        'result = ChArray < By
        'result = ChArray < Sh
        'result = ChArray < US
        'result = ChArray < [In]
        'result = ChArray < UI
        'result = ChArray < Lo
        'result = ChArray < UL
        'result = ChArray < De
        'result = ChArray < Si
        'result = ChArray < [Do]
        'result = ChArray < Tc
        'result = ChArray < Da
        'result = BoFalse < ChArray
        'result = BoTrue < ChArray
        'result = SB < ChArray
        'result = By < ChArray
        'result = Sh < ChArray
        'result = US < ChArray
        'result = [In] < ChArray
        'result = UI < ChArray
        'result = Lo < ChArray
        'result = UL < ChArray
        'result = De < ChArray
        'result = Si < ChArray
        'result = [Do] < ChArray
        'result = Tc < ChArray
        'result = Da > ChArray
        'result = ChArray > BoFalse
        'result = ChArray > BoTrue
        'result = ChArray > SB
        'result = ChArray > By
        'result = ChArray > Sh
        'result = ChArray > US
        'result = ChArray > [In]
        'result = ChArray > UI
        'result = ChArray > Lo
        'result = ChArray > UL
        'result = ChArray > De
        'result = ChArray > Si
        'result = ChArray > [Do]
        'result = ChArray > Tc
        'result = ChArray > Da
        'result = BoFalse > ChArray
        'result = BoTrue > ChArray
        'result = SB > ChArray
        'result = By > ChArray
        'result = Sh > ChArray
        'result = US > ChArray
        'result = [In] > ChArray
        'result = UI > ChArray
        'result = Lo > ChArray
        'result = UL > ChArray
        'result = De > ChArray
        'result = Si > ChArray
        'result = [Do] > ChArray
        'result = Tc > ChArray
        'result = ChArray Xor BoFalse
        'result = ChArray Xor BoTrue
        'result = ChArray Xor SB
        'result = ChArray Xor By
        'result = ChArray Xor Sh
        'result = ChArray Xor US
        'result = ChArray Xor [In]
        'result = ChArray Xor UI
        'result = ChArray Xor Lo
        'result = ChArray Xor UL
        'result = ChArray Xor De
        'result = ChArray Xor Si
        'result = ChArray Xor [Do]
        'result = ChArray Xor St
        'result = ChArray Xor Tc
        'result = ChArray Xor ChArray
        'result = BoFalse Xor ChArray
        'result = BoTrue Xor ChArray
        'result = SB Xor ChArray
        'result = By Xor ChArray
        'result = Sh Xor ChArray
        'result = US Xor ChArray
        'result = [In] Xor ChArray
        'result = UI Xor ChArray
        'result = Lo Xor ChArray
        'result = UL Xor ChArray
        'result = De Xor ChArray
        'result = Si Xor ChArray
        'result = [Do] Xor ChArray
        'result = St Xor ChArray
        'result = Tc Xor ChArray
        'result = ChArray Or BoFalse
        'result = ChArray Or BoTrue
        'result = ChArray Or SB
        'result = ChArray Or By
        'result = ChArray Or Sh
        'result = ChArray Or US
        'result = ChArray Or [In]
        'result = ChArray Or UI
        'result = ChArray Or Lo
        'result = ChArray Or UL
        'result = ChArray Or De
        'result = ChArray Or Si
        'result = ChArray Or [Do]
        'result = ChArray Or St
        'result = ChArray Or Tc
        'result = ChArray Or ChArray
        'result = BoFalse Or ChArray
        'result = BoTrue Or ChArray
        'result = SB Or ChArray
        'result = By Or ChArray
        'result = Sh Or ChArray
        'result = US Or ChArray
        'result = [In] Or ChArray
        'result = UI Or ChArray
        'result = Lo Or ChArray
        'result = UL Or ChArray
        'result = De Or ChArray
        'result = Si Or ChArray
        'result = [Do] Or ChArray
        'result = St Or ChArray
        'result = Tc Or ChArray
        'result = ChArray And BoFalse
        'result = ChArray And BoTrue
        'result = ChArray And SB
        'result = ChArray And By
        'result = ChArray And Sh
        'result = ChArray And US
        'result = ChArray And [In]
        'result = ChArray And UI
        'result = ChArray And Lo
        'result = ChArray And UL
        'result = ChArray And De
        'result = ChArray And Si
        'result = ChArray And [Do]
        'result = ChArray And St
        'result = ChArray And Ob
        'result = ChArray And Tc
        'result = ChArray And ChArray
        'result = BoFalse And ChArray
        'result = BoTrue And ChArray
        'result = SB And ChArray
        'result = By And ChArray
        'result = Sh And ChArray
        'result = US And ChArray
        'result = [In] And ChArray
        'result = UI And ChArray
        'result = Lo And ChArray
        'result = UL And ChArray
        'result = De And ChArray
        'result = Si And ChArray
        'result = [Do] And ChArray
        'result = St And ChArray
        'result = Tc And ChArray

        'result = ChArray - Nothing
        'result = Nothing - ChArray
        'result = ChArray * Nothing
        'result = Nothing * ChArray
        'result = ChArray / Nothing
        'result = Nothing / ChArray
        'result = ChArray \ Nothing
        'result = Nothing \ ChArray
        'result = ChArray Mod Nothing
        'result = Nothing Mod ChArray
        'result = ChArray ^ Nothing
        'result = Nothing ^ ChArray
        'result = ChArray << Nothing
        'result = Nothing << ChArray
        'result = ChArray >> Nothing
        'result = Nothing >> ChArray
        'result = ChArray OrElse Nothing
        'result = Nothing OrElse ChArray
        'result = ChArray AndAlso Nothing
        'result = Nothing AndAlso ChArray
        'result = ChArray Xor Nothing
        'result = Nothing Xor ChArray
        'result = ChArray Or Nothing
        'result = Nothing Or ChArray
        'result = ChArray And Nothing
        'result = Nothing And ChArray



        ' overload resolution errors

        'result = St = DBNull.Value
        'result = DBNull.Value = St
        'result = St <> DBNull.Value
        'result = DBNull.Value <> St


        ' No errors at compile time, but an error at runtime.
        PrintResult("ChArray - Ob", ChArray - Ob)
        PrintResult("Ob - ChArray", Ob - ChArray)
        PrintResult("ChArray * Ob", ChArray * Ob)
        PrintResult("Ob * ChArray", Ob * ChArray)
        PrintResult("ChArray / Ob", ChArray / Ob)
        PrintResult("Ob / ChArray", Ob / ChArray)
        PrintResult("ChArray \ Ob", ChArray \ Ob)
        PrintResult("Ob \ ChArray", Ob \ ChArray)
        PrintResult("ChArray Mod Ob", ChArray Mod Ob)
        PrintResult("Ob Mod ChArray", Ob Mod ChArray)
        PrintResult("ChArray ^ Ob", ChArray ^ Ob)
        PrintResult("Ob ^ ChArray", Ob ^ ChArray)
        PrintResult("ChArray << Ob", ChArray << Ob)
        PrintResult("Ob << ChArray", Ob << ChArray)
        PrintResult("ChArray >> Ob", ChArray >> Ob)
        PrintResult("Ob >> ChArray", Ob >> ChArray)
        PrintResult("ChArray AndAlso Ob", ChArray AndAlso Ob)
        PrintResult("Ob AndAlso ChArray", Ob AndAlso ChArray)
        PrintResult("ChArray Xor Ob", ChArray Xor Ob)
        PrintResult("Ob Xor ChArray", Ob Xor ChArray)
        PrintResult("ChArray Or Ob", ChArray Or Ob)
        PrintResult("Ob Or ChArray", Ob Or ChArray)
        PrintResult("Ob And ChArray", Ob And ChArray)
        PrintResult("ChArray OrElse Ob", ChArray OrElse Ob)
        PrintResult("Ob >> Da", Ob >> Da)
        PrintResult("Ob >> Ch", Ob >> Ch)
        PrintResult("Ob << Da", Ob << Da)
        PrintResult("Ob << Ch", Ob << Ch)

        PrintResult("Nothing OrElse St", Nothing OrElse St)
        PrintResult("Nothing AndAlso St", Nothing AndAlso St)

    End Sub


    Sub PrintResult(expr As String, val As Boolean)
        System.Console.WriteLine("[{1}] Boolean: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As SByte)
        System.Console.WriteLine("[{1}] SByte: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Byte)
        System.Console.WriteLine("[{1}] Byte: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Short)
        System.Console.WriteLine("[{1}] Short: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As UShort)
        System.Console.WriteLine("[{1}] UShort: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Integer)
        System.Console.WriteLine("[{1}] Integer: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As UInteger)
        System.Console.WriteLine("[{1}] UInteger: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Long)
        System.Console.WriteLine("[{1}] Long: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As ULong)
        System.Console.WriteLine("[{1}] ULong: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Decimal)
        System.Console.WriteLine("[{1}] Decimal: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Single)
        System.Console.WriteLine("[{1}] Single: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Double)
        System.Console.WriteLine("[{1}] Double: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Date)
        System.Console.WriteLine("[{1}] Date: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As Char)
        System.Console.WriteLine("[{1}] Char: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As String)
        System.Console.WriteLine("[{0}] String: {1}", expr, val)
    End Sub
    Sub PrintResult(expr As String, val As Object)
        System.Console.WriteLine("[{1}] Object: {0}", val, expr)
    End Sub
    Sub PrintResult(expr As String, val As System.TypeCode)
        System.Console.WriteLine("[{1}] TypeCode: {0}", val, expr)
    End Sub



End Module


