phases:
- phase: Windows_Unit_Tests
  queue:
    parallel: 2
    matrix:
      debug:
        configuration: debug
      release: 
        configuration: release
  steps:
    - script: build/scripts/cibuild.cmd -$(configuration) -testDesktop -test32
           
