trigger:
  branches:
    include:
      - main
      - main-vs-deps
      - release/dev15.9.x
      - release/dev16.*-vs-deps
      - release/dev17.*
    exclude:
      - release/dev17.0
pr: none

resources:
  repositories:
  - repository: MicroBuildTemplate
    type: git
    name: 1ESPipelineTemplates/MicroBuildTemplate
    ref: refs/tags/release

parameters:
  - name: IbcDrop
    type: string
    default: default

  - name: SignType
    default: real
    type: string
    values:
      - real
      - test

  - name: SkipApplyOptimizationData
    type: boolean
    default: false

  - name: SkipTests
    type: boolean
    default: true

  - name: PMEOverride
    type: boolean
    default: false

schedules:
  - cron: "0 8 22-28 * 0"
    displayName: "Monthly smoke test"
    branches:
      include:
        - main
        - release/*
      exclude:
        - ""
    always: true # Run even if there have been no source code changes since the last successful scheduled run
    batch: false # Do not run the pipeline if the previously scheduled run is in-progress

variables:
  - group: DotNet-Roslyn-SDLValidation-Params
  - name: Codeql.Enabled
    value: true

  # To retrieve OptProf data we need to authenticate to the VS drop storage.
  # Get access token with $dn-bot-devdiv-drop-rw-code-rw and dn-bot-dnceng-build-rw-code-rw from DotNet-VSTS-Infra-Access
  # Get $AccessToken-dotnet-build-bot-public-repo from DotNet-Versions-Publish
  - group: DotNet-Versions-Publish
  - group: DotNet-VSTS-Infra-Access
  - group: DotNet-DevDiv-Insertion-Workflow-Variables
  - group: AzureDevOps-Artifact-Feeds-Pats
  - name: _DevDivDropAccessToken
    value: $(dn-bot-devdiv-drop-rw-code-rw)
  - name: ArtifactServices.Drop.PAT
    value: $(dn-bot-devdiv-drop-rw-code-rw)
  - group: DotNet-Roslyn-Insertion-Variables
  - group: AzureDevOps-Artifact-Feeds-Pats

  - name: BuildConfiguration
    value: release
  - name: Roslyn.GitHubEmail
    value: dotnet-build-bot@microsoft.com
  - name: Roslyn.GitHubToken
    value: $(AccessToken-dotnet-build-bot-public-repo)
  - name: Roslyn.GitHubUserName
    value: dotnet-build-bot

  - name: Insertion.InsertToolset
    value: true
  - name: Insertion.CreateDraftPR
    value: true
  - name: Insertion.TitlePrefix
    value: "[Auto Insertion]"
  - name: Insertion.TitleSuffix
    value: ""

  - ${{ if and(notin(variables['Build.Reason'], 'PullRequest'), eq(variables['Build.SourceBranch'], 'refs/heads/main')) }}:
      - name: enableSourceIndex
        value: true

extends:
  template: azure-pipelines/MicroBuild.1ES.Official.yml@MicroBuildTemplate
  parameters:
    featureFlags:
      autoBaseline: true
    sdl:
      sourceAnalysisPool:
        name: NetCore1ESPool-Svc-Internal
        image: 1es-windows-2022
        os: windows
      sbom:
        enabled: false
      suppression:
        suppressionFile: $(Build.SourcesDirectory)\eng\config\guardian\.gdnsuppres
      policheck:
        enabled: true
      tsa:
        enabled: true
        configFile: "$(Build.SourcesDirectory)/eng/TSAConfig.gdntsa"
    pool:
      name: NetCore1ESPool-Svc-Internal
      image: windows.vs2017.amd64
      os: windows
    customBuildTags:
      - ES365AIMigrationTooling
    stages:
      - stage: build
        displayName: Build and Test

        jobs:
          - job: OfficialBuild
            displayName: Official Build
            timeoutInMinutes: 360
            templateContext:
              outputParentDirectory: $(Build.ArtifactStagingDirectory)
              outputs:
                - output: pipelineArtifact
                  displayName: 'Publish Build Logs'
                  condition: succeededOrFailed()
                  targetPath: '$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\logs'
                  artifactName: ReleaseBuildLogs_Attempt$(System.JobAttempt)
                  artifactType: container
                  sbomEnabled: false
                - output: pipelineArtifact
                  displayName: Publish Symbols artifacts
                  condition: succeededOrFailed()
                  targetPath: $(Build.ArtifactStagingDirectory)\symbols
                  artifactName: ReleaseSymbols
                  artifactType: container
                  sbomEnabled: false
                - output: pipelineArtifact
                  displayName: Publish NuGet Packages as Artifact
                  targetPath: $(Build.ArtifactStagingDirectory)\Packages
                  artifactName: ReleasePackages
                  artifactType: container
                  sbomEnabled: false
                - output: pipelineArtifact
                  displayName: Publish Insertion Parameters
                  targetPath: $(Build.ArtifactStagingDirectory)\Insertion
                  artifactName: InsertionParameters
                  artifactType: container
                  sbomEnabled: false

            steps:
              - task: NuGetToolInstaller@1
                displayName: 'Use NuGet 6.2.4'
                inputs:
                  versionSpec: 6.2.4

              - task: NuGetAuthenticate@1
                inputs:
                  nuGetServiceConnections: azure-public/vs-impl, azure-public/vssdk, devdiv/engineering, devdiv/dotnet-core-internal-tooling

              - task: NuGetCommand@2
                inputs:
                  command: custom
                  arguments: 'locals all -clear'

              - task: UseDotNet@2
                displayName: 'Use .NET Core sdk'
                inputs:
                  packageType: sdk
                  useGlobalJson: true
                  workingDirectory: '$(Build.SourcesDirectory)'

              - task: NuGetCommand@2
                displayName: 'NuGet restore'
                inputs:
                  nugetConfigPath: 'NuGet.Config'
                  feedsToUse: 'config'
                  restoreSolution: 'build\ToolsetPackages\InternalToolset.csproj'

              - task: MicroBuildSigningPlugin@4
                inputs:
                  signType: ${{ parameters.SignType }}
                  zipSources: false
                  feedSource: https://dnceng.pkgs.visualstudio.com/_packaging/MicroBuildToolset/nuget/v3/index.json
                  # Set ConnectedPMEServiceName if the build is a CI build, otherwise it is not needed
                  ${{ if or(eq(variables['Build.Reason'], 'IndividualCI'), eq(variables['Build.Reason'], 'Schedule'), parameters.PMEOverride) }}:
                     ConnectedPMEServiceName: 248d384a-b39b-46e3-8ad5-c2c210d5e7ca
                condition: and(succeeded(), in('${{ parameters.SignType }}', 'test', 'real'))

              - task: VSBuild@1
                inputs:
                  solution: 'src/Tools/MicroBuild/Build.proj'
                  vsVersion: '15.0'
                  msbuildArgs: >- 
                          /p:TreatWarningsAsErrors=true 
                          /p:DeployExtension=false 
                          /p:TrackFileAccess=false
                          /p:OfficialBuild=true 
                          /p:VisualStudioVersion=14.0 
                          /flp1:Summary;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.log 
                          /flp2:WarningsOnly;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.wrn 
                          /flp3:ErrorsOnly;Verbosity=diagnostic;Encoding=UTF-8;LogFile=$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)\Roslyn.err 
                          /p:RoslynMyGetApiKey=$(Roslyn.MyGetApiKey) 
                          /p:RoslynNuGetApiKey=$(Roslyn.NuGetApiKey) 
                          /p:RoslynGitHubEmail=$(Roslyn.GitHubEmail) 
                          /p:RoslynGitHubToken=$(Roslyn.GitHubToken) 
                          /p:RoslynGitHubUserName=$(Roslyn.GitHubUserName) 
                          /p:PB_PublishBlobFeedKey=$(PB_PublishBlobFeedKey) 
                          /p:PB_SkipTests=${{ parameters.SkipTests }}
                          /p:PublishStableVersions=false 
                          /p:VersionStampToPublish=prerelease
                  platform: '$(BuildPlatform)'
                  configuration: '$(BuildConfiguration)'
                  maximumCpuCount: true
                  logProjectEvents: false

              - task: PublishTestResults@2
                displayName: Publish xUnit Test Results
                inputs:
                  testRunner: XUnit
                  testResultsFiles: '**/xUnitResults/*.xml'
                  mergeTestResults: true
                  testRunTitle: 'Unit Tests'
                condition: and(succeededOrFailed(), ${{ not(parameters.SkipTests) }})

              - task: CopyFiles@2
                displayName: 'Collect Built Symbols from $(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                inputs:
                  SourceFolder: '$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                  Contents: '**\*.pdb'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)\symbols'
                  FlattenFolders: true
                condition: succeeded()

              - task: PublishSymbols@2
                inputs:
                  SymbolsFolder: '$(Build.ArtifactStagingDirectory)\symbols'
                  SearchPattern: '**/*.pdb'
                  IndexSources: false
                  SymbolServerType: TeamServices
                displayName: Publish symbols to symbol server
                condition: and(succeeded(), eq(variables['SignType'], 'Real'))

              - task: CopyFiles@2
                displayName: 'Collect Built Packages from $(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                inputs:
                  SourceFolder: '$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                  Contents: '**\*.nupkg'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)\packages'
                  FlattenFolders: true
                condition: succeeded()

              - task: 1ES.PublishNuGet@1
                displayName: 'NuGet push (VS-CoreXtFeeds)'
                inputs:
                  packageParentPath: '$(Build.ArtifactStagingDirectory)'
                  packagesToPush: $(Build.ArtifactStagingDirectory)/packages/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg
                  nuGetFeedType: 'internal'
                  publishVstsFeed: 37a181e8-5ec9-4e8d-a499-07b754f9b4f8
                  allowPackageConflicts: true
                condition: succeeded()

              - task: CopyFiles@2
                displayName: 'Collect vsman from $(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                inputs:
                  SourceFolder: '$(Build.SourcesDirectory)\Binaries\$(BuildConfiguration)'
                  Contents: '**\*.vsman'
                  TargetFolder: '$(Build.ArtifactStagingDirectory)\insertion'
                  FlattenFolders: true
                condition: succeeded()

              - task: 1ES.MicroBuildVstsDrop@1
                displayName: "Upload artifacts to VSTS Drop"
                inputs:
                  dropFolder: $(Build.ArtifactStagingDirectory)/insertion
                  dropName: 'Products/$(System.TeamProject)/$(Build.Repository.Name)/$(Build.SourceBranchName)/$(Build.BuildNumber)'
                  dropRetentionDays: 183
                  accessToken: $(_DevDivDropAccessToken)
                  skipUploadIfExists: true
                  dropServiceUri: 'https://devdiv.artifacts.visualstudio.com'
                  vsDropServiceUri: 'https://vsdrop.corp.microsoft.com/file/v1'
                condition: and(succeeded(), eq(variables['SignType'], 'Real'))
