# Roslyn VS integration test gate pipeline for real-signed Visual Studio builds.

trigger: none
pr: none

resources:
  repositories:
  - repository: DartLabTemplates
    type: git
    name: DevDiv/DartLab.Templates
    ref: refs/heads/main
  - repository: VSTemplates
    type: git
    name: DevDiv/VS.Templates
    ref: refs/heads/main
  - repository: RoslynMirror
    endpoint: dnceng-internal-code-access
    type: git
    name: internal/dotnet-roslyn
    ref: $(Build.SourceBranch)

parameters:
  - name: prNumber
    type: string
    default: 'None'
  - name: sha
    type: string
    default: 'None'
  - name: EnforceLatestCommit
    type: boolean
    default: true
  - name: visualStudioBootstrapperURI
    type: string
    default: '(default)'
  - name: testCaseFilter
    type: string
    default: '(all)'
  - name: skipCustomRoslynDeploy
    type: boolean
    default: false
  - name: testsCommitHash
    type: string
    default: '(default)'
  - name: testsCommitFromVisualStudioBuild
    type: boolean
    default: false
  # Set to 'stop' if you want to keep the test machines around for investigation after test completion.
  - name: testMachineCleanUpStrategy
    displayName: Test Machine Clean Up Strategy
    type: string
    default: delete
    values:
    - delete
    - stop
  # The retention period for the test machine (expressed as <Days>:<Hours>:<Minutes>:<Seconds>)
  - name: testMachineRetention
    displayName: Test Machine Retention (format "D:H:M:S")
    type: string
    default: 1:0:0:0 # 1 day default

extends:
  template: /DartLab/1ES/pipelines/ci/real-sign.yml@VSTemplates
  parameters:
    testStages:
    - template: /eng/pipelines/test-gates/staging/stages.yml@self
      parameters:
        prNumber: ${{ parameters.prNumber }}
        sha: ${{ parameters.sha }}
        EnforceLatestCommit: ${{ parameters.EnforceLatestCommit }}
        visualStudioBootstrapperURI: ${{ parameters.visualStudioBootstrapperURI }}
        testCaseFilter: ${{ parameters.testCaseFilter }}
        skipCustomRoslynDeploy: ${{ parameters.skipCustomRoslynDeploy }}
        testsCommitHash: ${{ parameters.testsCommitHash }}
        testsCommitFromVisualStudioBuild: ${{ parameters.testsCommitFromVisualStudioBuild }}
        testMachineCleanUpStrategy: ${{ parameters.testMachineCleanUpStrategy }}
        testMachineRetention: ${{ parameters.testMachineRetention }}
