# Branches that trigger a build on commit
trigger:
- main
- main-vs-deps
- release/*
- features/*
- demos/*

# Branches that trigger builds on PR
pr:
  branches:
    include:
    - main
    - main-vs-deps
    - release/*
    - features/*
    - demos/*
  paths:
    exclude:
      - docs/*
      - eng/config/PublishData.json
      - src/Features/LanguageServer/Microsoft.CommonLanguageServerProtocol.Framework/README.md
      - .vscode/*
      - .github/*
      - .devcontainer/*
      - .git-blame-ignore-revs
      - .vsconfig
      - CODE-OF-CONDUCT.md
      - CONTRIBUTING.md
      - README.md

stages:
- stage: Windows_Debug_Build
  dependsOn: []
  jobs:
  - template: eng/pipelines/build-windows-job.yml
    parameters:
      jobName: Build_Windows_Debug
      testArtifactName: Transport_Artifacts_Windows_Debug
      configuration: Debug
      queueName: windows.vs2022preview.amd64.open
      restoreArguments: -msbuildEngine dotnet /p:UsingToolVSSDK=false /p:GenerateSatelliteAssemblies=false
      buildArguments: -msbuildEngine dotnet /p:UsingToolVSSDK=false /p:GenerateSatelliteAssemblies=false /p:PublishReadyToRun=false
.yml

