parameters:
  # Optional: dependencies of the job
  dependsOn: ''

  # Optional: A defined YAML pool - https://docs.microsoft.com/en-us/azure/devops/pipelines/yaml-schema?view=vsts&tabs=schema#pool
  pool: {}

  # Optional: Include toolset dependencies in the generated graph files
  includeToolset: false
  
jobs:
- job: Generate_Graph_Files

  dependsOn: ${{ parameters.dependsOn }}

  displayName: Generate Graph Files

  pool: ${{ parameters.pool }}

  variables:
    # Publish-Build-Assets provides: MaestroAccessToken, BotAccount-dotnet-maestro-bot-PAT
    # DotNet-AllOrgs-Darc-Pats provides: dn-bot-devdiv-dnceng-rw-code-pat
    - group: Publish-Build-Assets
    - group: DotNet-AllOrgs-Darc-Pats
    - name: _GraphArguments
      value: -gitHubPat $(BotAccount-dotnet-maestro-bot-PAT) 
        -azdoPat $(dn-bot-devdiv-dnceng-rw-code-pat) 
        -barToken $(MaestroAccessToken) 
        -outputFolder '$(Build.StagingDirectory)/GraphFiles/'
    - ${{ if ne(parameters.includeToolset, 'false') }}:
      - name: _GraphArguments
        value: ${{ variables._GraphArguments }} -includeToolset

  steps:
    - task: PowerShell@2
      displayName: Generate Graph Files
      inputs:
        filePath: eng\common\generate-graph-files.ps1 
        arguments: $(_GraphArguments)
      continueOnError: true
    - task: PublishBuildArtifacts@1
      displayName: Publish Graph to Artifacts
      inputs:
        PathtoPublish: '$(Build.StagingDirectory)/GraphFiles'
        PublishLocation: Container
        ArtifactName: GraphFiles
      continueOnError: true
      condition: always()      
