<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net472</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Build" />
    <PackageReference Include="Microsoft.Build.Tasks.Core" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic.Workspaces" />
    <PackageReference Include="Microsoft.IO.Redist" PrivateAssets="all" />
    <PackageReference Include="System.Text.Json" />
  </ItemGroup>

</Project>
