// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CodeMapper.ICSharpCopilotMapCodeService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.CodeSnippetItem))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.ICSharpCopilotContextProviderService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.IContextItem))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.IContextProvider))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.Importance))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Completion.TraitItem))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotAnalysisUtilities))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotChecksumWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotDocumentationCommentProposalWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotDocumentationCommentProposedEditWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotDocumentationCommentTagType))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotOnTheFlyDocsInfoWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotOnTheFlyDocsRelevantFileInfoWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.CopilotUtilities))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.GenerateImplementation.ImplementationDetailsWrapper))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.IExternalCSharpCopilotCodeAnalysisService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.IExternalCSharpCopilotGenerateDocumentationService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.IExternalCSharpCopilotGenerateImplementationService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.IExternalCSharpOnTheFlyDocsService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.Analyzer.AbstractCopilotCodeAnalysisService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.Analyzer.CSharp.CSharpCopilotCodeAnalysisService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.CodeMapper.CSharpMapCodeService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.Completion.CSharpContextProviderService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.SemanticSearch.CopilotSemanticSearchQueryExecutor))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.SemanticSearch.CopilotSemanticSearchQueryService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.Internal.SemanticSearch.CopilotSemanticSearchSolutionService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.CopilotSemanticSearchQueryResults))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.CopilotSemanticSearchUtilities))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.ICopilotSemanticSearchQueryExecutor))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.ICopilotSemanticSearchQueryService))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.ICopilotSemanticSearchResultsObserver))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Copilot.SemanticSearch.ICopilotSemanticSearchSolutionService))]
