#!/bin/sh

THISDIR=$(dirname $0)

# CoreCLR / CoreFX does not execute reliably with an unlimited 
# stack.  Make on Linux can execute child processes with an 
# unlimited stack so force it back to a known good limit
#
# https://github.com/dotnet/coreclr/issues/2467
ulimit -s 8192

chmod +x $THISDIR/corerun 2>/dev/null
$THISDIR/corerun $THISDIR/vbc.exe "$@"

