<!-- Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the MIT license.  See License.txt in the project root for license information.-->
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>

    <!-- VSIX -->
    <ExtensionInstallationRoot>CommonExtensions</ExtensionInstallationRoot>
    <ExtensionInstallationFolder>Microsoft\Templates\Editorconfig</ExtensionInstallationFolder>
    <VisualStudioInsertionComponent>Templates.Editorconfig.Setup</VisualStudioInsertionComponent>
    <SetupProductArch>Neutral</SetupProductArch>
    <IncludeAssemblyInVSIXContainer>false</IncludeAssemblyInVSIXContainer>
    <GeneratePkgDefFile>false</GeneratePkgDefFile>
    <EnableDefaultEmbeddedResourceItems>false</EnableDefaultEmbeddedResourceItems>
    <EnableDefaultItems>false</EnableDefaultItems>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Wizard\Microsoft.VisualStudio.Templates.Editorconfig.Wizard.csproj">
      <Name>Microsoft.VisualStudio.Templates.Editorconfig.Wizard</Name>
      <IncludeOutputGroupsInVSIX>BuiltProjectOutputGroup%3bGetCopyToOutputDirectoryItems</IncludeOutputGroupsInVSIX>
      <IncludeOutputGroupsInVSIXLocalOnly>DebugSymbolsProjectOutputGroup%3b</IncludeOutputGroupsInVSIXLocalOnly>
      <ForceIncludeInVSIX>true</ForceIncludeInVSIX>
    </ProjectReference>
    <None Include="source.extension.vsixmanifest" />
    <None Include="*.vstemplate" />
    <VSTemplate Include="Editorconfig.CS.Default.vstemplate">
      <OutputSubPath>General</OutputSubPath>
    </VSTemplate>
    <VSTemplate Include="Editorconfig.CS.DotNet.vstemplate">
      <OutputSubPath>General</OutputSubPath>
    </VSTemplate>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="UpdateTemplateVersion" GeneratePathProperty="true" ExcludeAssets="all" PrivateAssets="all" />
  </ItemGroup>

  <!-- rewriting of .vstemplate files to reference the correct assembly version number -->
  <UsingTask AssemblyFile="$(PkgUpdateTemplateVersion)\tools\net472\UpdateTemplateVersion.dll" TaskName="UpdateTemplateVersion" />
  <Target Name="UpdateAssemblyVersionInTemplates" BeforeTargets="GetZipFilesFromVSTemplates">
    <ItemGroup>
      <_OriginalVSTemplate Include="@(VSTemplate)" />
    </ItemGroup>
    <UpdateTemplateVersion VSTemplatesToRewrite="@(VSTemplate)" AssemblyVersion="$(AssemblyVersion)" IntermediatePath="ModifiedTemplates">
      <Output TaskParameter="NewVSTemplates" ItemName="VSTemplate" />
    </UpdateTemplateVersion>
    <ItemGroup>
      <VSTemplate Remove="@(_OriginalVSTemplate)" />
    </ItemGroup>
  </Target>
</Project>
