' Copyright (c) Microsoft.  All Rights Reserved.  Licensed under the Apache License, Version 2.0.  See License.txt in the project root for license information.

Namespace Microsoft.VisualStudio.LanguageServices.VisualBasic.Help
    Friend NotInheritable Class HelpKeywords

        Friend Shared Assign As String = "vb.Assign"
        Friend Shared QueryAggregate As String = "vb.QueryAggregate"
        Friend Shared QueryAggregateIn As String = "vb.QueryAggregateIn"
        Friend Shared QueryAggregateInto As String = "vb.QueryAggregateInto"
        Friend Shared ModuleAttribute As String = "vb.ModuleAttribute"
        Friend Shared AssemblyAttribute As String = "vb.AssemblyAttribute"
        Friend Shared Attributes As String = "vb.Attributes"
        Friend Shared Constructor As String = "vb.Constructor"
        Friend Shared QueryDistinct As String = "vb.QueryDistinct"
        Friend Shared EndDefinition As String = "vb.EndDefinition"
        Friend Shared AddHandlerMethod As String = "vb.AddHandlerMethod"
        Friend Shared RemoveHandlerMethod As String = "vb.RemoveHandlerMethod"
        Friend Shared RaiseEventMethod As String = "vb.RaiseEventMethod"
        Friend Shared ImplementsClause As String = "vb.ImplementsClause"
        Friend Shared TypeInfer As String = "vb.TypeInfer"
        Friend Shared ForEach As String = "vb.ForEach"
        Friend Shared QueryFrom As String = "vb.QueryFrom"
        Friend Shared QueryGroup As String = "vb.QueryGroup"
        Friend Shared QueryGroupBy As String = "vb.QueryGroupBy"
        Friend Shared QueryGroupByInto As String = "vb.QueryGroupByInto"
        Friend Shared QueryGroupJoin As String = "vb.QueryGroupJoin"
        Friend Shared QueryGroupJoinIn As String = "vb.QueryGroupJoinIn"
        Friend Shared QueryGroupJoinOn As String = "vb.QueryGroupJoinOn"
        Friend Shared QueryGroupJoinInto As String = "vb.QueryGroupJoinInto"
        Friend Shared QueryGroupRef As String = "vb.QueryGroupRef"
        Friend Shared IfOperator As String = "vb.IfOperator"
        Friend Shared ImportsXmlns As String = "vb.ImportsXmlns"
        Friend Shared QueryJoin As String = "vb.QueryJoin"
        Friend Shared QueryJoinIn As String = "vb.QueryJoinIn"
        Friend Shared QueryJoinOn As String = "vb.QueryJoinOn"
        Friend Shared Colon As String = "vb.Colon"
        Friend Shared LambdaFunction As String = "vb.LambdaFunction"
        Friend Shared QueryLet As String = "vb.QueryLet"
        Friend Shared PartialMethod As String = "vb.PartialMethod"
        Friend Shared OnError As String = "vb.OnError"
        Friend Shared OptionExplicit As String = "vb.OptionExplicit"
        Friend Shared OptionStrict As String = "vb.OptionStrict"
        Friend Shared OptionCompare As String = "vb.OptionCompare"
        Friend Shared OptionInfer As String = "vb.OptionInfer"
        Friend Shared QueryAscending As String = "vb.QueryAscending"
        Friend Shared QueryDescending As String = "vb.QueryDescending"
        Friend Shared QueryOrderBy As String = "vb.QueryOrderBy"
        Friend Shared PreprocessorConst As String = "vb.#Const"
        Friend Shared PreprocessorIf As String = "vb.#If"
        Friend Shared Region As String = "vb.#Region"
        Friend Shared [Redim] As String = "vb.Redim"
        Friend Shared ClassConstraint As String = "vb.ClassConstraint"
        Friend Shared QuerySelect As String = "vb.QuerySelect"
        Friend Shared QuerySkip As String = "vb.QuerySkip"
        Friend Shared QuerySkipWhile As String = "vb.QuerySkipWhile"
        Friend Shared QueryTake As String = "vb.QueryTake"
        Friend Shared QueryTakeWhile As String = "vb.QueryTakeWhile"
        Friend Shared Negate As String = "vb.Negate"
        Friend Shared StructureConstraint As String = "vb.StructureConstraint"
        Friend Shared QueryWhere As String = "vb.QueryWhere"
        Friend Shared XmlLiteralCdata As String = "vb.XmlLiteralCdata"
        Friend Shared XmlLiteralComment As String = "vb.XmlLiteralComment"
        Friend Shared XmlLiteralDocument As String = "vb.XmlLiteralDocument"
        Friend Shared XmlLiteralElement As String = "vb.XmlLiteralElement"
        Friend Shared XmlEmbeddedExpression As String = "vb.XmlEmbeddedExpression"
        Friend Shared XmlLiteralProcessingInstruction As String = "vb.XmlLiteralProcessingInstruction"
        Friend Shared NewConstraint As String = "vb.NewConstraint"
        Friend Shared AnonymousKey As String = "vb.AnonymousKey"
        Friend Shared AnonymousType As String = "vb.AnonymousType"
        Friend Shared ObjectInitializer As String = "vb.ObjectInitializer"
        Friend Shared ExtensionMethods As String = "vb.ExtensionMethods"
        Friend Shared Nullable As String = "vb.Nullable"
        Friend Shared AutoProperty As String = "vb.AutoImplementedProperty"
        Friend Shared XmlDocComment As String = "vb.XmlDocComment"
        Friend Shared [Rem] As String = "vb.Rem"
        Friend Shared QueryFromIn As String = "vb.QueryFromIn"
        Friend Shared QueryFromLet As String = "vb.QueryFromLet"
        Friend Shared XmlPropertyChildAxis As String = "vb.XmlPropertyChildAxis"
        Friend Shared XmlPropertyDescendantsAxis As String = "vb.XmlPropertyDescendantsAxis"
        Friend Shared XmlPropertyAttributeAxis As String = "vb.XmlPropertyAttributeAxis"
        Friend Shared XmlPropertyExtensionValue As String = "vb.XmlPropertyExtensionValue"
        Friend Shared MyNamespaceKeyword As String = "vb.My"
        Friend Shared CollectionInitializer As String = "vb.CollectionInitializer"
        Friend Shared VarianceIn As String = "vb.VarianceIn"
        Friend Shared VarianceOut As String = "vb.VarianceOut"
        Friend Shared TaskListUserComments As String = "vbc0"
        Friend Shared Main As String = "vb.Main"
        Friend Shared Async As String = "vb.Async"
        Friend Shared Iterator As String = "vb.Iterator"
        Friend Shared Await As String = "vb.Await"
        Friend Shared Yield As String = "vb.Yield"

    End Class

End Namespace
