// <auto-generated />
using System.Runtime.CompilerServices;

[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Apex.ApexAsynchronousOperationListenerProviderAccessor))]
[assembly: TypeForwardedTo(typeof(Microsoft.CodeAnalysis.ExternalAccess.Apex.IApexAsynchronousOperationListenerProviderAccessor))]
