// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text;

namespace HtmlSchemaGenerator;

/// <summary>
/// Emits a .g.cs file containing static HTML schema data as compiled lookup tables.
/// </summary>
internal static class CodeEmitter
{
    public static string Emit(HtmlSchema schema)
    {
        var sb = new StringBuilder(2 * 1024);

        EmitHeader(sb, includeFrozen: true);
        EmitSchemaDataClass(sb, schema);

        return sb.ToString();
    }

    public static string EmitSharedData(HtmlSchema schema)
    {
        var sb = new StringBuilder(16 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Shared groups of valid attribute values (used by more than one attribute).");
        sb.AppendLine("/// Derived from XSD simpleType enumerations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributeValueGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Shared");
        sb.AppendLine("    {");

        var (shared, _) = BuildValueArrayMaps(schema);
        EmitValueArrayFields(sb, shared, "        ");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitUniqueValueGroups(HtmlSchema schema)
    {
        var sb = new StringBuilder(16 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Unique groups of valid attribute values (used by exactly one attribute).");
        sb.AppendLine("/// Derived from XSD simpleType enumerations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributeValueGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Unique");
        sb.AppendLine("    {");

        var (_, unique) = BuildValueArrayMaps(schema);
        EmitValueArrayFields(sb, unique, "        ");

        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitSharedAttrs(HtmlSchema schema)
    {
        var sb = new StringBuilder(16 * 1024);

        EmitHeader(sb);

        var (shared, unique) = BuildValueArrayMaps(schema);
        var attrInstanceMap = BuildAttrInstanceMap(schema, shared, unique);
        EmitSharedAttrInstances(sb, attrInstanceMap);

        return sb.ToString();
    }

    public static string EmitUniqueAttrs(HtmlSchema schema)
    {
        var sb = new StringBuilder(32 * 1024);

        EmitHeader(sb);

        var (shared, unique) = BuildValueArrayMaps(schema);
        var attrInstanceMap = BuildAttrInstanceMap(schema, shared, unique);
        var uniqueAttrMap = BuildUniqueAttrMap(schema, shared, unique, attrInstanceMap);
        EmitUniqueAttrInstances(sb, schema, shared, unique, uniqueAttrMap);

        return sb.ToString();
    }

    private static void EmitHeader(StringBuilder sb, bool includeFrozen = false)
    {
        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC by HtmlCompletionDataGenerator from html.xsd + html.loc");
        sb.AppendLine("// Source: VS HTML Editor schema files (src/Languages/html/Editor/Schemas/SchemaFiles/)");
        sb.AppendLine("// Do not edit manually. Re-run the generator to update.");
        sb.AppendLine();
        sb.AppendLine("#nullable enable");
        sb.AppendLine();

        if (includeFrozen)
        {
            sb.AppendLine("using System;");
            sb.AppendLine("using System.Collections.Generic;");
            sb.AppendLine("#if NET8_0_OR_GREATER");
            sb.AppendLine("using System.Collections.Frozen;");
            sb.AppendLine("#else");
            sb.AppendLine("using System.Linq;");
            sb.AppendLine("#endif");
        }

        sb.AppendLine("using System.Collections.Immutable;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.CodeAnalysis.Razor.Completion.Html;");
        sb.AppendLine();
    }

    public static string EmitElementKindEnum()
    {
        var sb = new StringBuilder(512);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Classifies an HTML element for icon selection in completion lists.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal enum HtmlElementKind : byte");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>A standard HTML element.</summary>");
        sb.AppendLine("    Default = 0,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>An Angular directive element (e.g., ng-form, ng-include).</summary>");
        sb.AppendLine("    Angular = 1,");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitElementInfoStruct()
    {
        var sb = new StringBuilder(2 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Describes an HTML element with its element-specific attributes.");
        sb.AppendLine("/// Global attributes (core, events, microdata, ARIA) are available separately via");
        sb.AppendLine("/// <see cref=\"HtmlCompletionData.GlobalAttributes\"/>.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class HtmlElementInfo");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The tag name of the element (e.g., \"div\", \"input\").</summary>");
        sb.AppendLine("    public string Name { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>A brief description of the element's purpose, loaded from localized resources.</summary>");
        sb.AppendLine("    public string Description { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>URL to the element's specification or reference documentation.</summary>");
        sb.AppendLine("    public string DocumentationUrl { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Baseline availability level: \"high\" (widely available) or \"low\" (newly available), or empty.</summary>");
        sb.AppendLine("    public string Baseline { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The year the feature reached baseline status, or empty.</summary>");
        sb.AppendLine("    public string BaselineDate { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Element-specific attributes. Does not include global attributes.</summary>");
        sb.AppendLine("    public ImmutableArray<HtmlAttributeInfo> Attributes { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Element names allowed as direct children. Empty means void element (no children).");
        sb.AppendLine("    /// For transparent content model elements, see <see cref=\"IsTransparentContent\"/>.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public ImmutableArray<string> AllowedChildren { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// True if this element has a transparent content model (inherits parent's allowed children).");
        sb.AppendLine("    /// Examples: a, noscript, object.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool IsTransparentContent { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// The kind of element, used for icon selection in completion lists.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public HtmlElementKind Kind { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Ancestor element names that disallow this element as a descendant.");
        sb.AppendLine("    /// E.g., form cannot nest inside form; a cannot nest inside a or button.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public ImmutableArray<string> DisallowedAncestors { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// True if this element can be implicitly closed (e.g., li, p, td, tr).");
        sb.AppendLine("    /// A new sibling of the same type implicitly ends the previous one.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool IsImplicitlyClosed { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// When true, this element's content completion is owned by an external provider.");
        sb.AppendLine("    /// Examples: script (JavaScript), style (CSS).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasExternalCompletion { get; }");
        sb.AppendLine();
        sb.AppendLine("    public HtmlElementInfo(");
        sb.AppendLine("        string name,");
        sb.AppendLine("        string documentationUrl,");
        sb.AppendLine("        string baseline = \"\",");
        sb.AppendLine("        string baselineDate = \"\",");
        sb.AppendLine("        ImmutableArray<HtmlAttributeInfo> attributes = default,");
        sb.AppendLine("        ImmutableArray<string> allowedChildren = default,");
        sb.AppendLine("        bool isTransparentContent = false,");
        sb.AppendLine("        HtmlElementKind kind = HtmlElementKind.Default,");
        sb.AppendLine("        ImmutableArray<string> disallowedAncestors = default,");
        sb.AppendLine("        bool isImplicitlyClosed = false,");
        sb.AppendLine("        bool hasExternalCompletion = false)");
        sb.AppendLine("    {");
        sb.AppendLine("        Name = name;");
        sb.AppendLine("        Description = HtmlDescriptions.GetElementDescription(name);");
        sb.AppendLine("        DocumentationUrl = documentationUrl;");
        sb.AppendLine("        Baseline = baseline;");
        sb.AppendLine("        BaselineDate = baselineDate;");
        sb.AppendLine("        Attributes = attributes.IsDefault ? [] : attributes;");
        sb.AppendLine("        AllowedChildren = allowedChildren.IsDefault ? [] : allowedChildren;");
        sb.AppendLine("        IsTransparentContent = isTransparentContent;");
        sb.AppendLine("        Kind = kind;");
        sb.AppendLine("        DisallowedAncestors = disallowedAncestors.IsDefault ? [] : disallowedAncestors;");
        sb.AppendLine("        IsImplicitlyClosed = isImplicitlyClosed;");
        sb.AppendLine("        HasExternalCompletion = hasExternalCompletion;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitAttributeKindEnum()
    {
        var sb = new StringBuilder(512);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Classifies an HTML attribute for icon selection in completion lists.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal enum HtmlAttributeKind : byte");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>A regular HTML attribute.</summary>");
        sb.AppendLine("    Default = 0,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>An event handler attribute (e.g., onclick, onchange).</summary>");
        sb.AppendLine("    Event = 1,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>An ARIA accessibility attribute (e.g., aria-label, aria-hidden).</summary>");
        sb.AppendLine("    Aria = 2,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>An Angular directive attribute (e.g., ng-model, ng-click).</summary>");
        sb.AppendLine("    Angular = 3,");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>A custom data attribute (data-*).</summary>");
        sb.AppendLine("    Data = 4,");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitAttributeInfoStruct()
    {
        var sb = new StringBuilder(2 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Describes an HTML attribute with its valid values (if enumerated).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal sealed class HtmlAttributeInfo");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>The attribute name (e.g., \"class\", \"href\", \"aria-label\").</summary>");
        sb.AppendLine("    public string Name { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>A brief description of the attribute's purpose, loaded from localized resources.</summary>");
        sb.AppendLine("    public string Description { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>URL to the attribute's specification or reference documentation.</summary>");
        sb.AppendLine("    public string DocumentationUrl { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>Baseline availability level: \"high\" (widely available) or \"low\" (newly available), or empty.</summary>");
        sb.AppendLine("    public string Baseline { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>The year the feature reached baseline status, or empty.</summary>");
        sb.AppendLine("    public string BaselineDate { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Known valid values for this attribute (from XSD enumerations).");
        sb.AppendLine("    /// Empty if the attribute accepts freeform values.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public ImmutableArray<string> Values { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// When true, this is a boolean attribute that doesn't require a value (e.g., disabled, checked).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool IsBoolean { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// The kind of attribute, used for icon selection in completion lists.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public HtmlAttributeKind Kind { get; }");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// When true, this attribute's value completion is owned by an external provider.");
        sb.AppendLine("    /// Sources: URI attributes (xsd:anyURI), multivalue attributes");
        sb.AppendLine("    /// (vs:multivalue), and hardcoded attributes (class, style, id).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public bool HasExternalCompletion { get; }");
        sb.AppendLine();
        sb.AppendLine("    public HtmlAttributeInfo(");
        sb.AppendLine("        string name,");
        sb.AppendLine("        string documentationUrl = \"\",");
        sb.AppendLine("        string baseline = \"\",");
        sb.AppendLine("        string baselineDate = \"\",");
        sb.AppendLine("        ImmutableArray<string> values = default,");
        sb.AppendLine("        bool isBoolean = false,");
        sb.AppendLine("        HtmlAttributeKind kind = HtmlAttributeKind.Default,");
        sb.AppendLine("        bool hasExternalCompletion = false)");
        sb.AppendLine("    {");
        sb.AppendLine("        Name = name;");
        sb.AppendLine("        Description = HtmlDescriptions.GetAttributeDescription(name);");
        sb.AppendLine("        DocumentationUrl = documentationUrl;");
        sb.AppendLine("        Baseline = baseline;");
        sb.AppendLine("        BaselineDate = baselineDate;");
        sb.AppendLine("        Values = values.IsDefault ? [] : values;");
        sb.AppendLine("        IsBoolean = isBoolean;");
        sb.AppendLine("        Kind = kind;");
        sb.AppendLine("        HasExternalCompletion = hasExternalCompletion;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitHtmlElements(HtmlSchema schema)
    {
        var sb = new StringBuilder(64 * 1024);

        EmitHeader(sb);

        var (shared, unique) = BuildValueArrayMaps(schema);
        var attrInstanceMap = BuildAttrInstanceMap(schema, shared, unique);
        var uniqueAttrMap = BuildUniqueAttrMap(schema, shared, unique, attrInstanceMap);
        var (sharedElemAttrs, uniqueElemAttrs) = BuildElementAttrArrayMap(schema, shared, unique, attrInstanceMap, uniqueAttrMap);
        var (sharedGroupMap, uniqueGroupMap) = BuildElementGroupMaps(schema);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// All known HTML elements with their metadata, attributes, and allowed children.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class HtmlElements");
        sb.AppendLine("{");

        EmitElements(sb, schema, shared, unique, attrInstanceMap, uniqueAttrMap, sharedElemAttrs, uniqueElemAttrs, sharedGroupMap, uniqueGroupMap);

        sb.AppendLine("}");

        return sb.ToString();
    }

    private static void EmitSchemaDataClass(StringBuilder sb, HtmlSchema schema)
    {
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Public entry point for HTML schema data. Provides element lookup and access to all elements.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class HtmlCompletionData");
        sb.AppendLine("{");

        // Emit the private lookup field first
        EmitLookup(sb, schema);

        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All known HTML elements with their element-specific attributes.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ImmutableArray<HtmlElementInfo> AllElements => HtmlElements.All;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Global attributes (core, events, microdata, ARIA) that apply to all HTML elements.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ImmutableArray<HtmlAttributeInfo> GlobalAttributes => HtmlAttributeGroups.Shared.Global;");
        sb.AppendLine();
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Returns element info by name, or null if not a known HTML element.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static HtmlElementInfo? GetElement(string name)");
        sb.AppendLine("        => s_elements.TryGetValue(name, out var info) ? info : null;");

        sb.AppendLine("}");
    }

    /// <summary>
    /// Collects all unique value arrays across all attributes and assigns field names.
    /// Returns two maps: shared (count > 1) and unique (count == 1).
    /// Uses the XSD simpleType name when available, then the attribute name, then indexed fallback.
    /// </summary>
    private static (Dictionary<string, string> Shared, Dictionary<string, string> Unique) BuildValueArrayMaps(HtmlSchema schema)
    {
        // key = joined values, value = (count, candidate name from simpleType or attribute)
        var valueSets = new Dictionary<string, (int Count, string? TypeName, string? AttrName)>(StringComparer.Ordinal);

        void CountValues(IEnumerable<AttributeData> attrs)
        {
            foreach (var attr in attrs)
            {
                if (attr.Values.Count > 0)
                {
                    var key = string.Join("|", attr.Values);
                    valueSets.TryGetValue(key, out var entry);
                    // Keep the first non-null type name or attribute name we encounter
                    var typeName = entry.TypeName ?? attr.ValueTypeName;
                    var attrName = entry.AttrName ?? (attr.ValueTypeName == null ? attr.Name : null);
                    valueSets[key] = (entry.Count + 1, typeName, attrName);
                }
            }
        }

        CountValues(schema.GlobalAttributes);
        foreach (var element in schema.Elements)
        {
            CountValues(element.Attributes);
        }

        var shared = new Dictionary<string, string>(StringComparer.Ordinal);
        var unique = new Dictionary<string, string>(StringComparer.Ordinal);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);
        var fallbackIndex = 0;

        foreach (var (key, (count, typeName, attrName)) in valueSets.OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            var fieldName = DeriveFieldName(typeName, attrName, usedNames, ref fallbackIndex);
            if (count > 1)
            {
                shared[key] = fieldName;
            }
            else
            {
                unique[key] = fieldName;
            }
        }

        return (shared, unique);
    }



    private static string DeriveFieldName(string? typeName, string? attrName, HashSet<string> usedNames, ref int fallbackIndex)
    {
        // Try simpleType name first: "inputTypeType" → "InputType"
        if (typeName != null)
        {
            var baseName = typeName;
            if (baseName.EndsWith("Type", StringComparison.Ordinal))
            {
                baseName = baseName[..^4];
            }

            var candidate = ToPascalCase(baseName);
            if (usedNames.Add(candidate))
            {
                return candidate;
            }
        }

        // Try attribute name: "aria-checked" → "AriaChecked"
        if (attrName != null)
        {
            var candidate = ToPascalCase(string.Concat(attrName.Split('-').Select((part, i) =>
                i == 0 ? part : char.ToUpperInvariant(part[0]) + part[1..])));
            if (usedNames.Add(candidate))
            {
                return candidate;
            }
        }

        // Fallback for collisions
        string fallback;
        do
        {
            fallback = $"Values{fallbackIndex++}";
        } while (!usedNames.Add(fallback));

        return fallback;
    }

    private static void EmitValueArrayFields(StringBuilder sb, Dictionary<string, string> valueArrayMap, string indent = "    ")
    {
        if (valueArrayMap.Count == 0) return;

        foreach (var (key, fieldName) in valueArrayMap.OrderBy(kv => kv.Value, StringComparer.Ordinal))
        {
            var values = key.Split('|');
            sb.AppendLine($"{indent}internal static readonly ImmutableArray<string> {fieldName} = [{string.Join(", ", values.Select(EscapeString))}];");
        }
    }

    /// <summary>
    /// Builds a map of attribute instance expressions that appear more than once → field name.
    /// </summary>
    private static Dictionary<string, string> BuildAttrInstanceMap(HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap)
    {
        var instances = new Dictionary<string, int>(StringComparer.Ordinal);

        void Count(IEnumerable<AttributeData> attrs)
        {
            foreach (var attr in attrs)
            {
                var key = GetAttrInstanceKey(attr, schema, sharedValueMap, uniqueValueMap);
                instances.TryGetValue(key, out var count);
                instances[key] = count + 1;
            }
        }

        Count(schema.GlobalAttributes);
        foreach (var element in schema.Elements)
        {
            Count(element.Attributes);
        }

        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var (key, count) in instances.Where(kv => kv.Value > 1).OrderBy(kv => kv.Key, StringComparer.Ordinal))
        {
            // Derive field name from the attribute name embedded in the key
            var attrName = key.Split('|')[0]; // first segment is the attribute name
            var camelCase = string.Concat(attrName.Split('-').Select((part, i) =>
                i == 0 ? part : char.ToUpperInvariant(part[0]) + part[1..]));
            var candidate = ToPascalCase(camelCase);
            if (!usedNames.Add(candidate))
            {
                var idx = 2;
                while (!usedNames.Add($"{candidate}{idx}")) idx++;
                candidate = $"{candidate}{idx}";
            }
            map[key] = candidate;
        }

        return map;
    }

    private static string GetAttrInstanceKey(AttributeData attr, HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap)
    {
        var url = GetUrl(attr.DescriptionId, schema);
        var valuesExpr = GetValuesExpression(attr, sharedValueMap, uniqueValueMap);
        // key format: name|url|valuesExpr|boolean|event|icon|hasExternalCompletion|baseline|baselineDate
        return $"{attr.Name}|{url}|{valuesExpr}|{attr.IsBoolean}|{attr.IsEvent}|{attr.Icon ?? ""}|{attr.HasExternalCompletion}|{attr.Baseline}|{attr.BaselineDate}";
    }

    private static string GetValuesExpression(AttributeData attr, Dictionary<string, string> sharedValueArrayMap, Dictionary<string, string> uniqueValueArrayMap)
    {
        if (attr.Values.Count == 0)
        {
            return "[]";
        }

        var key = string.Join("|", attr.Values);
        if (sharedValueArrayMap.TryGetValue(key, out var sharedFieldName))
        {
            return $"HtmlAttributeValueGroups.Shared.{sharedFieldName}";
        }

        if (uniqueValueArrayMap.TryGetValue(key, out var uniqueFieldName))
        {
            return $"HtmlAttributeValueGroups.Unique.{uniqueFieldName}";
        }

        return $"[{string.Join(", ", attr.Values.Select(EscapeString))}]";
    }

    private static void EmitSharedAttrInstances(StringBuilder sb, Dictionary<string, string> attrInstanceMap)
    {
        if (attrInstanceMap.Count == 0) return;

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Shared attribute instances referenced by multiple elements, deduplicated for reduced allocations.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributes");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Shared");
        sb.AppendLine("    {");
        foreach (var (key, fieldName) in attrInstanceMap.OrderBy(kv => kv.Value, StringComparer.Ordinal))
        {
            var parts = key.Split('|');
            var name = parts[0];
            var url = parts[1];
            var valuesExpr = parts[2];
            var isBoolean = bool.Parse(parts[3]);
            var isEvent = bool.Parse(parts[4]);
            var icon = parts.Length > 5 ? parts[5] : "";
            var hasExternalCompletion = parts.Length > 6 && bool.Parse(parts[6]);
            var baseline = parts.Length > 7 ? parts[7] : "";
            var baselineDate = parts.Length > 8 ? parts[8] : "";

            sb.AppendLine($"        internal static readonly HtmlAttributeInfo {fieldName} = new({BuildAttrCtorArgs(name, url, baseline, baselineDate, valuesExpr, isBoolean, isEvent, icon, hasExternalCompletion)});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    /// <summary>
    /// Builds a map from (elementName, attrInstanceKey) → field name for attributes that appear only once.
    /// </summary>
    private static Dictionary<string, string> BuildUniqueAttrMap(HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap, Dictionary<string, string> attrInstanceMap)
    {
        var map = new Dictionary<string, string>(StringComparer.Ordinal);
        var usedNames = new HashSet<string>(StringComparer.Ordinal);

        void Process(string ownerName, IEnumerable<AttributeData> attrs)
        {
            foreach (var attr in attrs)
            {
                var instanceKey = GetAttrInstanceKey(attr, schema, sharedValueMap, uniqueValueMap);
                if (attrInstanceMap.ContainsKey(instanceKey))
                    continue; // already shared

                var compositeKey = $"{ownerName}|{instanceKey}";
                if (map.ContainsKey(compositeKey))
                    continue;

                var attrCamel = string.Concat(attr.Name.Split('-').Select((part, i) =>
                    i == 0 ? part : char.ToUpperInvariant(part[0]) + part[1..]));
                var ownerCamel = string.Concat(ownerName.Split('-').Select((part, i) =>
                    i == 0 ? part : char.ToUpperInvariant(part[0]) + part[1..].Replace("-", "")));
                var candidate = $"{ToPascalCase(ownerCamel)}_{ToPascalCase(attrCamel)}";
                if (!usedNames.Add(candidate))
                {
                    var idx = 2;
                    while (!usedNames.Add($"{candidate}{idx}")) idx++;
                    candidate = $"{candidate}{idx}";
                }
                map[compositeKey] = candidate;
            }
        }

        Process("global", schema.GlobalAttributes);
        foreach (var element in schema.Elements)
        {
            Process(element.Name, element.Attributes);
        }

        return map;
    }

    private static void EmitUniqueAttrInstances(StringBuilder sb, HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap, Dictionary<string, string> uniqueAttrMap)
    {
        if (uniqueAttrMap.Count == 0) return;

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Attribute instances that are unique to a single element.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributes");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Unique");
        sb.AppendLine("    {");
        foreach (var (compositeKey, fieldName) in uniqueAttrMap.OrderBy(kv => kv.Value, StringComparer.Ordinal))
        {
            // compositeKey = "elementName|attrName|desc|url|valuesExpr|boolean|event|icon"
            var firstPipe = compositeKey.IndexOf('|');
            var instanceKey = compositeKey[(firstPipe + 1)..];
            var parts = instanceKey.Split('|');
            var name = parts[0];
            var url = parts[1];
            var valuesExpr = parts[2];
            var isBoolean = bool.Parse(parts[3]);
            var isEvent = bool.Parse(parts[4]);
            var icon = parts.Length > 5 ? parts[5] : "";
            var hasExternalCompletion = parts.Length > 6 && bool.Parse(parts[6]);
            var baseline = parts.Length > 7 ? parts[7] : "";
            var baselineDate = parts.Length > 8 ? parts[8] : "";

            sb.AppendLine($"        internal static readonly HtmlAttributeInfo {fieldName} = new({BuildAttrCtorArgs(name, url, baseline, baselineDate, valuesExpr, isBoolean, isEvent, icon, hasExternalCompletion)});");
        }
        sb.AppendLine("    }");
        sb.AppendLine("}");
    }

    private static void EmitElements(StringBuilder sb, HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap, Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap, Dictionary<string, string> sharedElemAttrMap, Dictionary<string, string> uniqueElemAttrMap, Dictionary<string, string> sharedGroupMap, Dictionary<string, string> uniqueGroupMap)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// All known HTML elements.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static ImmutableArray<HtmlElementInfo> All { get; } =");
        sb.AppendLine("    [");

        foreach (var element in schema.Elements.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase))
        {
            EmitElementInfo(sb, element, schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap, sharedElemAttrMap, uniqueElemAttrMap, sharedGroupMap, uniqueGroupMap);
        }

        sb.AppendLine("    ];");
    }

    private static void EmitElementInfo(StringBuilder sb, ElementData element, HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap, Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap, Dictionary<string, string> sharedElemAttrMap, Dictionary<string, string> uniqueElemAttrMap, Dictionary<string, string> sharedGroupMap, Dictionary<string, string> uniqueGroupMap)
    {
        var descId = element.DescriptionId;
        var url = GetUrl(descId, schema);
        var baseline = element.Baseline;
        var baselineDate = element.BaselineDate;
        var isTransparent = element.AllowedChildren.Count == 1 && element.AllowedChildren[0] == "*";
        var hasChildren = element.AllowedChildren.Count > 0 && !isTransparent;

        // Build the list of trailing optional parameters
        var trailingParams = new List<string>();
        if (baseline != "") trailingParams.Add($"baseline: {EscapeString(baseline)}");
        if (baselineDate != "") trailingParams.Add($"baselineDate: {EscapeString(baselineDate)}");
        if (hasChildren)
        {
            var childrenExpr = GetChildrenExpression(element, schema, sharedGroupMap, uniqueGroupMap);
            if (childrenExpr != null)
            {
                trailingParams.Add($"allowedChildren: {childrenExpr}");
            }
            else
            {
                // Fallback inline (should not happen with complete maps)
                var inlineChildren = string.Join(", ",
                    element.AllowedChildren.OrderBy(c => c, StringComparer.OrdinalIgnoreCase).Select(c => $"\"{c}\""));
                trailingParams.Add($"allowedChildren: [{inlineChildren}]");
            }
        }

        if (isTransparent) trailingParams.Add("isTransparentContent: true");
        if (element.HasCustomIcon) trailingParams.Add("kind: HtmlElementKind.Angular");
        if (!string.IsNullOrEmpty(element.DisallowedAncestors))
        {
            var ancestors = element.DisallowedAncestors!.Split(' ', StringSplitOptions.RemoveEmptyEntries);
            var ancestorList = string.Join(", ", ancestors.Select(a => $"\"{a}\""));
            trailingParams.Add($"disallowedAncestors: [{ancestorList}]");
        }
        if (element.IsImplicitlyClosed) trailingParams.Add("isImplicitlyClosed: true");
        if (element.HasExternalCompletion) trailingParams.Add("hasExternalCompletion: true");

        sb.AppendLine($"        new HtmlElementInfo(");
        sb.AppendLine($"            {EscapeString(element.Name)},");

        // Attributes parameter — use field reference if available, omit when empty
        var attrExpr = GetElementAttrExpression(element, schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap, sharedElemAttrMap, uniqueElemAttrMap);

        if (attrExpr != null)
        {
            trailingParams.Insert(0, $"attributes: {attrExpr}");
        }

        if (trailingParams.Count == 0)
        {
            // Only name and url — close the constructor
            sb.AppendLine($"            {EscapeString(url)}),");
        }
        else
        {
            sb.AppendLine($"            {EscapeString(url)},");
            for (int i = 0; i < trailingParams.Count; i++)
            {
                var suffix = i == trailingParams.Count - 1 ? ")," : ",";
                sb.AppendLine($"            {trailingParams[i]}{suffix}");
            }
        }
    }

    private static void EmitAttributeInfo(StringBuilder sb, AttributeData attr, string ownerName, HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap, Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap, string indent)
    {
        // Check if this instance is shared (multi-element)
        var instanceKey = GetAttrInstanceKey(attr, schema, sharedValueMap, uniqueValueMap);
        if (attrInstanceMap.TryGetValue(instanceKey, out var sharedFieldName))
        {
            sb.AppendLine($"{indent}HtmlAttributes.Shared.{sharedFieldName},");
            return;
        }

        // Check if this instance is in the unique map
        var compositeKey = $"{ownerName}|{instanceKey}";
        if (uniqueAttrMap.TryGetValue(compositeKey, out var uniqueFieldName))
        {
            sb.AppendLine($"{indent}HtmlAttributes.Unique.{uniqueFieldName},");
            return;
        }

        // Fallback: inline (shouldn't happen if maps are complete)
        var url = GetUrl(attr.DescriptionId, schema);
        var baseline = attr.Baseline;
        var baselineDate = attr.BaselineDate;
        var valuesExpr = GetValuesExpression(attr, sharedValueMap, uniqueValueMap);

        sb.AppendLine($"{indent}new({BuildAttrCtorArgs(attr.Name, url, baseline, baselineDate, valuesExpr, attr.IsBoolean, attr.IsEvent, attr.Icon ?? "", attr.HasExternalCompletion)}),");
    }

    /// <summary>
    /// Builds the constructor argument string, omitting trailing default values.
    /// Order: name, documentationUrl="", baseline="", baselineDate="", values=default, isBoolean=false, kind=HtmlAttributeKind.Default
    /// </summary>
    private static string BuildAttrCtorArgs(string name, string url, string baseline, string baselineDate, string valuesExpr, bool isBoolean, bool isEvent, string icon, bool hasExternalCompletion)
    {
        var kind = isEvent ? "Event"
            : icon == "aria16.png" ? "Aria"
            : icon == "angular16.png" ? "Angular"
            : null;
        var args = new List<string> { EscapeString(name) };

        // After name (always positional), use named parameters for non-default values.
        var hasValues = valuesExpr != "[]";
        var hasUrl = url != "";

        if (hasUrl) args.Add($"documentationUrl: {EscapeString(url)}");
        if (baseline != "") args.Add($"baseline: {EscapeString(baseline)}");
        if (baselineDate != "") args.Add($"baselineDate: {EscapeString(baselineDate)}");
        if (hasValues) args.Add($"values: {valuesExpr}");
        if (isBoolean) args.Add("isBoolean: true");
        if (kind != null) args.Add($"kind: HtmlAttributeKind.{kind}");
        if (hasExternalCompletion) args.Add("hasExternalCompletion: true");

        return string.Join(", ", args);
    }

    private static void EmitLookup(StringBuilder sb, HtmlSchema schema)
    {
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// O(1) element lookup by name (case-insensitive).");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("#if NET8_0_OR_GREATER");
        sb.AppendLine("    private static readonly FrozenDictionary<string, HtmlElementInfo> s_elements =");
        sb.AppendLine("        HtmlElements.All.ToFrozenDictionary(static e => e.Name, StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("#else");
        sb.AppendLine("    private static readonly Dictionary<string, HtmlElementInfo> s_elements =");
        sb.AppendLine("        HtmlElements.All.ToDictionary(static e => e.Name, StringComparer.OrdinalIgnoreCase);");
        sb.AppendLine("#endif");
    }

    private static string GetDescription(int descId, HtmlSchema schema)
    {
        if (descId >= 0 && schema.Descriptions.TryGetValue(descId, out var desc))
        {
            return desc.Text;
        }
        return "";
    }

    private static string GetUrl(int descId, HtmlSchema schema)
    {
        if (descId >= 0 && schema.Descriptions.TryGetValue(descId, out var desc))
        {
            return desc.Url;
        }
        return "";
    }

    private static string EscapeString(string value)
    {
        if (string.IsNullOrEmpty(value))
        {
            return "\"\"";
        }

        // Use verbatim string for descriptions that contain quotes or are long
        if (value.Contains('"') || value.Contains('\n') || value.Length > 120)
        {
            return "@\"" + value.Replace("\"", "\"\"") + "\"";
        }

        return "\"" + value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            + "\"";
    }

    /// <summary>
    /// Emits a .resx file containing all HTML description strings, keyed by element/attribute name.
    /// Keys use the format "HtmlElement_{name}" and "HtmlAttribute_{name}".
    /// This enables localization through the standard .NET resource pipeline.
    /// </summary>
    public static string EmitDescriptionsResx(HtmlSchema schema)
    {
        var sb = new StringBuilder(16 * 1024);
        sb.AppendLine("""
<?xml version="1.0" encoding="utf-8"?>
<root>
  <xsd:schema id="root" xmlns="" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:msdata="urn:schemas-microsoft-com:xml-msdata">
    <xsd:element name="root" msdata:IsDataSet="true">
      <xsd:complexType>
        <xsd:choice maxOccurs="unbounded">
          <xsd:element name="data">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
                <xsd:element name="comment" type="xsd:string" minOccurs="0" msdata:Ordinal="2" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" msdata:Ordinal="1" />
              <xsd:attribute name="type" type="xsd:string" />
              <xsd:attribute name="mimetype" type="xsd:string" />
              <xsd:attribute name="space" use="optional" />
            </xsd:complexType>
          </xsd:element>
          <xsd:element name="resheader">
            <xsd:complexType>
              <xsd:sequence>
                <xsd:element name="value" type="xsd:string" minOccurs="0" msdata:Ordinal="1" />
              </xsd:sequence>
              <xsd:attribute name="name" type="xsd:string" use="required" />
            </xsd:complexType>
          </xsd:element>
        </xsd:choice>
      </xsd:complexType>
    </xsd:element>
  </xsd:schema>
  <resheader name="resmimetype">
    <value>text/microsoft-resx</value>
  </resheader>
  <resheader name="version">
    <value>2.0</value>
  </resheader>
  <resheader name="reader">
    <value>System.Resources.ResXResourceReader, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
  <resheader name="writer">
    <value>System.Resources.ResXResourceWriter, System.Windows.Forms, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</value>
  </resheader>
""");

        // Emit element descriptions keyed by element name
        foreach (var element in schema.Elements.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase))
        {
            var desc = GetDescription(element.DescriptionId, schema);
            if (desc != "")
            {
                var escapedText = System.Security.SecurityElement.Escape(desc);
                sb.AppendLine($"""  <data name="HtmlElement_{element.Name}" xml:space="preserve">""");
                sb.AppendLine($"    <value>{escapedText}</value>");
                sb.AppendLine("  </data>");
            }
        }

        // Emit attribute descriptions keyed by attribute name (deduplicated)
        var emittedAttrNames = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var element in schema.Elements)
        {
            foreach (var attr in element.Attributes)
            {
                var desc = GetDescription(attr.DescriptionId, schema);
                if (desc != "" && emittedAttrNames.Add(attr.Name))
                {
                    var escapedText = System.Security.SecurityElement.Escape(desc);
                    sb.AppendLine($"""  <data name="HtmlAttribute_{attr.Name}" xml:space="preserve">""");
                    sb.AppendLine($"    <value>{escapedText}</value>");
                    sb.AppendLine("  </data>");
                }
            }
        }

        // Also check global attributes
        foreach (var attr in schema.GlobalAttributes)
        {
            var desc = GetDescription(attr.DescriptionId, schema);
            if (desc != "" && emittedAttrNames.Add(attr.Name))
            {
                var escapedText = System.Security.SecurityElement.Escape(desc);
                sb.AppendLine($"""  <data name="HtmlAttribute_{attr.Name}" xml:space="preserve">""");
                sb.AppendLine($"    <value>{escapedText}</value>");
                sb.AppendLine("  </data>");
            }
        }

        sb.AppendLine("</root>");
        return sb.ToString();
    }

    /// <summary>
    /// Emits a static accessor class that resolves HTML descriptions from embedded resources.
    /// </summary>
    public static string EmitDescriptionsAccessor(HtmlSchema schema)
    {
        var sb = new StringBuilder(2 * 1024);

        sb.AppendLine("// <auto-generated/>");
        sb.AppendLine($"// Generated {DateTime.UtcNow:yyyy-MM-dd HH:mm:ss} UTC by HtmlCompletionDataGenerator from html.xsd + html.loc");
        sb.AppendLine("// Source: VS HTML Editor schema files (src/Languages/html/Editor/Schemas/SchemaFiles/)");
        sb.AppendLine("// Do not edit manually. Re-run the generator to update.");
        sb.AppendLine();
        sb.AppendLine("using System.Resources;");
        sb.AppendLine();
        sb.AppendLine("namespace Microsoft.CodeAnalysis.Razor.Completion.Html;");
        sb.AppendLine();
        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Provides localized HTML element and attribute descriptions from embedded resources.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static class HtmlDescriptions");
        sb.AppendLine("{");
        sb.AppendLine("    private static readonly ResourceManager s_resourceManager =");
        sb.AppendLine("        new(\"Microsoft.CodeAnalysis.Razor.Workspaces.Resources.HtmlDescriptions\",");
        sb.AppendLine("            typeof(HtmlDescriptions).Assembly);");
        sb.AppendLine();
        sb.AppendLine("    internal static string GetElementDescription(string elementName)");
        sb.AppendLine("        => (s_resourceManager.GetString($\"HtmlElement_{elementName}\") ?? \"\").Replace(\"\\r\\n\", \"\\n\");");
        sb.AppendLine();
        sb.AppendLine("    internal static string GetAttributeDescription(string attributeName)");
        sb.AppendLine("        => (s_resourceManager.GetString($\"HtmlAttribute_{attributeName}\") ?? \"\").Replace(\"\\r\\n\", \"\\n\");");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Builds maps for element child group extraction.
    /// Shared: child arrays used by more than one element (including named content groups).
    /// Unique: child arrays used by exactly one element.
    /// </summary>
    private static (Dictionary<string, string> sharedMap, Dictionary<string, string> uniqueMap) BuildElementGroupMaps(HtmlSchema schema)
    {
        // First, build a key for each element's children (sorted child list as pipe-delimited string)
        var elementKeys = new Dictionary<string, string>(); // elementName → key
        var keyUsage = new Dictionary<string, List<string>>(); // key → list of element names

        foreach (var element in schema.Elements)
        {
            if (element.AllowedChildren.Count == 0)
                continue;
            if (element.AllowedChildren.Count == 1 && element.AllowedChildren[0] == "*")
                continue; // transparent

            var key = string.Join("|", element.AllowedChildren.OrderBy(c => c, StringComparer.OrdinalIgnoreCase));
            elementKeys[element.Name] = key;

            if (!keyUsage.TryGetValue(key, out var users))
            {
                users = new List<string>();
                keyUsage[key] = users;
            }
            users.Add(element.Name);
        }

        // Named content groups are always shared (they come from XSD group definitions)
        var namedGroupKeys = new Dictionary<string, string>(); // key → groupName
        foreach (var (groupName, groupChildren) in schema.ContentGroups)
        {
            var key = string.Join("|", groupChildren.OrderBy(c => c, StringComparer.OrdinalIgnoreCase));
            namedGroupKeys[key] = groupName;
        }

        // Shared: named groups + any key used by 2+ elements
        var sharedMap = new Dictionary<string, string>(); // key → fieldName
        foreach (var (key, groupName) in namedGroupKeys)
        {
            sharedMap[key] = ToPascalCase(groupName);
        }

        // Check for unnamed shared groups (same child list on 2+ elements, not a named group)
        var sharedIndex = 0;
        foreach (var (key, users) in keyUsage)
        {
            if (users.Count > 1 && !namedGroupKeys.ContainsKey(key))
            {
                sharedMap[key] = $"Shared{sharedIndex++}";
            }
        }

        // Unique: keys used by exactly one element and not matching a named group
        var uniqueMap = new Dictionary<string, string>(); // elementName → fieldName
        foreach (var (elementName, key) in elementKeys)
        {
            if (!sharedMap.ContainsKey(key))
            {
                uniqueMap[elementName] = ToPascalCase(elementName);
            }
        }

        return (sharedMap, uniqueMap);
    }

    /// <summary>
    /// Gets the children field expression for an element.
    /// Returns null if the element is void (no children) or transparent.
    /// </summary>
    private static string? GetChildrenExpression(ElementData element, HtmlSchema schema, Dictionary<string, string> sharedGroupMap, Dictionary<string, string> uniqueGroupMap)
    {
        if (element.AllowedChildren.Count == 1 && element.AllowedChildren[0] == "*")
            return null;

        if (element.AllowedChildren.Count == 0)
            return null;

        var key = string.Join("|", element.AllowedChildren.OrderBy(c => c, StringComparer.OrdinalIgnoreCase));

        if (sharedGroupMap.TryGetValue(key, out var sharedField))
            return $"HtmlElementGroups.Shared.{sharedField}";

        if (uniqueGroupMap.TryGetValue(element.Name, out var uniqueField))
            return $"HtmlElementGroups.Unique.{uniqueField}";

        return null;
    }

    public static string EmitElementGroupsShared(HtmlSchema schema)
    {
        var (sharedMap, _) = BuildElementGroupMaps(schema);
        var sb = new StringBuilder(16 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Groups of child elements shared across multiple parent elements.");
        sb.AppendLine("/// Derived from XSD group definitions (flowContent, phrasingContent, etc.).");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlElementGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Shared");
        sb.AppendLine("    {");

        foreach (var (key, fieldName) in sharedMap.OrderBy(kv => kv.Value, StringComparer.OrdinalIgnoreCase))
        {
            var children = key.Split('|');
            sb.AppendLine($"        internal static readonly ImmutableArray<string> {fieldName} =");
            sb.AppendLine("        [");
            foreach (var child in children)
            {
                sb.AppendLine($"            \"{child}\",");
            }
            sb.AppendLine("        ];");
            sb.AppendLine();
        }

        TrimTrailingBlankLine(sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    public static string EmitElementGroupsUnique(HtmlSchema schema)
    {
        var (sharedMap, uniqueMap) = BuildElementGroupMaps(schema);
        var sb = new StringBuilder(16 * 1024);

        EmitHeader(sb);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Per-element child lists that are unique to a single parent element.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlElementGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Unique");
        sb.AppendLine("    {");

        foreach (var element in schema.Elements.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase))
        {
            if (!uniqueMap.TryGetValue(element.Name, out var fieldName))
                continue;

            var children = element.AllowedChildren.OrderBy(c => c, StringComparer.OrdinalIgnoreCase);
            sb.AppendLine($"        internal static readonly ImmutableArray<string> {fieldName} =");
            sb.AppendLine("        [");
            foreach (var child in children)
            {
                sb.AppendLine($"            \"{child}\",");
            }
            sb.AppendLine("        ];");
            sb.AppendLine();
        }

        TrimTrailingBlankLine(sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Returns a camelCase identifier from a hyphenated or camelCase name.
    /// "flowContent" → "flowContent", "phrasing-content" → "phrasingContent"
    /// </summary>
    private static string CamelCase(string name)
    {
        if (!name.Contains('-'))
            return name;
        return string.Concat(name.Split('-').Select((part, i) =>
            i == 0 ? part : char.ToUpperInvariant(part[0]) + part[1..]));
    }

    private static string ToPascalCase(string name)
    {
        if (string.IsNullOrEmpty(name))
            return name;
        return char.ToUpperInvariant(name[0]) + name[1..];
    }

    private static string BoolLiteral(bool value) => value ? "true" : "false";

    /// <summary>
    /// Builds a map from element name → attribute array field name for elements with attributes.
    /// Detects shared arrays (elements with identical attribute array content) vs unique ones.
    /// Returns (shared map: key→fieldName, unique map: elementName→fieldName, keyMap: elementName→key).
    /// </summary>
    private static (Dictionary<string, string> Shared, Dictionary<string, string> Unique) BuildElementAttrArrayMap(
        HtmlSchema schema, Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap,
        Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap)
    {
        // Build a content key for each element's attribute array
        var elementKeys = new Dictionary<string, string>(StringComparer.Ordinal); // elementName → key
        var keyCounts = new Dictionary<string, int>(StringComparer.Ordinal); // key → count

        foreach (var element in schema.Elements)
        {
            if (element.Attributes.Count == 0)
                continue;

            var key = BuildElementAttrKey(element, schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap);
            elementKeys[element.Name] = key;
            keyCounts.TryGetValue(key, out var count);
            keyCounts[key] = count + 1;
        }

        // Build shared (count > 1) and unique (count == 1) maps
        var shared = new Dictionary<string, string>(StringComparer.Ordinal); // key → fieldName
        var unique = new Dictionary<string, string>(StringComparer.Ordinal); // elementName → fieldName
        var sharedNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var element in schema.Elements.OrderBy(e => e.Name, StringComparer.OrdinalIgnoreCase))
        {
            if (!elementKeys.TryGetValue(element.Name, out var key))
                continue;

            if (keyCounts[key] > 1)
            {
                if (!shared.ContainsKey(key))
                {
                    // Name from first element alphabetically
                    shared[key] = ToPascalCase(CamelCase(element.Name));
                }
            }
            else
            {
                unique[element.Name] = ToPascalCase(CamelCase(element.Name));
            }
        }

        return (shared, unique);
    }

    /// <summary>
    /// Builds a string key representing the ordered attribute references for an element.
    /// </summary>
    private static string BuildElementAttrKey(ElementData element, HtmlSchema schema,
        Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap,
        Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap)
    {
        var parts = new List<string>();
        foreach (var attr in element.Attributes.OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase))
        {
            var instanceKey = GetAttrInstanceKey(attr, schema, sharedValueMap, uniqueValueMap);
            if (attrInstanceMap.TryGetValue(instanceKey, out var sharedFieldName))
            {
                parts.Add($"S:{sharedFieldName}");
            }
            else
            {
                var compositeKey = $"{element.Name}|{instanceKey}";
                if (uniqueAttrMap.TryGetValue(compositeKey, out var uniqueFieldName))
                {
                    parts.Add($"U:{uniqueFieldName}");
                }
                else
                {
                    parts.Add($"I:{instanceKey}");
                }
            }
        }
        return string.Join(";", parts);
    }

    /// <summary>
    /// Emits the shared attribute groups file (element attribute arrays used by multiple elements).
    /// </summary>
    public static string EmitAttributeGroupsShared(HtmlSchema schema)
    {
        var sb = new StringBuilder(32 * 1024);

        EmitHeader(sb);

        var (sharedValueMap, uniqueValueMap) = BuildValueArrayMaps(schema);
        var attrInstanceMap = BuildAttrInstanceMap(schema, sharedValueMap, uniqueValueMap);
        var uniqueAttrMap = BuildUniqueAttrMap(schema, sharedValueMap, uniqueValueMap, attrInstanceMap);
        var (sharedElemAttrs, _) = BuildElementAttrArrayMap(schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Element attribute arrays shared by multiple elements with identical attribute sets.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributeGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Shared");
        sb.AppendLine("    {");

        // Global attributes (valid on all HTML elements)
        sb.AppendLine("        /// <summary>");
        sb.AppendLine("        /// Attributes valid on all HTML elements (core + events + microdata + ARIA).");
        sb.AppendLine("        /// </summary>");
        sb.AppendLine("        internal static readonly ImmutableArray<HtmlAttributeInfo> Global =");
        sb.AppendLine("        [");

        foreach (var attr in schema.GlobalAttributes.OrderBy(a => a.Name, StringComparer.OrdinalIgnoreCase))
        {
            EmitAttributeInfo(sb, attr, "global", schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap, "            ");
        }

        sb.AppendLine("        ];");
        sb.AppendLine();

        foreach (var (key, fieldName) in sharedElemAttrs.OrderBy(kv => kv.Value, StringComparer.Ordinal))
        {
            EmitElementAttrField(sb, key, fieldName, "        ");
        }

        TrimTrailingBlankLine(sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits the unique attribute groups file (element attribute arrays unique to a single element).
    /// </summary>
    public static string EmitAttributeGroupsUnique(HtmlSchema schema)
    {
        var sb = new StringBuilder(64 * 1024);

        EmitHeader(sb);

        var (sharedValueMap, uniqueValueMap) = BuildValueArrayMaps(schema);
        var attrInstanceMap = BuildAttrInstanceMap(schema, sharedValueMap, uniqueValueMap);
        var uniqueAttrMap = BuildUniqueAttrMap(schema, sharedValueMap, uniqueValueMap, attrInstanceMap);
        var (_, uniqueElemAttrs) = BuildElementAttrArrayMap(schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap);

        sb.AppendLine("/// <summary>");
        sb.AppendLine("/// Element attribute arrays unique to a single element.");
        sb.AppendLine("/// </summary>");
        sb.AppendLine("internal static partial class HtmlAttributeGroups");
        sb.AppendLine("{");
        sb.AppendLine("    internal static class Unique");
        sb.AppendLine("    {");

        foreach (var (elementName, fieldName) in uniqueElemAttrs.OrderBy(kv => kv.Value, StringComparer.Ordinal))
        {
            var element = schema.Elements.First(e => e.Name == elementName);
            var key = BuildElementAttrKey(element, schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap);
            EmitElementAttrField(sb, key, fieldName, "        ");
        }

        TrimTrailingBlankLine(sb);
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    /// <summary>
    /// Emits a single element attribute array field from its key.
    /// </summary>
    private static void EmitElementAttrField(StringBuilder sb, string key, string fieldName, string indent)
    {
        var parts = key.Split(';');
        sb.AppendLine($"{indent}internal static readonly ImmutableArray<HtmlAttributeInfo> {fieldName} =");
        sb.AppendLine($"{indent}[");
        foreach (var part in parts)
        {
            var prefix = part[..2];
            var value = part[2..];
            switch (prefix)
            {
                case "S:":
                    sb.AppendLine($"{indent}    HtmlAttributes.Shared.{value},");
                    break;
                case "U:":
                    sb.AppendLine($"{indent}    HtmlAttributes.Unique.{value},");
                    break;
                case "I:":
                    // Inline fallback — reconstruct from instance key
                    var attrParts = value.Split('|');
                    var name = attrParts[0];
                    var url = attrParts[1];
                    var valuesExpr = attrParts[2];
                    var isBoolean = bool.Parse(attrParts[3]);
                    var isEvent = bool.Parse(attrParts[4]);
                    var icon = attrParts.Length > 5 ? attrParts[5] : "";
                    var hasExternalCompletion = attrParts.Length > 6 && bool.Parse(attrParts[6]);
                    var baseline = attrParts.Length > 7 ? attrParts[7] : "";
                    var baselineDate = attrParts.Length > 8 ? attrParts[8] : "";
                    sb.AppendLine($"{indent}    new({BuildAttrCtorArgs(name, url, baseline, baselineDate, valuesExpr, isBoolean, isEvent, icon, hasExternalCompletion)}),");
                    break;
            }
        }
        sb.AppendLine($"{indent}];");
        sb.AppendLine();
    }

    /// <summary>
    /// Gets the element attribute array field reference expression for use in EmitElementInfo.
    /// Returns null if the element has no attributes.
    /// </summary>
    internal static string? GetElementAttrExpression(ElementData element, HtmlSchema schema,
        Dictionary<string, string> sharedValueMap, Dictionary<string, string> uniqueValueMap,
        Dictionary<string, string> attrInstanceMap, Dictionary<string, string> uniqueAttrMap,
        Dictionary<string, string> sharedElemAttrMap, Dictionary<string, string> uniqueElemAttrMap)
    {
        if (element.Attributes.Count == 0)
            return null;

        var key = BuildElementAttrKey(element, schema, sharedValueMap, uniqueValueMap, attrInstanceMap, uniqueAttrMap);
        if (sharedElemAttrMap.TryGetValue(key, out var sharedField))
            return $"HtmlAttributeGroups.Shared.{sharedField}";

        if (uniqueElemAttrMap.TryGetValue(element.Name, out var uniqueField))
            return $"HtmlAttributeGroups.Unique.{uniqueField}";

        return null; // shouldn't happen
    }

    /// <summary>
    /// Removes a trailing blank line from the StringBuilder (the newline before the last newline).
    /// Used to prevent empty lines between the last field and the closing brace.
    /// </summary>
    private static void TrimTrailingBlankLine(StringBuilder sb)
    {
        // StringBuilder ends with "...last line\r\n\r\n" — remove one "\r\n"
        if (sb.Length >= 4
            && sb[sb.Length - 1] == '\n'
            && sb[sb.Length - 2] == '\r'
            && sb[sb.Length - 3] == '\n'
            && sb[sb.Length - 4] == '\r')
        {
            sb.Length -= 2;
        }
        else if (sb.Length >= 2
            && sb[sb.Length - 1] == '\n'
            && sb[sb.Length - 2] == '\n')
        {
            sb.Length -= 1;
        }
    }
}
