// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System;
using System.Collections.Generic;
using System.Composition;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Razor.Language;
using Microsoft.AspNetCore.Razor.PooledObjects;
using Microsoft.CodeAnalysis.LanguageServer;
using Microsoft.CodeAnalysis.Razor.CodeActions;
using Microsoft.CodeAnalysis.Razor.Formatting;
using Microsoft.CodeAnalysis.Razor.Logging;
using Microsoft.CodeAnalysis.Razor.Protocol;
using Microsoft.CodeAnalysis.Razor.Workspaces.Extensions;
using Microsoft.CodeAnalysis.Remote.Razor.Formatting;
using Microsoft.CodeAnalysis.Remote.Razor.ProjectSystem;

namespace Microsoft.CodeAnalysis.Remote.Razor.CodeActions;

[Export(typeof(ICSharpCodeActionResolver)), Shared]
[method: ImportingConstructor]
internal sealed class CSharpCodeActionResolver(
    IRazorFormattingService razorFormattingService,
    RemoteSnapshotManager snapshotManager,
    ILoggerFactory loggerFactory) : ICSharpCodeActionResolver
{
    private readonly IRazorFormattingService _razorFormattingService = razorFormattingService;
    private readonly RemoteSnapshotManager _snapshotManager = snapshotManager;
    private readonly ILogger _logger = loggerFactory.GetOrCreateLogger<CSharpCodeActionResolver>();

    public string Action => LanguageServerConstants.CodeActions.Default;

    public async Task<CodeAction> ResolveAsync(
        RemoteDocumentSnapshot snapshot,
        CodeAction codeAction,
        RazorFormattingOptions formattingOptions,
        CancellationToken cancellationToken)
    {
        if (codeAction.Edit?.DocumentChanges is null)
        {
            // Unable to resolve code action with server, return original code action
            return codeAction;
        }

        // Files this code action creates. Roslyn's generate-type-in-a-new-file copies the triggering
        // document's file banner into the new file. When the trigger is a Razor component's generated
        // C#, that banner is "// <auto-generated/>" -- correct for the generated document, but it must
        // not be written onto the user's authored file, so it is stripped below.
        using var _ = HashSetPool<DocumentUri>.GetPooledObject(out var createdFileUris);
        foreach (var edit in codeAction.Edit.EnumerateEdits())
        {
            if (edit.Value is CreateFile createFile)
            {
                createdFileUris.Add(createFile.DocumentUri);
            }
        }

        foreach (var textDocumentEdit in codeAction.Edit.EnumerateTextDocumentEdits())
        {
            cancellationToken.ThrowIfCancellationRequested();

            // If Roslyn wants to edit a random .cs file, then who are we to interfere -- except that when
            // it creates one, we strip the generated-code banner it copied from the Razor component.
            if (!textDocumentEdit.TextDocument.DocumentUri.IsRazorCSharpDocumentUri(snapshot.TextDocument.Project.Solution))
            {
                if (createdFileUris.Contains(textDocumentEdit.TextDocument.DocumentUri))
                {
                    RemoveGeneratedCodeBanner(textDocumentEdit);
                }

                continue;
            }

            // We know this is a virtual C# file, but we have to jump through a couple of hoops to make sure we get the right info
            var generatedDocumentUri = textDocumentEdit.TextDocument.DocumentUri;
            var solution = snapshot.TextDocument.Project.Solution;

            var razorDocument = await _snapshotManager.TryGetRazorDocumentAsync(solution, generatedDocumentUri, cancellationToken).ConfigureAwait(false);
            if (razorDocument is null)
            {
                _logger.LogWarning($"Could not get razor document for {generatedDocumentUri} processing {codeAction.Title}, so leaving original edit in place.");
                continue;
            }

            var razorSnapshot = _snapshotManager.GetSnapshot(razorDocument);
            var codeDocument = await razorSnapshot.GetGeneratedOutputAsync(cancellationToken).ConfigureAwait(false);

            if (!solution.TryGetSourceGeneratedDocumentIdentity(generatedDocumentUri, out var identity))
            {
                _logger.LogWarning($"Could not get generated document identity for {generatedDocumentUri} processing {codeAction.Title}, so leaving original edit in place.");
                continue;
            }

            var csharpDocument = codeDocument.GetCSharpDocumentForHintName(identity.HintName);
            var csharpSourceText = csharpDocument.Text;
            var csharpTextChanges = textDocumentEdit.Edits.SelectAsArray(e => csharpSourceText.GetTextChange((TextEdit)e));

            // Remaps the text edits from the generated C# to the razor file,
            // as well as applying appropriate formatting.
            var formattedChange = await _razorFormattingService.TryGetCSharpCodeActionEditAsync(
                razorSnapshot,
                csharpTextChanges,
                declarationDocument: csharpDocument.IsDeclarationDocument,
                formattingOptions,
                cancellationToken).ConfigureAwait(false);

            if (formattedChange is { } change)
            {
                textDocumentEdit.TextDocument = new() { DocumentUri = razorDocument.GetURI() };
                textDocumentEdit.Edits = [codeDocument.Source.Text.GetTextEdit(change)];
            }
            else
            {
                _logger.LogWarning($"Formatting dropped all C# code edits for {codeAction.Title} in {razorDocument.GetURI()}");
                textDocumentEdit.Edits = [];
            }
        }

        return codeAction;
    }

    // Removes a leading "// <auto-generated/>" banner that Roslyn copied from a Razor component's
    // generated C# into a file this code action creates. The banner belongs on generated documents,
    // not on a new file the user is authoring.
    private static void RemoveGeneratedCodeBanner(TextDocumentEdit textDocumentEdit)
    {
        foreach (var edit in textDocumentEdit.Edits)
        {
            var textEdit = (TextEdit)edit;
            if (textEdit.NewText is { } newText && TryRemoveLeadingAutoGeneratedComment(newText, out var updated))
            {
                textEdit.NewText = updated;
            }
        }
    }

    private static bool TryRemoveLeadingAutoGeneratedComment(string text, out string updated)
    {
        // Only a banner at the very start of the inserted text -- a comment line containing
        // "<auto-generated" -- is removed, matching what Roslyn recognizes as a file banner.
        var newlineIndex = text.IndexOf('\n');
        // TrimStart() does not treat a leading UTF-8 BOM (U+FEFF) as whitespace, so strip one explicitly
        // before the banner check -- generated C# can carry a BOM that would otherwise hide the "//".
        var firstLine = (newlineIndex < 0 ? text : text[..newlineIndex]).TrimStart('\uFEFF').TrimStart();
        if (firstLine.StartsWith("//", StringComparison.Ordinal) &&
            firstLine.IndexOf("<auto-generated", StringComparison.Ordinal) >= 0)
        {
            updated = newlineIndex < 0 ? string.Empty : text[(newlineIndex + 1)..];
            return true;
        }

        updated = text;
        return false;
    }
}
