<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>$(NetRoslyn)</TargetFramework>
    <AssemblyName>RunTests.UnitTests</AssemblyName>
    <RootNamespace>RunTests.UnitTests</RootNamespace>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Compilers\Test\Core\Microsoft.CodeAnalysis.Test.Utilities.csproj" />
    <ProjectReference Include="..\RunTests.csproj" />
  </ItemGroup>
</Project>
