//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.CodeAnalysis {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CodeStyleResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CodeStyleResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.CodeAnalysis.CodeStyleResources", typeof(CodeStyleResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language name cannot be specified for this option..
        /// </summary>
        internal static string A_language_name_cannot_be_specified_for_this_option {
            get {
                return ResourceManager.GetString("A_language_name_cannot_be_specified_for_this_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A language name must be specified for this option..
        /// </summary>
        internal static string A_language_name_must_be_specified_for_this_option {
            get {
                return ResourceManager.GetString("A_language_name_must_be_specified_for_this_option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code Quality.
        /// </summary>
        internal static string Code_Quality {
            get {
                return ResourceManager.GetString("Code_Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fix formatting.
        /// </summary>
        internal static string Fix_formatting {
            get {
                return ResourceManager.GetString("Fix_formatting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indentation and spacing.
        /// </summary>
        internal static string Indentation_and_spacing {
            get {
                return ResourceManager.GetString("Indentation_and_spacing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line preferences.
        /// </summary>
        internal static string New_line_preferences {
            get {
                return ResourceManager.GetString("New_line_preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private member &apos;{0}&apos; can be removed as the value assigned to it is never read..
        /// </summary>
        internal static string Private_member_0_can_be_removed_as_the_value_assigned_to_it_is_never_read {
            get {
                return ResourceManager.GetString("Private_member_0_can_be_removed_as_the_value_assigned_to_it_is_never_read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private member &apos;{0}&apos; is unused..
        /// </summary>
        internal static string Private_member_0_is_unused {
            get {
                return ResourceManager.GetString("Private_member_0_is_unused", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private method &apos;{0}&apos; can be removed as it is never invoked..
        /// </summary>
        internal static string Private_method_0_can_be_removed_as_it_is_never_invoked {
            get {
                return ResourceManager.GetString("Private_method_0_can_be_removed_as_it_is_never_invoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Private property &apos;{0}&apos; can be converted to a method as its get accessor is never invoked..
        /// </summary>
        internal static string Private_property_0_can_be_converted_to_a_method_as_its_get_accessor_is_never_invoked {
            get {
                return ResourceManager.GetString("Private_property_0_can_be_converted_to_a_method_as_its_get_accessor_is_never_invo" +
                        "ked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refactoring Only.
        /// </summary>
        internal static string Refactoring_Only {
            get {
                return ResourceManager.GetString("Refactoring_Only", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unread private members.
        /// </summary>
        internal static string Remove_unread_private_members {
            get {
                return ResourceManager.GetString("Remove_unread_private_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused member.
        /// </summary>
        internal static string Remove_unused_member {
            get {
                return ResourceManager.GetString("Remove_unused_member", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove unused private members.
        /// </summary>
        internal static string Remove_unused_private_members {
            get {
                return ResourceManager.GetString("Remove_unused_private_members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string Style {
            get {
                return ResourceManager.GetString("Style", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestion.
        /// </summary>
        internal static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
