<?xml version="1.0" encoding="utf-8"?>
<Module Name="rvbc.vbproj" Id="rvbc" Version="0.1" xmlns="http://schemas.microsoft.com/developer/modules/2012">
  <Capability Type="module" Id="rvbc" Version="0.1" />
  <Facet Domain="build">
    <!-- Tell Airstream to copy all the dependencies locally; this enables running with F5. -->
    <Property Key="CopyOutputBehavior" Value="Transitive" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset.Open" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset" />
    <Requirement Type="toolset" Id="RoslynCompilers" />
    <Requirement Type="toolset" Id="RoslynDiagnostics" />
    <Requirement Id="Microsoft.CodeAnalysis">
      <Binding Type="Custom">
        <Artifact Name="Microsoft.CodeAnalysis.dll" />
      </Binding>
    </Requirement>
    <Requirement Id="Microsoft.CodeAnalysis.VisualBasic">
      <Binding Type="Custom">
        <Artifact Name="Microsoft.CodeAnalysis.VisualBasic.dll" />
      </Binding>
    </Requirement>
    <Requirement Id="System.Collections.Immutable" />
    <Project Name="rvbc.vbproj" Guid="2ac2755d-9437-4271-bbde-1a3795a0c320" />
  </Facet>
  <Facet Domain="sdk">
    <Artifact Name="rvbc.exe" />
  </Facet>
  <Facet Domain="runtime">
    <Requirement Id="System.Collections.Immutable" />
    <Requirement Id="Microsoft.CodeAnalysis" />
    <Requirement Id="Microsoft.CodeAnalysis.VisualBasic" />
  </Facet>
  <Facet Domain="packaging">
    <Artifact Name="rvbc.exe" />
    <Artifact Name="rvbc.exe.config" />
    <Artifact Name="rvbc.rsp" />
  </Facet>
  <Facet Domain="debug">
    <Artifact Name="rvbc.pdb" />
  </Facet>
  <Facet Domain="signing">
  </Facet>
</Module>