<?xml version="1.0" encoding="utf-8"?>
<Module Name="rcsc.csproj" Id="rcsc" Version="0.1" xmlns="http://schemas.microsoft.com/developer/modules/2012">
  <Capability Type="module" Id="rcsc" Version="0.1" />
  <Facet Domain="sdk">
    <Artifact Name="rcsc.exe" />
  </Facet>
  <Facet Domain="build">
    <!-- Tell Airstream to copy all the dependencies locally; this enables running with F5. -->
    <Property Key="CopyOutputBehavior" Value="Transitive" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset.Open" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset" />
    <Requirement Type="toolset" Id="RoslynCompilers" />
    <Requirement Type="toolset" Id="RoslynDiagnostics" />
    <Requirement Type="toolset" Id="Roslyn.StyleCop" />
    <Requirement Id="Microsoft.CodeAnalysis">
      <Binding Type="Custom">
        <Artifact Name="Microsoft.CodeAnalysis.dll" />
      </Binding>
    </Requirement>
    <Requirement Id="Microsoft.CodeAnalysis.CSharp">
      <Binding Type="Custom">
        <Artifact Name="Microsoft.CodeAnalysis.CSharp.dll" />
      </Binding>
    </Requirement>
    <Requirement Id="System.Collections.Immutable" />
    <Project Name="rcsc.csproj" Guid="4b45ca0c-03a0-400f-b454-3d4bcb16af38" />
  </Facet>
  <Facet Domain="runtime">
    <Requirement Id="System.Collections.Immutable" />
    <Requirement Id="Microsoft.CodeAnalysis" />
    <Requirement Id="Microsoft.CodeAnalysis.CSharp" />
  </Facet>
  <Facet Domain="packaging">
    <Artifact Name="rcsc.exe" />
    <Artifact Name="rcsc.exe.config" />
    <Artifact Name="rcsc.rsp" />
  </Facet>
  <Facet Domain="debug">
    <Artifact Name="rcsc.pdb" />
  </Facet>
  <Facet Domain="signing">
  </Facet>
</Module>