parameters:
  enableSourceLinkValidation: false
  enableSigningValidation: true
  enableSymbolValidation: false
  enableNugetValidation: true
  publishInstallersAndChecksums: false
  SDLValidationParameters:
    enable: false
    continueOnError: false
    params: ''
    artifactNames: ''

  # These parameters let the user customize the call to sdk-task.ps1 for publishing
  # symbols & general artifacts as well as for signing validation
  symbolPublishingAdditionalParameters: ''
  artifactsPublishingAdditionalParameters: ''
  signingValidationAdditionalParameters: ''

  # Which stages should finish execution before post-build stages start
  validateDependsOn:
  - build
  publishDependsOn: 
  - Validate

  # Channel ID's instantiated in this file.
  # When adding a new channel implementation the call to `check-channel-consistency.ps1` 
  # needs to be updated with the new channel ID
  NetEngLatestChannelId: 2
  NetEngValidationChannelId: 9
  NetCoreDev5ChannelId: 131
  GeneralTestingChannelId: 529
  NETCoreToolingDevChannelId: 548
  NETCoreToolingReleaseChannelId: 549
  NETInternalToolingChannelId: 551
  NETCoreExperimentalChannelId: 562
  NetEngServicesIntChannelId: 678
  NetEngServicesProdChannelId: 679
  Net5Preview1ChannelId: 737
  Net5Preview2ChannelId: 738
  
stages:
- stage: Validate
  dependsOn: ${{ parameters.validateDependsOn }}
  displayName: Validate
  variables:
    - template: common-variables.yml
  jobs:
  - template: setup-maestro-vars.yml

  - job:
    displayName: Post-build Checks
    dependsOn: setupMaestroVars
    variables:
      - name: InitialChannels
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'] ]
      - name: PromoteToMaestroChannelId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.PromoteToMaestroChannelId'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: PowerShell@2
        displayName: Maestro Channels Consistency
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/check-channel-consistency.ps1
          arguments: -PromoteToChannels "$(InitialChannels)[$(PromoteToMaestroChannelId)]"
            -AvailableChannelIds ${{parameters.NetEngLatestChannelId}},${{parameters.NetEngValidationChannelId}},${{parameters.NetCoreDev5ChannelId}},${{parameters.GeneralTestingChannelId}},${{parameters.NETCoreToolingDevChannelId}},${{parameters.NETCoreToolingReleaseChannelId}},${{parameters.NETInternalToolingChannelId}},${{parameters.NETCoreExperimentalChannelId}},${{parameters.NetEngServicesIntChannelId}},${{parameters.NetEngServicesProdChannelId}},${{parameters.Net5Preview1ChannelId}},${{parameters.Net5Preview2ChannelId}}

  - job:
    displayName: NuGet Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableNugetValidation }}, 'true')
    pool:
      vmImage: 'windows-2019'
    variables:
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: PackageArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/nuget-validation.ps1
          arguments: -PackagesPath $(Build.ArtifactStagingDirectory)/PackageArtifacts/ 
            -ToolDestinationPath $(Agent.BuildDirectory)/Extract/ 

  - job:
    displayName: Signing Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableSigningValidation }}, 'true')
    variables:
      - template: common-variables.yml
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Package Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: PackageArtifacts

      # This is necessary whenever we want to publish/restore to an AzDO private feed
      # Since sdk-task.ps1 tries to restore packages we need to do this authentication here
      # otherwise it'll complain about accessing a private feed.
      - task: NuGetAuthenticate@0
        displayName: 'Authenticate to AzDO Feeds'

      - task: PowerShell@2
        displayName: Enable cross-org publishing
        inputs:
          filePath: eng\common\enable-cross-org-publishing.ps1
          arguments: -token $(dn-bot-dnceng-artifact-feeds-rw)

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: eng\common\sdk-task.ps1
          arguments: -task SigningValidation -restore -msbuildEngine dotnet
            /p:PackageBasePath='$(Build.ArtifactStagingDirectory)/PackageArtifacts'
            /p:SignCheckExclusionsFile='$(Build.SourcesDirectory)/eng/SignCheckExclusionsFile.txt'
            ${{ parameters.signingValidationAdditionalParameters }}

      - template: ../steps/publish-logs.yml
        parameters:
          StageLabel: 'Validation'
          JobLabel: 'Signing'

  - job:
    displayName: SourceLink Validation
    dependsOn: setupMaestroVars
    condition: eq( ${{ parameters.enableSourceLinkValidation }}, 'true')
    variables:
      - template: common-variables.yml
      - name: AzDOProjectName
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOProjectName'] ]
      - name: AzDOPipelineId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOPipelineId'] ]
      - name: AzDOBuildId
        value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.AzDOBuildId'] ]
    pool:
      vmImage: 'windows-2019'
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: Download Blob Artifacts
        inputs:
          buildType: specific
          buildVersionToDownload: specific
          project: $(AzDOProjectName)
          pipeline: $(AzDOPipelineId)
          buildId: $(AzDOBuildId)
          artifactName: BlobArtifacts

      - task: PowerShell@2
        displayName: Validate
        inputs:
          filePath: $(Build.SourcesDirectory)/eng/common/post-build/sourcelink-validation.ps1
          arguments: -InputPath $(Build.ArtifactStagingDirectory)/BlobArtifacts/ 
            -ExtractPath $(Agent.BuildDirectory)/Extract/ 
            -GHRepoName $(Build.Repository.Name) 
            -GHCommit $(Build.SourceVersion)
            -SourcelinkCliVersion $(SourceLinkCLIVersion)
        continueOnError: true

  - template: /eng/common/templates/job/execute-sdl.yml
    parameters:
      enable: ${{ parameters.SDLValidationParameters.enable }}
      dependsOn: setupMaestroVars
      additionalParameters: ${{ parameters.SDLValidationParameters.params }}
      continueOnError: ${{ parameters.SDLValidationParameters.continueOnError }}
      artifactNames: ${{ parameters.SDLValidationParameters.artifactNames }}

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'NetCore_Dev5_Publish'
    channelName: '.NET Core 5 Dev'
    akaMSChannelName: 'net5/dev'
    channelId: ${{ parameters.NetCoreDev5ChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net5_Preview1_Publish'
    channelName: '.NET 5 Preview 1'
    akaMSChannelName: 'net5/preview1'
    channelId: ${{ parameters.Net5Preview1ChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net5_Preview2_Publish'
    channelName: '.NET 5 Preview 2'
    akaMSChannelName: 'net5/preview2'
    channelId: ${{ parameters.Net5Preview2ChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-transport/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet5-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Latest_Publish'
    channelName: '.NET Eng - Latest'
    akaMSChannelName: 'eng/daily'
    channelId: ${{ parameters.NetEngLatestChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Validation_Publish'
    channelName: '.NET Eng - Validation'
    akaMSChannelName: 'eng/validation'
    channelId: ${{ parameters.NetEngValidationChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'General_Testing_Publish'
    channelName: 'General Testing'
    akaMSChannelName: 'generaltesting'
    channelId: ${{ parameters.GeneralTestingChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/general-testing-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'NETCore_Tooling_Dev_Publishing'
    channelName: '.NET Core Tooling Dev'
    channelId: ${{ parameters.NETCoreToolingDevChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'NETCore_Tooling_Release_Publishing'
    channelName: '.NET Core Tooling Release'
    channelId: ${{ parameters.NETCoreToolingReleaseChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-tools-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-internal-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'NET_Internal_Tooling_Publishing'
    channelName: '.NET Internal Tooling'
    channelId: ${{ parameters.NETInternalToolingChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-tools-internal/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-tools-internal/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/internal/_packaging/dotnet-tools-internal-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'NETCore_Experimental_Publishing'
    channelName: '.NET Core Experimental'
    channelId: ${{ parameters.NETCoreExperimentalChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-experimental-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Services_Int_Publish'
    channelName: '.NET Eng Services - Int'
    channelId: ${{ parameters.NetEngServicesIntChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'

- template: \eng\common\templates\post-build\channels\generic-public-channel.yml
  parameters:
    artifactsPublishingAdditionalParameters: ${{ parameters.artifactsPublishingAdditionalParameters }}
    dependsOn: ${{ parameters.publishDependsOn }}
    publishInstallersAndChecksums: ${{ parameters.publishInstallersAndChecksums }}
    symbolPublishingAdditionalParameters: ${{ parameters.symbolPublishingAdditionalParameters }}
    stageName: 'Net_Eng_Services_Prod_Publish'
    channelName: '.NET Eng Services - Prod'
    channelId: ${{ parameters.NetEngServicesProdChannelId }}
    transportFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    shippingFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json'
    symbolsFeed: 'https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng-symbols/nuget/v3/index.json'
