parameters:
  ChannelId: 0

jobs:
- job:
  displayName: Promote Build
  dependsOn: setupMaestroVars
  condition: contains(dependencies.setupMaestroVars.outputs['setReleaseVars.InitialChannels'], ${{ parameters.ChannelId }})
  variables:
    - name: BARBuildId
      value: $[ dependencies.setupMaestroVars.outputs['setReleaseVars.BARBuildId'] ]
    - name: ChannelId
      value: ${{ parameters.ChannelId }}
    - group: Publish-Build-Assets
  pool:
    vmImage: 'windows-2019'
  steps:
    - task: PowerShell@2
      displayName: Add Build to Channel
      inputs:
        targetType: inline
        script: |
          $headers = @{
            "Accept" = "application/json"
            "Authorization" = "Bearer $(MaestroAccessToken)"
          }
          Invoke-RestMethod -Method Post -Headers $headers -Uri https://maestro-prod.westus2.cloudapp.azure.com/api/channels/$(ChannelId)/builds/$(BARBuildId)?api-version=2019-01-16
