// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
#nullable restore
#line (1,8)-(9,1) "x:\dir\subdir\Test\TestComponent.razor"

    public class Person
    {
        public required string Name { get; init; }
    }
    
    public static string Value()
        => new Person { Name = "Razor" }.Name;

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
