#pragma checksum "TestFiles\IntegrationTests\CSharp10LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "aef58c825b9a13530b5e86f28d9d5974003a88b58df819f40985b5543ebcdbe0"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharp10LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"aef58c825b9a13530b5e86f28d9d5974003a88b58df819f40985b5543ebcdbe0", @"/TestFiles/IntegrationTests/CSharp10LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharp10LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line (3,3)-(6,1) "TestFiles\IntegrationTests\CSharp10LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    var value = new { A = new { B = 1 } };
    _ = value is { A.B: 1 };

#line default
#line hidden
#nullable disable

            WriteLiteral("\r\n");
#nullable restore
#line (8,2)-(10,1) "TestFiles\IntegrationTests\CSharp10LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
if (value is { A.B: 1 })
{

#line default
#line hidden
#nullable disable

            WriteLiteral("    <p>Matched</p>\r\n");
#nullable restore
#line (11,1)-(11,2) "TestFiles\IntegrationTests\CSharp10LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
}

#line default
#line hidden
#nullable disable

        }
    }
}
#pragma warning restore 1591
