#pragma checksum "TestFiles\IntegrationTests\CSharpPreviewLanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "f9659ed17b4bec6475d3dd8f00044124dc8473b7b660970e57af41eeb82be415"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharpPreviewLanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"f9659ed17b4bec6475d3dd8f00044124dc8473b7b660970e57af41eeb82be415", @"/TestFiles/IntegrationTests/CSharpPreviewLanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharpPreviewLanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
#nullable restore
#line (3,3)-(5,1) "TestFiles\IntegrationTests\CSharpPreviewLanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    System.Collections.Generic.List<string> values = [with(capacity: 32), "a", "b", "c"];

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
