<Module Name="rcsc2.vcxproj" Id="rcsc2" Version="0.1" xmlns="http://schemas.microsoft.com/developer/modules/2012">
  <Capability Type="module" Id="rcsc2" Version="0.1" />
  <Facet Domain="build">
    <Property Key="SupportedPlatforms" Value="AnyCPU" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset.Open" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset" />
    <Project Name="rcsc2.vcxproj" Guid="63d0f073-f0b3-42cd-829f-e48b977b48ba" />
  </Facet>
  <Facet Domain="sdk">
    <Artifact Name="logging.cpp" />
    <Artifact Name="rcsc2.cpp" />
    <Artifact Name="stdafx.cpp" />
    <Artifact Name="logging.h" />
    <Artifact Name="protocol.h" />
    <Artifact Name="stdafx.h" />
    <Artifact Name="targetver.h" />
    <Artifact Name="rcsc2.exe" />
  </Facet>
  <Facet Domain="packaging">
    <Artifact Name="rcsc2.exe" />
  </Facet>
  <Facet Domain="debug">
    <Artifact Name="rcsc2.pdb" />
  </Facet>
  <Facet Domain="signing">
    <Artifact Name="rcsc2.exe" Strongname="none" />
  </Facet>
</Module>