//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.VisualStudio.LanguageServices.CSharp {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CSharpVSResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CSharpVSResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.VisualStudio.LanguageServices.CSharp.CSharpVSResources", typeof(CSharpVSResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before and after binary operators.
        /// </summary>
        internal static string BinaryOperatorSpace {
            get {
                return ResourceManager.GetString("BinaryOperatorSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore spaces around binary operators.
        /// </summary>
        internal static string BinaryOperatorSpaceIgnore {
            get {
                return ResourceManager.GetString("BinaryOperatorSpaceIgnore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove spaces before and after binary operators.
        /// </summary>
        internal static string BinaryOperatorSpaceRemove {
            get {
                return ResourceManager.GetString("BinaryOperatorSpaceRemove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C#.
        /// </summary>
        internal static string C {
            get {
                return ResourceManager.GetString("C", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place &quot;catch&quot; on new line.
        /// </summary>
        internal static string CatchOnNewLine {
            get {
                return ResourceManager.GetString("CatchOnNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place &quot;else&quot; on new line.
        /// </summary>
        internal static string ElseOnNewLine {
            get {
                return ResourceManager.GetString("ElseOnNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place &quot;finally&quot; on new line.
        /// </summary>
        internal static string FinallyOnNewLine {
            get {
                return ResourceManager.GetString("FinallyOnNewLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format _block on }.
        /// </summary>
        internal static string FormatOnCloseBraceCheckBox {
            get {
                return ResourceManager.GetString("FormatOnCloseBraceCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format on _paste.
        /// </summary>
        internal static string FormatOnPasteCheckBox {
            get {
                return ResourceManager.GetString("FormatOnPasteCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically format _statement on ;.
        /// </summary>
        internal static string FormatOnSemicolonCheckBox {
            get {
                return ResourceManager.GetString("FormatOnSemicolonCheckBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place goto labels in leftmost column.
        /// </summary>
        internal static string GotoLeftmost {
            get {
                return ResourceManager.GetString("GotoLeftmost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent labels normally.
        /// </summary>
        internal static string GotoNoIndent {
            get {
                return ResourceManager.GetString("GotoNoIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place goto labels one indent less than current.
        /// </summary>
        internal static string GotoOneLess {
            get {
                return ResourceManager.GetString("GotoOneLess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent block contents.
        /// </summary>
        internal static string IndentBlock {
            get {
                return ResourceManager.GetString("IndentBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent open and close braces.
        /// </summary>
        internal static string IndentBraces {
            get {
                return ResourceManager.GetString("IndentBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent case contents.
        /// </summary>
        internal static string IndentSwitchCaseContents {
            get {
                return ResourceManager.GetString("IndentSwitchCaseContents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent case labels.
        /// </summary>
        internal static string IndentSwitchCaseLabels {
            get {
                return ResourceManager.GetString("IndentSwitchCaseLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Snippet.
        /// </summary>
        internal static string InsertSnippet {
            get {
                return ResourceManager.GetString("InsertSnippet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label Indentation.
        /// </summary>
        internal static string LabelIndentation {
            get {
                return ResourceManager.GetString("LabelIndentation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line options for braces.
        /// </summary>
        internal static string NewLineBraces {
            get {
                return ResourceManager.GetString("NewLineBraces", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line options for expressions.
        /// </summary>
        internal static string NewLineExpressions {
            get {
                return ResourceManager.GetString("NewLineExpressions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place query expression clauses on new line.
        /// </summary>
        internal static string NewLineForClausesInQuery {
            get {
                return ResourceManager.GetString("NewLineForClausesInQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place members in anonymous types on new line.
        /// </summary>
        internal static string NewLineForMembersInAnonymousTypes {
            get {
                return ResourceManager.GetString("NewLineForMembersInAnonymousTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place members in object initializers on new line.
        /// </summary>
        internal static string NewLineForMembersInObjectInit {
            get {
                return ResourceManager.GetString("NewLineForMembersInObjectInit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New line options for keywords.
        /// </summary>
        internal static string NewLineKeywords {
            get {
                return ResourceManager.GetString("NewLineKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for types.
        /// </summary>
        internal static string NewLinesBracesType {
            get {
                return ResourceManager.GetString("NewLinesBracesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for property, indexer, and event accessors.
        /// </summary>
        internal static string NewLinesForBracesAccessors {
            get {
                return ResourceManager.GetString("NewLinesForBracesAccessors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for anonymous methods.
        /// </summary>
        internal static string NewLinesForBracesInAnonymousMethods {
            get {
                return ResourceManager.GetString("NewLinesForBracesInAnonymousMethods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for anonymous types.
        /// </summary>
        internal static string NewLinesForBracesInAnonymousTypes {
            get {
                return ResourceManager.GetString("NewLinesForBracesInAnonymousTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for control blocks.
        /// </summary>
        internal static string NewLinesForBracesInControlBlocks {
            get {
                return ResourceManager.GetString("NewLinesForBracesInControlBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for lambda expression.
        /// </summary>
        internal static string NewLinesForBracesInLambdaExpressionBody {
            get {
                return ResourceManager.GetString("NewLinesForBracesInLambdaExpressionBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for object, collection and array initializers.
        /// </summary>
        internal static string NewLinesForBracesInObjectCollectionArrayInitializers {
            get {
                return ResourceManager.GetString("NewLinesForBracesInObjectCollectionArrayInitializers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for methods.
        /// </summary>
        internal static string NewLinesForBracesMethod {
            get {
                return ResourceManager.GetString("NewLinesForBracesMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place open brace on new line for properties, indexers, and events.
        /// </summary>
        internal static string NewLinesForBracesProperty {
            get {
                return ResourceManager.GetString("NewLinesForBracesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Move local declaration to the extracted method if it is not used elsewhere.
        /// </summary>
        internal static string Option_AllowMovingDeclaration {
            get {
                return ResourceManager.GetString("Option_AllowMovingDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show completion list after a character is typed.
        /// </summary>
        internal static string Option_BringUpOnIdentifier {
            get {
                return ResourceManager.GetString("Option_BringUpOnIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable full solution _analysis.
        /// </summary>
        internal static string Option_ClosedFileDiagnostics {
            get {
                return ResourceManager.GetString("Option_ClosedFileDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completion Lists.
        /// </summary>
        internal static string Option_CompletionLists {
            get {
                return ResourceManager.GetString("Option_CompletionLists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Show procedure line separators.
        /// </summary>
        internal static string Option_DisplayLineSeparators {
            get {
                return ResourceManager.GetString("Option_DisplayLineSeparators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Don&apos;t put ref or out on custom struct.
        /// </summary>
        internal static string Option_DontPutOutOrRefOnStruct {
            get {
                return ResourceManager.GetString("Option_DontPutOutOrRefOnStruct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor Help.
        /// </summary>
        internal static string Option_EditorHelp {
            get {
                return ResourceManager.GetString("Option_EditorHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight related _keywords under cursor.
        /// </summary>
        internal static string Option_EnableHighlightKeywords {
            get {
                return ResourceManager.GetString("Option_EnableHighlightKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Highlight references to symbol under cursor.
        /// </summary>
        internal static string Option_EnableHighlightReferences {
            get {
                return ResourceManager.GetString("Option_EnableHighlightReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter _outlining mode when files open.
        /// </summary>
        internal static string Option_EnterOutliningMode {
            get {
                return ResourceManager.GetString("Option_EnterOutliningMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extract Method.
        /// </summary>
        internal static string Option_ExtractMethod {
            get {
                return ResourceManager.GetString("Option_ExtractMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Generate XML documentation comments for ///.
        /// </summary>
        internal static string Option_GenerateXmlDocCommentsForTripleSlash {
            get {
                return ResourceManager.GetString("Option_GenerateXmlDocCommentsForTripleSlash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlighting.
        /// </summary>
        internal static string Option_Highlighting {
            get {
                return ResourceManager.GetString("Option_Highlighting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Add new line on enter after end of fully typed word.
        /// </summary>
        internal static string Option_InsertNewlineOnEnterWithWholeWord {
            get {
                return ResourceManager.GetString("Option_InsertNewlineOnEnterWithWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optimize for solution size.
        /// </summary>
        internal static string Option_OptimizeForSolutionSize {
            get {
                return ResourceManager.GetString("Option_OptimizeForSolutionSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large.
        /// </summary>
        internal static string Option_OptimizeForSolutionSize_Large {
            get {
                return ResourceManager.GetString("Option_OptimizeForSolutionSize_Large", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regular.
        /// </summary>
        internal static string Option_OptimizeForSolutionSize_Regular {
            get {
                return ResourceManager.GetString("Option_OptimizeForSolutionSize_Regular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small.
        /// </summary>
        internal static string Option_OptimizeForSolutionSize_Small {
            get {
                return ResourceManager.GetString("Option_OptimizeForSolutionSize_Small", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organize Usings.
        /// </summary>
        internal static string Option_OrganizeUsings {
            get {
                return ResourceManager.GetString("Option_OrganizeUsings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outlining.
        /// </summary>
        internal static string Option_Outlining {
            get {
                return ResourceManager.GetString("Option_Outlining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performance.
        /// </summary>
        internal static string Option_Performance {
            get {
                return ResourceManager.GetString("Option_Performance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Place &apos;System&apos; directives first when sorting usings.
        /// </summary>
        internal static string Option_PlaceSystemNamespaceFirst {
            get {
                return ResourceManager.GetString("Option_PlaceSystemNamespaceFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show preview for _rename tracking.
        /// </summary>
        internal static string Option_RenameTrackingPreview {
            get {
                return ResourceManager.GetString("Option_RenameTrackingPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection In Completion List.
        /// </summary>
        internal static string Option_SelectionInCompletionList {
            get {
                return ResourceManager.GetString("Option_SelectionInCompletionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place _keywords in completion lists.
        /// </summary>
        internal static string Option_ShowKeywords {
            get {
                return ResourceManager.GetString("Option_ShowKeywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place _code snippets in completion lists.
        /// </summary>
        internal static string Option_ShowSnippets {
            get {
                return ResourceManager.GetString("Option_ShowSnippets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warn if _build errors exist when organizing usings.
        /// </summary>
        internal static string Option_WarnOnBuildErrors {
            get {
                return ResourceManager.GetString("Option_WarnOnBuildErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer intrinsic predefined type keyword when declaring locals, parameters and members.
        /// </summary>
        internal static string PreferIntrinsicPredefinedTypeKeywordInDeclaration {
            get {
                return ResourceManager.GetString("PreferIntrinsicPredefinedTypeKeywordInDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefer intrinsic predefined type keyword in member access expressions.
        /// </summary>
        internal static string PreferIntrinsicPredefinedTypeKeywordInMemberAccess {
            get {
                return ResourceManager.GetString("PreferIntrinsicPredefinedTypeKeywordInMemberAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualify member access with &apos;this&apos;.
        /// </summary>
        internal static string QualifyMemberAccessWithThis {
            get {
                return ResourceManager.GetString("QualifyMemberAccessWithThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set other spacing options.
        /// </summary>
        internal static string SetOtherSpacingOptions {
            get {
                return ResourceManager.GetString("SetOtherSpacingOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spacing for brackets.
        /// </summary>
        internal static string SetSpacingForBrackets {
            get {
                return ResourceManager.GetString("SetSpacingForBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spacing for delimiters.
        /// </summary>
        internal static string SetSpacingForDelimiters {
            get {
                return ResourceManager.GetString("SetSpacingForDelimiters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spacing for method calls.
        /// </summary>
        internal static string SetSpacingForMethodCalls {
            get {
                return ResourceManager.GetString("SetSpacingForMethodCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spacing for method declarations.
        /// </summary>
        internal static string SetSpacingForMethodDeclarations {
            get {
                return ResourceManager.GetString("SetSpacingForMethodDeclarations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set spacing for operators.
        /// </summary>
        internal static string SetSpacingForOperators {
            get {
                return ResourceManager.GetString("SetSpacingForOperators", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after cast.
        /// </summary>
        internal static string SpaceAfterCast {
            get {
                return ResourceManager.GetString("SpaceAfterCast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after colon for base or interface in type declaration.
        /// </summary>
        internal static string SpaceAfterColonInBaseTypeDeclaration {
            get {
                return ResourceManager.GetString("SpaceAfterColonInBaseTypeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after comma.
        /// </summary>
        internal static string SpaceAfterComma {
            get {
                return ResourceManager.GetString("SpaceAfterComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after keywords in control flow statements.
        /// </summary>
        internal static string SpaceAfterControlFlowStatementKeyword {
            get {
                return ResourceManager.GetString("SpaceAfterControlFlowStatementKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after dot.
        /// </summary>
        internal static string SpaceAfterDot {
            get {
                return ResourceManager.GetString("SpaceAfterDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space between method name and its opening parenthesis.
        /// </summary>
        internal static string SpaceAfterMethodCallName {
            get {
                return ResourceManager.GetString("SpaceAfterMethodCallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space after semicolon in &quot;for&quot; statement.
        /// </summary>
        internal static string SpaceAfterSemicolonsInForStatement {
            get {
                return ResourceManager.GetString("SpaceAfterSemicolonsInForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before colon for base or interface in type declaration.
        /// </summary>
        internal static string SpaceBeforeColonInBaseTypeDeclaration {
            get {
                return ResourceManager.GetString("SpaceBeforeColonInBaseTypeDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before comma.
        /// </summary>
        internal static string SpaceBeforeComma {
            get {
                return ResourceManager.GetString("SpaceBeforeComma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before dot.
        /// </summary>
        internal static string SpaceBeforeDot {
            get {
                return ResourceManager.GetString("SpaceBeforeDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before open square bracket.
        /// </summary>
        internal static string SpaceBeforeOpenSquareBracket {
            get {
                return ResourceManager.GetString("SpaceBeforeOpenSquareBracket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space before semicolon in &quot;for&quot; statement.
        /// </summary>
        internal static string SpaceBeforeSemicolonsInForStatement {
            get {
                return ResourceManager.GetString("SpaceBeforeSemicolonsInForStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within empty argument list parentheses.
        /// </summary>
        internal static string SpaceBetweenEmptyMethodCallParentheses {
            get {
                return ResourceManager.GetString("SpaceBetweenEmptyMethodCallParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within empty argument list parentheses.
        /// </summary>
        internal static string SpaceBetweenEmptyMethodDeclarationParentheses {
            get {
                return ResourceManager.GetString("SpaceBetweenEmptyMethodDeclarationParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within empty square brackets.
        /// </summary>
        internal static string SpaceBetweenEmptySquareBrackets {
            get {
                return ResourceManager.GetString("SpaceBetweenEmptySquareBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ignore spaces in declaration statements.
        /// </summary>
        internal static string SpacesIgnoreAroundVariableDeclaration {
            get {
                return ResourceManager.GetString("SpacesIgnoreAroundVariableDeclaration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within parentheses of type casts.
        /// </summary>
        internal static string SpaceWithinCastParentheses {
            get {
                return ResourceManager.GetString("SpaceWithinCastParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within parentheses of expressions.
        /// </summary>
        internal static string SpaceWithinExpressionParentheses {
            get {
                return ResourceManager.GetString("SpaceWithinExpressionParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within argument list parentheses.
        /// </summary>
        internal static string SpaceWithinMethodCallParentheses {
            get {
                return ResourceManager.GetString("SpaceWithinMethodCallParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space within argument list parentheses.
        /// </summary>
        internal static string SpaceWithinMethodDeclarationParenthesis {
            get {
                return ResourceManager.GetString("SpaceWithinMethodDeclarationParenthesis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces within parentheses of control flow statements.
        /// </summary>
        internal static string SpaceWithinOtherParentheses {
            get {
                return ResourceManager.GetString("SpaceWithinOtherParentheses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert spaces within square brackets.
        /// </summary>
        internal static string SpaceWithinSquareBrackets {
            get {
                return ResourceManager.GetString("SpaceWithinSquareBrackets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert space between method name and its opening parenthesis.
        /// </summary>
        internal static string SpacingAfterMethodDeclarationName {
            get {
                return ResourceManager.GetString("SpacingAfterMethodDeclarationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Surround With.
        /// </summary>
        internal static string SurroundWith {
            get {
                return ResourceManager.GetString("SurroundWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use &apos;var&apos; when generating locals.
        /// </summary>
        internal static string UseVarWhenGeneratingLocals {
            get {
                return ResourceManager.GetString("UseVarWhenGeneratingLocals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave statements and member declarations on the same line.
        /// </summary>
        internal static string WrappingKeepStatementsOnSingleLine {
            get {
                return ResourceManager.GetString("WrappingKeepStatementsOnSingleLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave block on single line.
        /// </summary>
        internal static string WrappingPreserveSingleLine {
            get {
                return ResourceManager.GetString("WrappingPreserveSingleLine", resourceCulture);
            }
        }
    }
}
