#pragma checksum "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "5c32257deeea20162c64d4849c1cf31ad1272b7ec7cf204f0a3a7a6845c75d02"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharp12LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"5c32257deeea20162c64d4849c1cf31ad1272b7ec7cf204f0a3a7a6845c75d02", @"/TestFiles/IntegrationTests/CSharp12LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        #pragma warning disable 1998
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
        #pragma warning restore 1998
#nullable restore
#line (3,13)-(8,1) "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    [System.Diagnostics.CodeAnalysis.Experimental("RAZOR0001")]
    public class ExperimentalType
    {
    }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
