#pragma checksum "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "1eef6b15390367e0c5a56d0621a1ad70db739a30748567a21a27ec1a2daa1b89"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharp12LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line default
#nullable restore
#line (3,2)-(3,42) "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
using NumberPair = (int Left, int Right)

#nullable disable
    ;
    #line default
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"1eef6b15390367e0c5a56d0621a1ad70db739a30748567a21a27ec1a2daa1b89", @"/TestFiles/IntegrationTests/CSharp12LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
            WriteLiteral("\r\n");
#nullable restore
#line (5,3)-(8,1) "TestFiles\IntegrationTests\CSharp12LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    NumberPair pair = (1, 2);
    _ = pair.Left + pair.Right;

#line default
#line hidden
#nullable disable

        }
    }
}
#pragma warning restore 1591
