<Project>

  <!-- Include and reference README in nuget package, if a README is in the project directory. -->
  <PropertyGroup>
    <PackageReadmeFile Condition="Exists('README.md')">README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Condition="Exists('README.md')" Include="README.md" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CSDevKit.Tests" Key="$(VsPublicKey)" />
  </ItemGroup>

  <Import Project="$([MSBuild]::GetPathOfFileAbove($(MSBuildThisFile), $(MSBuildThisFileDirectory)..))" />

  <PropertyGroup>
    <TargetFramework>$(NetVSCode)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
</Project>