#pragma checksum "TestFiles\IntegrationTests\CSharp11LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml" "{8829d00f-11b8-4213-878b-770e8597ac16}" "8960f9394beef0d28defbd2f278ebc8e8bd209489dab58c926559084087cea5f"
// <auto-generated/>
#pragma warning disable 1591
[assembly: global::Microsoft.AspNetCore.Razor.Hosting.RazorCompiledItemAttribute(typeof(Razor.Template), @"default", @"/TestFiles/IntegrationTests/CSharp11LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
namespace Razor
{
    #line hidden
    [global::Microsoft.AspNetCore.Razor.Hosting.RazorSourceChecksumAttribute(@"Sha256", @"8960f9394beef0d28defbd2f278ebc8e8bd209489dab58c926559084087cea5f", @"/TestFiles/IntegrationTests/CSharp11LanguageFeaturesIntegrationTest_Legacy/TestView.cshtml")]
    public class Template : 
#nullable restore
#line (1,11)-(1,37) "TestFiles\IntegrationTests\CSharp11LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"
global::LegacyTemplateBase

#line default
#line hidden
#nullable disable

    {
        public async override global::System.Threading.Tasks.Task ExecuteAsync()
        {
            WriteLiteral("\r\n");
        }
#nullable restore
#line (3,13)-(15,1) "TestFiles\IntegrationTests\CSharp11LanguageFeaturesIntegrationTest_Legacy\TestView.cshtml"

    public ref struct ValueRef
    {
        private ref int _value;
    
        public ValueRef(ref int value)
        {
            _value = ref value;
        }
    
        public ref int Value => ref _value;
    }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
