<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <IsProductComponent>false</IsProductComponent>
    <RootNamespace></RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Roslyn.SDK.UnitTests" />
  </ItemGroup>

  <!-- Package References -->
  <ItemGroup>
    <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" PrivateAssets="all" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp" />
    <PackageReference Include="Microsoft.CodeAnalysis.VisualBasic" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Resources.resx" GenerateSource="true" ClassName="Roslyn.SyntaxVisualizer.DgmlHelper.My.Resources.Resources" ManifestResourceName="Roslyn.SyntaxVisualizer.DgmlHelper.My.Resources.Resources" />
  </ItemGroup>
</Project>