<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>$(TestTargetFrameworks)</TargetFrameworks>
    <RootNamespace>Microsoft.CodeAnalysis.Testing</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\Workspaces\CSharp\Portable\Microsoft.CodeAnalysis.CSharp.Workspaces.csproj" />
    <ProjectReference Include="..\..\..\..\Workspaces\VisualBasic\Portable\Microsoft.CodeAnalysis.VisualBasic.Workspaces.vbproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.assert" />
    <PackageReference Include="xunit.extensibility.core" />
  </ItemGroup>

  <ItemGroup>
    <Compile Include="..\..\..\..\Compilers\Test\Core\Assert\UseCultureAttribute.cs" Link="UseCultureAttribute.cs" />
  </ItemGroup>
</Project>
