# Build on Unix
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: queueName
  type: string
  default: ''
- name: vmImageName
  type: string
  default: ''
- name: restoreArguments
  type: string
  default: ''
- name: buildArguments
  type: string
  default: ''
  

jobs:
- job: ${{ parameters.jobName }}
  pool:
    ${{ if ne(parameters.queueName, '') }}:
      name: NetCore-Public
      demands: ImageOverride -equals ${{ parameters.queueName }}

    ${{ if ne(parameters.vmImageName, '') }}:
      vmImage: ${{ parameters.vmImageName }}
  timeoutInMinutes: 40
  variables:
    artifactName: ${{ parameters.testArtifactName }}

  steps:
    - template: checkout-unix-task.yml

    - script: ./eng/build.sh --ci --restore --prepareMachine --binaryLog --configuration ${{ parameters.configuration }} ${{ parameters.restoreArguments }}
      displayName: Restore

    - script: ./eng/build.sh --ci --build --prepareMachine --binaryLog --skipDocumentation --configuration ${{ parameters.configuration }} ${{ parameters.buildArguments }}
      displayName: Build

    - script: ./eng/prepare-tests.sh --configuration ${{ parameters.configuration }}
      displayName: Prepare Test Payload
      condition: and(ne(variables['artifactName'], ''), succeeded())
      
    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)/artifacts/testPayload'
        artifactName: ${{ parameters.testArtifactName }}
      condition: and(ne(variables['artifactName'], ''), succeeded())
      
    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
