# Build on windows desktop
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    name: NetCorePublic-Pool
    queue: BuildPool.Windows.10.Amd64.Open
  timeoutInMinutes: 40

  steps:
    - checkout: none

    - powershell: |
        git version
        git init "F:\workspace\_work\1\s"
        git remote add origin https://github.com/dotnet/roslyn
        git config gc.auto 0
        git config --get-all http.https://github.com/dotnet/roslyn.extraheader
        git config --get-all http.proxy
        git config http.version HTTP/1.1
        git -c http.extraheader="AUTHORIZATION: basic $(System.AccessToken)" fetch --force --no-tags --progress --no-recurse-submodules --depth=1 origin "$(Build.SourceVersion)"
        git checkout "$(Build.SourceVersion)"
      displayName: Checkout Sources

    - task: PowerShell@2
      displayName: Restore
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -restore -binaryLog

    - task: PowerShell@2 
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -build -publish -binaryLog 

    - task: PowerShell@2 
      displayName: Prepare Unit Tests
      inputs:
        filePath: eng/prepare-tests.ps1
        arguments: -configuration ${{ parameters.configuration }}

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)\artifacts\testPayload'
        artifactName: ${{ parameters.testArtifactName }}

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}

