# Build on windows desktop
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'

jobs:
- job: ${{ parameters.jobName }}
  pool:
    vmImage: 'windows-2019'
  timeoutInMinutes: 40

  steps:
    - template: checkout-windows-task.yml

    - powershell: |
        Write-Host "##vso[task.setvariable variable=DotNetSDKVersion]$((Get-Content global.json | ConvertFrom-Json).sdk.version)"
      displayName: Read SDK version from global.json

    - task: UseDotNet@2
      displayName: 'Use .NET Core SDK'
      inputs:
        version: $(DotNetSDKVersion)

    - task: PowerShell@2
      displayName: Restore
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -restore -binaryLog

    - task: PowerShell@2 
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -build -publish -binaryLog -skipDocumentation "/p:Features=run-nullable-analysis=never"

    - task: PowerShell@2 
      displayName: Prepare Unit Tests
      inputs:
        filePath: eng/prepare-tests.ps1
        arguments: -configuration ${{ parameters.configuration }}

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)\artifacts\testPayload'
        artifactName: ${{ parameters.testArtifactName }}

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}

