# Build on Unix
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: cacheArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: poolParameters
  type: object

jobs:
- job: ${{ parameters.jobName }}
  pool: ${{ parameters.poolParameters }}
  timeoutInMinutes: 40
  variables:
    - template: variables-build.yml
      parameters:
        configuration: ${{ parameters.configuration }}
    - name: ROSLYN_CACHE_PATH
      value: $(Agent.TempDirectory)/roslyn-cache

  steps:
    - template: checkout-unix-task.yml

    - script: ./eng/build.sh --ci --restore --prepareMachine --binaryLog --configuration ${{ parameters.configuration }}
      displayName: Restore

    - template: cache-roslyn-outputs.yml
      parameters:
        configuration: ${{ parameters.configuration }}

    - template: build-file-based-apps.yml

    - script: ./eng/build.sh --ci --build --prepareMachine --binaryLog --skipDocumentation --configuration ${{ parameters.configuration }}
      displayName: Build

    - script: |
        if [ -d "$(ROSLYN_CACHE_PATH)" ]; then
          echo "##vso[task.setvariable variable=ROSLYN_CACHE_EXISTS]true"
        fi
      displayName: Check Compiler Cache Exists
      condition: and(ne('${{ parameters.cacheArtifactName }}', ''), succeeded())

    - task: PublishPipelineArtifact@1
      displayName: Publish Compiler Cache
      inputs:
        targetPath: '$(ROSLYN_CACHE_PATH)'
        artifactName: ${{ parameters.cacheArtifactName }}
      condition: and(ne('${{ parameters.cacheArtifactName }}', ''), succeeded(), eq(variables['ROSLYN_CACHE_EXISTS'], 'true'))

    - script: ./eng/prepare-tests.sh
      displayName: Prepare Test Payload

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)/artifacts/testPayload'
        artifactName: ${{ parameters.testArtifactName }}

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
