# Build on windows desktop
parameters:
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: cacheArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: poolParameters
  type: object
- name: restoreArguments
  type: string
  default: ''
- name: buildArguments
  type: string
  default: ''

jobs:
- job: ${{ parameters.jobName }}
  pool: ${{ parameters.poolParameters }}
  timeoutInMinutes: 40
  variables:
    - template: variables-build.yml
      parameters:
        configuration: ${{ parameters.configuration }}
    - name: artifactName
      value: ${{ parameters.testArtifactName }}
    - name: ROSLYN_CACHE_PATH
      value: $(Agent.TempDirectory)/roslyn-cache

  steps:
    - template: checkout-windows-task.yml

    - task: PowerShell@2
      displayName: Restore
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -restore -binaryLogName Restore.binlog ${{ parameters.restoreArguments }}

    - template: cache-roslyn-outputs.yml
      parameters:
        configuration: ${{ parameters.configuration }}

    - template: build-file-based-apps.yml

    - task: PowerShell@2
      displayName: Build
      inputs:
        filePath: eng/build.ps1
        arguments: -configuration ${{ parameters.configuration }} -prepareMachine -ci -build -binaryLogName Build.binlog -skipDocumentation ${{ parameters.buildArguments }}

    - powershell: |
        if (Test-Path "$(ROSLYN_CACHE_PATH)") {
          Write-Host "##vso[task.setvariable variable=ROSLYN_CACHE_EXISTS]true"
        }
      displayName: Check Compiler Cache Exists
      condition: and(ne('${{ parameters.cacheArtifactName }}', ''), succeeded())

    - task: PublishPipelineArtifact@1
      displayName: Publish Compiler Cache
      inputs:
        targetPath: '$(ROSLYN_CACHE_PATH)'
        artifactName: ${{ parameters.cacheArtifactName }}
      condition: and(ne('${{ parameters.cacheArtifactName }}', ''), succeeded(), eq(variables['ROSLYN_CACHE_EXISTS'], 'true'))

    - task: PowerShell@2
      displayName: Prepare Unit Tests
      inputs:
        filePath: eng/prepare-tests.ps1
        arguments: -configuration ${{ parameters.configuration }}
      condition: and(ne(variables['artifactName'], ''), succeeded())

    - task: PublishPipelineArtifact@1
      displayName: Publish Test Payload
      inputs:
        targetPath: '$(Build.SourcesDirectory)\artifacts\testPayload'
        artifactName: ${{ parameters.testArtifactName }}
      condition: and(ne(variables['artifactName'], ''), succeeded())

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}

