# Template to evaluate common paths in different pipelines.
parameters:
- name: jobName
  type: string
  default: ''
- name: poolName
  type: string
  default: ''
- name: queueName
  type: string
  default: ''
- name: vmImageName
  type: string
  default: ''
- name: paths
  type: object
  default: []

jobs:
- job: ${{ parameters.jobName }}
  pool:
    ${{ if ne(parameters.queueName, '') }}:
      name: ${{ parameters.poolName }}
      demands: ImageOverride -equals ${{ parameters.queueName }}

    ${{ if ne(parameters.vmImageName, '') }}:
      vmImage: ${{ parameters.vmImageName }}
  timeoutInMinutes: 10

  steps:
  - template: checkout-unix-task.yml
    parameters:
      depth: 2
  
  - ${{ if ne(parameters.paths[0], '') }}:
    - ${{ each path in parameters.paths }}:
      - template: evaluate-changed-files-group.yml
        parameters:
          subsetName: ${{ path.subset }} 
          arguments:
          # The commit that we're building is always a merge commit that is merging into the target branch.
          # So the first parent of the commit is on the target branch and the second parent is on the source branch.
          - --difftarget HEAD^1
          - --subset ${{ path.subset }}
          - ${{ if ne(path.include[0], '') }}:
            - --includepaths '${{ join('+', path.include) }}'
          - ${{ if ne(path.exclude[0], '') }}:
            - --excludepaths '${{ join('+', path.exclude) }}'