# Test on Unix using Helix
parameters:
- name: helixQueueName
  type: string
- name: testRunName
  type: string
  default: ''
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: testArguments
  type: string
  default: ''
- name: helixApiAccessToken
  type: string
  default: ''
- name: poolParameters
  type: object

jobs:
- job: ${{ parameters.jobName }}
  pool: ${{ parameters.poolParameters }}
  timeoutInMinutes: 360
  steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: Download Test Payload
      inputs:
        artifact: ${{ parameters.testArtifactName }}
        path: '$(Build.SourcesDirectory)'

    - task: ShellScript@2
      displayName: Rehydrate RunTests
      inputs:
        scriptPath: ./artifacts/bin/RunTests/${{ parameters.configuration }}/net10.0/rehydrate.sh
      env:
        HELIX_CORRELATION_PAYLOAD: '$(Build.SourcesDirectory)/.duplicate'

    - task: Bash@3
      displayName: Run Unit Tests
      inputs:
        targetType: inline
        script: |
          set -e
          ci=true
          configuration='${{ parameters.configuration }}'
          source eng/common/tools.sh
          InitializeDotNetCli true
          helix_args=()
          if [[ -n "$HELIX_API_ACCESS_TOKEN" ]]; then
            helix_args+=(--helixApiAccessToken "$HELIX_API_ACCESS_TOKEN")
          fi
          "$_InitializeDotNetCli/dotnet" exec "$(Build.SourcesDirectory)/artifacts/bin/RunTests/${{ parameters.configuration }}/net10.0/RunTests.dll" --dotnet "$_InitializeDotNetCli/dotnet" --ci --helix --testConfiguration ${{ parameters.configuration }} --logs "$(Build.SourcesDirectory)/artifacts/log/${{ parameters.configuration }}" --helixQueueName ${{ parameters.helixQueueName }} "${helix_args[@]}" ${{ parameters.testArguments }}
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)
        HELIX_API_ACCESS_TOKEN: ${{ parameters.helixApiAccessToken }}
        DOTNET_ROLL_FORWARD: LatestMajor
        DOTNET_ROLL_FORWARD_TO_PRERELEASE: 1

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
        testRunName: ${{ parameters.testRunName }}
