# Test on Unix using Helix
parameters:
- name: helixQueueName
  type: string
- name: testRunName
  type: string
  default: ''
- name: jobName
  type: string
  default: ''
- name: testArtifactName
  type: string
  default: ''
- name: configuration
  type: string
  default: 'Debug'
- name: testArguments
  type: string
  default: ''
- name: helixApiAccessToken
  type: string
  default: ''
- name: poolParameters
  type: object

jobs:
- job: ${{ parameters.jobName }}
  pool: ${{ parameters.poolParameters }}
  timeoutInMinutes: 90
  steps:
    - checkout: none

    - task: DownloadPipelineArtifact@2
      displayName: Download Test Payload
      inputs:
        artifact: ${{ parameters.testArtifactName }}
        path: '$(Build.SourcesDirectory)'
    
    - task: ShellScript@2
      displayName: Rehydrate RunTests
      inputs:
        scriptPath: ./artifacts/bin/RunTests/${{ parameters.configuration }}/net7.0/rehydrate.sh
      env:
        HELIX_CORRELATION_PAYLOAD: '$(Build.SourcesDirectory)/.duplicate'

    - task: ShellScript@2
      inputs:
        scriptPath: ./eng/build.sh
        args: --ci --helix --configuration ${{ parameters.configuration }} --helixQueueName ${{ parameters.helixQueueName }} ${{ parameters.testArguments }}
      displayName: Test
      env:
        SYSTEM_ACCESSTOKEN: $(System.AccessToken)

    - template: publish-logs.yml
      parameters:
        configuration: ${{ parameters.configuration }}
        jobName: ${{ parameters.jobName }}
