// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (1,3)-(6,1) "x:\dir\subdir\Test\TestComponent.razor"

    var value = $"{
        1 + 1
    }";
    _ = value.Length;

#line default
#line hidden
#nullable disable

#nullable restore
#line (8,3)-(10,3) 24 "x:\dir\subdir\Test\TestComponent.razor"
__builder.AddContent(0, $"{
    1 + 1
}"

#line default
#line hidden
#nullable disable
            );
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
