// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line (1,2)-(1,9) "x:\dir\subdir\Test\TestComponent.cshtml"
using N

#nullable disable
    ;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent<
#nullable restore
#line (2,12)-(2,18) "x:\dir\subdir\Test\TestComponent.cshtml"
TParam

#line default
#line hidden
#nullable disable
    > : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
#nullable restore
#line (4,8)-(10,1) "x:\dir\subdir\Test\TestComponent.cshtml"

    [Parameter]
    public TParam InferParam { get; set; }

    [Parameter]
    public RenderFragment<(MyClass I1, MyStruct I2, TParam P)> Template { get; set; }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
