'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Reflection

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Public Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Resources", GetType(Resources).GetTypeInfo.Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Public Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove unnecessary methods..
        '''</summary>
        Public ReadOnly Property CodeBlockAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("CodeBlockAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Method &apos;{0}&apos; is a non-virtual method with an empty body. Consider removing this method from your assembly..
        '''</summary>
        Public ReadOnly Property CodeBlockAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("CodeBlockAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove unnecessary methods.
        '''</summary>
        Public ReadOnly Property CodeBlockAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("CodeBlockAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove unused parameters..
        '''</summary>
        Public ReadOnly Property CodeBlockStartedAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("CodeBlockStartedAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Parameter &apos;{0}&apos; is unused in the method &apos;{1}&apos;..
        '''</summary>
        Public ReadOnly Property CodeBlockStartedAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("CodeBlockStartedAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Remove unused parameters.
        '''</summary>
        Public ReadOnly Property CodeBlockStartedAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("CodeBlockStartedAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dont suppress analyzer diagnostics..
        '''</summary>
        Public ReadOnly Property CompilationAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("CompilationAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Analyzer diagnostic &apos;{0}&apos; is suppressed, consider removing this compilation wide suppression..
        '''</summary>
        Public ReadOnly Property CompilationAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("CompilationAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Dont suppress analyzer diagnostics.
        '''</summary>
        Public ReadOnly Property CompilationAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("CompilationAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not implement unsupported interface..
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type &apos;{0}&apos; implements interface &apos;{1}&apos;, which is only meant for internal implementation and might change in future. You should avoid implementing this interface..
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not implement unsupported interface.
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secure types must not implement interfaces with unsecure methods..
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerWithCompilationWideAnalysisDescription() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerWithCompilationWideAnalysisDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type &apos;{0}&apos; is a secure type as it implements interface &apos;{1}&apos;, but it also implements interface &apos;{2}&apos; which has unsecure method(s)..
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerWithCompilationWideAnalysisMessageFormat() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerWithCompilationWideAnalysisMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Secure types must not implement interfaces with unsecure methods.
        '''</summary>
        Public ReadOnly Property CompilationStartedAnalyzerWithCompilationWideAnalysisTitle() As String
            Get
                Return ResourceManager.GetString("CompilationStartedAnalyzerWithCompilationWideAnalysisTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source file declaration diagnostic count..
        '''</summary>
        Public ReadOnly Property SemanticModelAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("SemanticModelAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source file &apos;{0}&apos; has &apos;{1}&apos; declaration diagnostic(s).
        '''</summary>
        Public ReadOnly Property SemanticModelAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("SemanticModelAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Source file declaration diagnostics count.
        '''</summary>
        Public ReadOnly Property SemanticModelAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("SemanticModelAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not declare members with same name as containing type..
        '''</summary>
        Public ReadOnly Property SymbolAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("SymbolAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Type &apos;{0}&apos; has one or more members with the same name, considering renaming the type or the members..
        '''</summary>
        Public ReadOnly Property SymbolAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("SymbolAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not declare members with same name as containing type.
        '''</summary>
        Public ReadOnly Property SymbolAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("SymbolAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Declare explicit type for local declarations..
        '''</summary>
        Public ReadOnly Property SyntaxNodeAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("SyntaxNodeAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Local &apos;{0}&apos; is implicitly typed. Consider specifying its type explicitly in the declaration..
        '''</summary>
        Public ReadOnly Property SyntaxNodeAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("SyntaxNodeAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Declare explicit type for local declarations.
        '''</summary>
        Public ReadOnly Property SyntaxNodeAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("SyntaxNodeAnalyzerTitle", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not suppress documentation comment diagnostics..
        '''</summary>
        Public ReadOnly Property SyntaxTreeAnalyzerDescription() As String
            Get
                Return ResourceManager.GetString("SyntaxTreeAnalyzerDescription", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Enable documentation comment diagnostics on source file &apos;{0}&apos;..
        '''</summary>
        Public ReadOnly Property SyntaxTreeAnalyzerMessageFormat() As String
            Get
                Return ResourceManager.GetString("SyntaxTreeAnalyzerMessageFormat", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Do not suppress documentation comment diagnostics.
        '''</summary>
        Public ReadOnly Property SyntaxTreeAnalyzerTitle() As String
            Get
                Return ResourceManager.GetString("SyntaxTreeAnalyzerTitle", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
