// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
#nullable restore
#line (1,17)-(4,30) 4 "x:\dir\subdir\Test\TestComponent.razor"
/** <summary>
}
@code { public int Example => 1; }
</summary> Extra information.*/

#line default
#line hidden
#nullable disable
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
    }
}
#pragma warning restore 1591
