// <auto-generated/>
#pragma warning disable 1591
namespace 
#nullable restore
#line (1,12)-(1,28) "x:\dir\subdir\Test\TestComponent.cshtml"
Custom.Namespace

#line default
#line hidden
#nullable disable
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    [global::Custom.Namespace.TestComponent.__PrivateComponentRenderModeAttribute]
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
        private sealed class __PrivateComponentRenderModeAttribute : global::Microsoft.AspNetCore.Components.RenderModeAttribute
        {
            private static global::Microsoft.AspNetCore.Components.IComponentRenderMode ModeImpl => 
#nullable restore
#line (3,13)-(3,77) "x:\dir\subdir\Test\TestComponent.cshtml"
Microsoft.AspNetCore.Components.Web.RenderMode.InteractiveServer

#line default
#line hidden
#nullable disable

            ;
            public override global::Microsoft.AspNetCore.Components.IComponentRenderMode Mode => ModeImpl;
        }
    }
}
#pragma warning restore 1591
