
' This file is used by Code Analysis to maintain SuppressMessage 
' attributes that are applied to this project.
' Project-level suppressions either have no target or are given 
' a specific target and scoped to a namespace, type, member, etc.

' Baselined for the port, we should revisit these, see: https://github.com/dotnet/roslyn/issues/8183.
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.AppDesCommon.Utils.FocusFirstOrLastTabItem(System.IntPtr,System.Boolean)~System.Boolean")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.AppDesDesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndoing(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.AppDesDesignerFramework.DeferrableWindowPaneProviderServiceBase.DesignerWindowPaneBase.OnUndone(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.Create(System.IntPtr)~System.IntPtr")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropPageBase.Deactivate")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.PostValidation")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.InitializeStateOfUICues")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.PropertyPagePanel_GotFocus(System.Object,System.EventArgs)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Reliability", "RS0015:Always consume the value returned by methods marked with PreserveSigAttribute", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropPageDesigner.PropPageDesignerView.UpdateWindowStyles(System.IntPtr)")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.ApplicationDesigner.ApplicationDesignerView.GetPageGuids(System.Object)~System.Guid[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.MyApplication.MyApplicationPropertiesBase.FilesToCheckOut(System.Boolean)~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropertyControlData.FilesToCheckOut~System.String[]")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.RefreshPropertyStandardValues")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~M:Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.SetObjects(System.Object[])")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.ControlData")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropertyPages.PropPageUserControlBase.RawPropertiesObjectsOfAllProperties")>
<Assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Performance", "RS0007:Avoid zero-length array allocations.", Justification:="<Pending>", Scope:="member", Target:="~P:Microsoft.VisualStudio.Editors.PropPageDesigner.PropertyPageSerializationService.PropertyPageSerializationStore.Errors")>