#pragma checksum "Folder2/Component2.razor" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "6b035b1ceae4651124a6a654ee9943a6c99618b3"
// <auto-generated/>
#pragma warning disable 1591
namespace MyApp.Folder2
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class Component2 : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (1,3)-(1,26) "Folder2/Component2.razor"
 var c = new Class1(); 

#line default
#line hidden
#nullable disable

        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
