// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.Options;

namespace Microsoft.CodeAnalysis.EditorFeatures.Cocoa;

internal static class VisualStudioMacOptionStorage
{
    internal readonly struct PropertyName
    {
        private readonly string _name;
        private readonly string? _vbName;
        private readonly string? _altName;

        public PropertyName(string name, string? vbName = null, string? altName = null)
        {
            _name = name;
            _vbName = vbName;
            _altName = altName;
        }

        private static string SubstituteLanguage(string keyName, string? language)
            => keyName.Replace("%LANGUAGE%", language switch
            {
                LanguageNames.CSharp => "CSharp",
                LanguageNames.VisualBasic => "VisualBasic",
                _ => language // handles F#, TypeScript and Xaml
            });

        public string GetName(string? language)
            => (_vbName != null && language == LanguageNames.VisualBasic) ? _vbName : SubstituteLanguage(_name, language);

        public string? TryGetAlternativeName(string? language)
            => _altName != null ? SubstituteLanguage(_altName, language) : null;
    }

    /// <summary>
    /// Maps option config name to a legacy property name used in VS Mac XML settings file.
    /// This list is frozen and only used to enable migration from existing settings files.
    /// Do not add mappings for new options. <see cref="OptionDefinition.ConfigName"/> is going to be used as a property name for these options.
    /// </summary>
    public static readonly IReadOnlyDictionary<string, PropertyName> LegacyPropertyNames = new Dictionary<string, PropertyName>()
    {
        {"BlockStructureOptions_CollapseEmptyMetadataImplementationsWhenFirstOpened", new PropertyName("TextEditor.%LANGUAGE%.Specific.CollapseEmptyMetadataImplementationsWhenFirstOpened")},
        {"BlockStructureOptions_CollapseImportsWhenFirstOpened", new PropertyName("TextEditor.%LANGUAGE%.Specific.CollapseImportsWhenFirstOpened")},
        {"BlockStructureOptions_CollapseMetadataImplementationsWhenFirstOpened", new PropertyName("TextEditor.%LANGUAGE%.Specific.CollapseMetadataImplementationsWhenFirstOpened")},
        {"BlockStructureOptions_CollapseRegionsWhenCollapsingToDefinitions", new PropertyName("TextEditor.%LANGUAGE%.Specific.CollapseRegionsWhenCollapsingToDefinitions")},
        {"BlockStructureOptions_CollapseRegionsWhenFirstOpened", new PropertyName("TextEditor.%LANGUAGE%.Specific.CollapseRegionsWhenFirstOpened")},
        {"BlockStructureOptions_MaximumBannerLength", new PropertyName("TextEditor.%LANGUAGE%.Specific.MaximumBannerLength")},
        {"BlockStructureOptions_ShowBlockStructureGuidesForCodeLevelConstructs", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowBlockStructureGuidesForCodeLevelConstructs")},
        {"BlockStructureOptions_ShowBlockStructureGuidesForCommentsAndPreprocessorRegions", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowBlockStructureGuidesForCommentsAndPreprocessorRegions")},
        {"BlockStructureOptions_ShowBlockStructureGuidesForDeclarationLevelConstructs", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowBlockStructureGuidesForDeclarationLevelConstructs")},
        {"BlockStructureOptions_ShowOutliningForCodeLevelConstructs", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowOutliningForCodeLevelConstructs")},
        {"BlockStructureOptions_ShowOutliningForCommentsAndPreprocessorRegions", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowOutliningForCommentsAndPreprocessorRegions")},
        {"BlockStructureOptions_ShowOutliningForDeclarationLevelConstructs", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowOutliningForDeclarationLevelConstructs")},
        {"BraceCompletionOptions_AutoFormattingOnCloseBrace", new PropertyName("TextEditor.%LANGUAGE%.Specific.Auto Formatting On Close Brace")},
        {"ClassificationOptions_ClassifyReassignedVariables", new PropertyName("TextEditor.%LANGUAGE%.Specific.ClassificationOptions.ClassifyReassignedVariables")},
        {"CodeStyleOptions_PreferSystemHashCode", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferSystemHashCode")},
        {"CompletionOptions_BlockForCompletionItems", new PropertyName("TextEditor.%LANGUAGE%.Specific.BlockForCompletionItems")},
        {"CompletionOptions_EnableArgumentCompletionSnippets", new PropertyName("TextEditor.%LANGUAGE%.Specific.EnableArgumentCompletionSnippets")},
        {"CompletionOptions_EnterKeyBehavior", new PropertyName("TextEditor.%LANGUAGE%.Specific.EnterKeyBehavior")},
        {"CompletionOptions_HideAdvancedMembers", new PropertyName("TextEditor.%LANGUAGE%.Hide Advanced Auto List Members", vbName: "TextEditor.Basic.Hide Advanced Auto List Members")},
        {"CompletionOptions_HighlightMatchingPortionsOfCompletionListItems", new PropertyName("TextEditor.%LANGUAGE%.Specific.HighlightMatchingPortionsOfCompletionListItems")},
        {"CompletionOptions_ShowCompletionItemFilters", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowCompletionItemFilters")},
        {"CompletionOptions_ShowItemsFromUnimportedNamespaces", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowItemsFromUnimportedNamespaces")},
        {"CompletionOptions_ShowNameSuggestions", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowNameSuggestions")},
        {"CompletionOptions_ShowNewSnippetExperienceUserOption", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowNewSnippetExperience")},
        {"CompletionOptions_SnippetsBehavior", new PropertyName("TextEditor.%LANGUAGE%.Specific.SnippetsBehavior")},
        {"CompletionOptions_TriggerInArgumentLists", new PropertyName("TextEditor.%LANGUAGE%.Specific.TriggerInArgumentLists")},
        {"CompletionOptions_TriggerOnDeletion", new PropertyName("TextEditor.%LANGUAGE%.Specific.TriggerOnDeletion")},
        {"CompletionOptions_TriggerOnTyping", new PropertyName("TextEditor.%LANGUAGE%.Auto List Members", vbName: "TextEditor.Basic.Auto List Members")},
        {"CompletionOptions_TriggerOnTypingLetters", new PropertyName("TextEditor.%LANGUAGE%.Specific.TriggerOnTypingLetters")},
        {"csharp_indent_block_contents", new PropertyName("TextEditor.CSharp.Specific.IndentBlock")},
        {"csharp_indent_braces", new PropertyName("TextEditor.CSharp.Specific.OpenCloseBracesIndent")},
        {"csharp_indent_case_contents", new PropertyName("TextEditor.CSharp.Specific.IndentSwitchCaseSection")},
        {"csharp_indent_case_contents_when_block", new PropertyName("TextEditor.CSharp.Specific.IndentSwitchCaseSectionWhenBlock")},
        {"csharp_indent_labels", new PropertyName("TextEditor.CSharp.Specific.LabelPositioning")},
        {"csharp_indent_switch_labels", new PropertyName("TextEditor.CSharp.Specific.IndentSwitchSection")},
        {"csharp_new_line_before_open_brace", new PropertyName("TextEditor.CSharp.Specific.csharp_new_line_before_open_brace") },
        {"csharp_new_line_before_catch", new PropertyName("TextEditor.CSharp.Specific.NewLineForCatch")},
        {"csharp_new_line_before_else", new PropertyName("TextEditor.CSharp.Specific.NewLineForElse")},
        {"csharp_new_line_before_finally", new PropertyName("TextEditor.CSharp.Specific.NewLineForFinally")},
        {"csharp_new_line_before_members_in_anonymous_types", new PropertyName("TextEditor.CSharp.Specific.NewLineForMembersInAnonymousTypes")},
        {"csharp_new_line_before_members_in_object_initializers", new PropertyName("TextEditor.CSharp.Specific.NewLineForMembersInObjectInit")},
        {"csharp_new_line_between_query_expression_clauses", new PropertyName("TextEditor.CSharp.Specific.NewLineForClausesInQuery")},
        {"csharp_prefer_braces", new PropertyName("TextEditor.CSharp.Specific.PreferBraces")},
        {"csharp_prefer_simple_default_expression", new PropertyName("TextEditor.CSharp.Specific.PreferSimpleDefaultExpression")},
        {"csharp_prefer_simple_using_statement", new PropertyName("TextEditor.CSharp.Specific.PreferSimpleUsingStatement")},
        {"csharp_prefer_static_local_function", new PropertyName("TextEditor.CSharp.Specific.PreferStaticLocalFunction")},
        {"csharp_preferred_modifier_order", new PropertyName("TextEditor.CSharp.Specific.PreferredModifierOrder")},
        {"csharp_preserve_single_line_blocks", new PropertyName("TextEditor.CSharp.Specific.WrappingPreserveSingleLine")},
        {"csharp_preserve_single_line_statements", new PropertyName("TextEditor.CSharp.Specific.WrappingKeepStatementsOnSingleLine")},
        {"csharp_space_after_cast", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterCast")},
        {"csharp_space_after_colon_in_inheritance_clause", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterColonInBaseTypeDeclaration")},
        {"csharp_space_after_comma", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterComma")},
        {"csharp_space_after_dot", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterDot")},
        {"csharp_space_after_keywords_in_control_flow_statements", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterControlFlowStatementKeyword")},
        {"csharp_space_after_semicolon_in_for_statement", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterSemicolonsInForStatement")},
        {"csharp_space_around_binary_operators", new PropertyName("TextEditor.CSharp.Specific.SpacingAroundBinaryOperator")},
        {"csharp_space_around_declaration_statements", new PropertyName("TextEditor.CSharp.Specific.SpacesIgnoreAroundVariableDeclaration")},
        {"csharp_space_before_colon_in_inheritance_clause", new PropertyName("TextEditor.CSharp.Specific.SpaceBeforeColonInBaseTypeDeclaration")},
        {"csharp_space_before_comma", new PropertyName("TextEditor.CSharp.Specific.SpaceBeforeComma")},
        {"csharp_space_before_dot", new PropertyName("TextEditor.CSharp.Specific.SpaceBeforeDot")},
        {"csharp_space_before_open_square_brackets", new PropertyName("TextEditor.CSharp.Specific.SpaceBeforeOpenSquareBracket")},
        {"csharp_space_before_semicolon_in_for_statement", new PropertyName("TextEditor.CSharp.Specific.SpaceBeforeSemicolonsInForStatement")},
        {"csharp_space_between_empty_square_brackets", new PropertyName("TextEditor.CSharp.Specific.SpaceBetweenEmptySquareBrackets")},
        {"csharp_space_between_method_call_empty_parameter_list_parentheses", new PropertyName("TextEditor.CSharp.Specific.SpaceBetweenEmptyMethodCallParentheses")},
        {"csharp_space_between_method_call_name_and_opening_parenthesis", new PropertyName("TextEditor.CSharp.Specific.SpaceAfterMethodCallName")},
        {"csharp_space_between_method_call_parameter_list_parentheses", new PropertyName("TextEditor.CSharp.Specific.SpaceWithinMethodCallParentheses")},
        {"csharp_space_between_method_declaration_empty_parameter_list_parentheses", new PropertyName("TextEditor.CSharp.Specific.SpaceBetweenEmptyMethodDeclarationParentheses")},
        {"csharp_space_between_method_declaration_name_and_open_parenthesis", new PropertyName("TextEditor.CSharp.Specific.SpacingAfterMethodDeclarationName")},
        {"csharp_space_between_method_declaration_parameter_list_parentheses", new PropertyName("TextEditor.CSharp.Specific.SpaceWithinMethodDeclarationParenthesis")},
        {"csharp_space_between_parentheses", new PropertyName("TextEditor.CSharp.Specific.csharp_space_between_parentheses") },
        {"csharp_space_between_square_brackets", new PropertyName("TextEditor.CSharp.Specific.SpaceWithinSquareBrackets")},
        {"csharp_style_allow_blank_line_after_colon_in_constructor_initializer_experimental", new PropertyName("TextEditor.CSharp.Specific.AllowBlankLineAfterColonInConstructorInitializer")},
        {"csharp_style_allow_blank_line_after_token_in_arrow_expression_clause_experimental", new PropertyName("TextEditor.CSharp.Specific.AllowBlankLineAfterTokenInArrowExpressionClause")},
        {"csharp_style_allow_blank_line_after_token_in_conditional_expression_experimental", new PropertyName("TextEditor.CSharp.Specific.AllowBlankLineAfterTokenInConditionalExpression")},
        {"csharp_style_allow_blank_lines_between_consecutive_braces_experimental", new PropertyName("TextEditor.CSharp.Specific.AllowBlankLinesBetweenConsecutiveBraces")},
        {"csharp_style_allow_embedded_statements_on_same_line_experimental", new PropertyName("TextEditor.CSharp.Specific.AllowEmbeddedStatementsOnSameLine")},
        {"csharp_style_conditional_delegate_call", new PropertyName("TextEditor.CSharp.Specific.PreferConditionalDelegateCall")},
        {"csharp_style_deconstructed_variable_declaration", new PropertyName("TextEditor.CSharp.Specific.PreferDeconstructedVariableDeclaration")},
        {"csharp_style_expression_bodied_accessors", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedAccessors")},
        {"csharp_style_expression_bodied_constructors", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedConstructors")},
        {"csharp_style_expression_bodied_indexers", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedIndexers")},
        {"csharp_style_expression_bodied_lambdas", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedLambdas")},
        {"csharp_style_expression_bodied_local_functions", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedLocalFunctions")},
        {"csharp_style_expression_bodied_methods", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedMethods")},
        {"csharp_style_expression_bodied_operators", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedOperators")},
        {"csharp_style_expression_bodied_properties", new PropertyName("TextEditor.CSharp.Specific.PreferExpressionBodiedProperties")},
        {"csharp_style_implicit_object_creation_when_type_is_apparent", new PropertyName("TextEditor.CSharp.Specific.ImplicitObjectCreationWhenTypeIsApparent")},
        {"csharp_style_inlined_variable_declaration", new PropertyName("TextEditor.CSharp.Specific.PreferInlinedVariableDeclaration")},
        {"csharp_style_namespace_declarations", new PropertyName("TextEditor.CSharp.Specific.NamespaceDeclarations")},
        {"csharp_style_pattern_matching_over_as_with_null_check", new PropertyName("TextEditor.CSharp.Specific.PreferPatternMatchingOverAsWithNullCheck")},
        {"csharp_style_pattern_matching_over_is_with_cast_check", new PropertyName("TextEditor.CSharp.Specific.PreferPatternMatchingOverIsWithCastCheck")},
        {"csharp_style_prefer_extended_property_pattern", new PropertyName("TextEditor.CSharp.Specific.PreferExtendedPropertyPattern")},
        {"csharp_style_prefer_index_operator", new PropertyName("TextEditor.CSharp.Specific.PreferIndexOperator")},
        {"csharp_style_prefer_local_over_anonymous_function", new PropertyName("TextEditor.CSharp.Specific.PreferLocalOverAnonymousFunction")},
        {"csharp_style_prefer_method_group_conversion", new PropertyName("TextEditor.CSharp.Specific.PreferMethodGroupConversion")},
        {"csharp_style_prefer_not_pattern", new PropertyName("TextEditor.CSharp.Specific.PreferNotPattern")},
        {"csharp_style_prefer_null_check_over_type_check", new PropertyName("TextEditor.CSharp.Specific.PreferNullCheckOverTypeCheck")},
        {"csharp_style_prefer_pattern_matching", new PropertyName("TextEditor.CSharp.Specific.PreferPatternMatching")},
        {"csharp_style_prefer_range_operator", new PropertyName("TextEditor.CSharp.Specific.PreferRangeOperator")},
        {"csharp_style_prefer_readonly_struct", new PropertyName("TextEditor.CSharp.Specific.PreferReadOnlyStruct")},
        {"csharp_style_prefer_switch_expression", new PropertyName("TextEditor.CSharp.Specific.PreferSwitchExpression")},
        {"csharp_style_prefer_top_level_statements", new PropertyName("TextEditor.CSharp.Specific.PreferTopLevelStatements")},
        {"csharp_style_prefer_tuple_swap", new PropertyName("TextEditor.CSharp.Specific.PreferTupleSwap")},
        {"csharp_style_prefer_utf8_string_literals", new PropertyName("TextEditor.CSharp.Specific.PreferUtf8StringLiterals")},
        {"csharp_style_throw_expression", new PropertyName("TextEditor.CSharp.Specific.PreferThrowExpression")},
        {"csharp_style_unused_value_assignment_preference", new PropertyName("TextEditor.CSharp.Specific.UnusedValueAssignmentPreference")},
        {"csharp_style_unused_value_expression_statement_preference", new PropertyName("TextEditor.%LANGUAGE%.Specific.UnusedValueExpressionStatementPreference")},
        {"csharp_style_var_elsewhere", new PropertyName("TextEditor.CSharp.Specific.UseImplicitTypeWherePossible")},
        {"csharp_style_var_for_built_in_types", new PropertyName("TextEditor.CSharp.Specific.UseImplicitTypeForIntrinsicTypes")},
        {"csharp_style_var_when_type_is_apparent", new PropertyName("TextEditor.CSharp.Specific.UseImplicitTypeWhereApparent")},
        {"csharp_using_directive_placement", new PropertyName("TextEditor.CSharp.Specific.PreferredUsingDirectivePlacement")},
        {"DateAndTime_ProvideDateAndTimeCompletions", new PropertyName("TextEditor.%LANGUAGE%.Specific.ProvideDateAndTimeCompletions")},
        {"DocumentationCommentOptions_AutoXmlDocCommentGeneration", new PropertyName("TextEditor.%LANGUAGE%.Specific.Automatic XML Doc Comment Generation", "TextEditor.VisualBasic.Specific.AutoComment")},
        {"dotnet_code_quality_unused_parameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.UnusedParametersPreference")},
        {"dotnet_remove_unnecessary_suppression_exclusions", new PropertyName("TextEditor.%LANGUAGE%.Specific.RemoveUnnecessarySuppressionExclusions")},
        {"dotnet_separate_import_directive_groups", new PropertyName("TextEditor.%LANGUAGE%.Specific.SeparateImportDirectiveGroups")},
        {"dotnet_sort_system_directives_first", new PropertyName("TextEditor.%LANGUAGE%.Specific.PlaceSystemNamespaceFirst")},
        {"dotnet_style_allow_multiple_blank_lines_experimental", new PropertyName("TextEditor.%LANGUAGE%.Specific.AllowMultipleBlankLines")},
        {"dotnet_style_allow_statement_immediately_after_block_experimental", new PropertyName("TextEditor.%LANGUAGE%.Specific.AllowStatementImmediatelyAfterBlock")},
        {"dotnet_style_coalesce_expression", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferCoalesceExpression")},
        {"dotnet_style_collection_initializer", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferCollectionInitializer")},
        {"dotnet_style_explicit_tuple_names", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferExplicitTupleNames")},
        {"dotnet_style_namespace_match_folder", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferNamespaceAndFolderMatchStructure")},
        {"dotnet_style_null_propagation", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferNullPropagation")},
        {"dotnet_style_object_initializer", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferObjectInitializer")},
        {"dotnet_style_parentheses_in_arithmetic_binary_operators", new PropertyName("TextEditor.%LANGUAGE%.Specific.ArithmeticBinaryParenthesesPreference")},
        {"dotnet_style_parentheses_in_other_binary_operators", new PropertyName("TextEditor.%LANGUAGE%.Specific.OtherBinaryParenthesesPreference")},
        {"dotnet_style_parentheses_in_other_operators", new PropertyName("TextEditor.%LANGUAGE%.Specific.OtherParenthesesPreference")},
        {"dotnet_style_parentheses_in_relational_binary_operators", new PropertyName("TextEditor.%LANGUAGE%.Specific.RelationalBinaryParenthesesPreference")},
        {"dotnet_style_predefined_type_for_locals_parameters_members", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferIntrinsicPredefinedTypeKeywordInDeclaration.CodeStyle")},
        {"dotnet_style_predefined_type_for_member_access", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferIntrinsicPredefinedTypeKeywordInMemberAccess.CodeStyle")},
        {"dotnet_style_prefer_auto_properties", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferAutoProperties")},
        {"dotnet_style_prefer_compound_assignment", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferCompoundAssignment")},
        {"dotnet_style_prefer_conditional_expression_over_assignment", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferConditionalExpressionOverAssignment")},
        {"dotnet_style_prefer_conditional_expression_over_return", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferConditionalExpressionOverReturn")},
        {"dotnet_style_prefer_inferred_anonymous_type_member_names", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferInferredAnonymousTypeMemberNames")},
        {"dotnet_style_prefer_inferred_tuple_names", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferInferredTupleNames")},
        {"dotnet_style_prefer_is_null_check_over_reference_equality_method", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferIsNullCheckOverReferenceEqualityMethod")},
        {"dotnet_style_prefer_simplified_boolean_expressions", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferSimplifiedBooleanExpressions")},
        {"dotnet_style_prefer_simplified_interpolation", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferSimplifiedInterpolation")},
        {"dotnet_style_qualification_for_event", new PropertyName("TextEditor.%LANGUAGE%.Specific.QualifyEventAccess")},
        {"dotnet_style_qualification_for_field", new PropertyName("TextEditor.%LANGUAGE%.Specific.QualifyFieldAccess")},
        {"dotnet_style_qualification_for_method", new PropertyName("TextEditor.%LANGUAGE%.Specific.QualifyMethodAccess")},
        {"dotnet_style_qualification_for_property", new PropertyName("TextEditor.%LANGUAGE%.Specific.QualifyPropertyAccess")},
        {"dotnet_style_readonly_field", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreferReadonly")},
        {"dotnet_style_require_accessibility_modifiers", new PropertyName("TextEditor.%LANGUAGE%.Specific.RequireAccessibilityModifiers")},
        {"EditorComponentOnOffOptions_Adornment", new PropertyName(@"Roslyn\Internal\OnOff\Components\Adornment")},
        {"EditorComponentOnOffOptions_CodeRefactorings", new PropertyName(@"Roslyn\Internal\OnOff\Components\Code Refactorings")},
        {"EditorComponentOnOffOptions_Tagger", new PropertyName(@"Roslyn\Internal\OnOff\Components\Tagger")},
        {"ExtractMethodOptions_AllowBestEffort", new PropertyName("TextEditor.%LANGUAGE%.Specific.Allow Best Effort")},
        {"ExtractMethodOptions_DontPutOutOrRefOnStruct", new PropertyName("TextEditor.%LANGUAGE%.Specific.Don't Put Out Or Ref On Strcut")},
        {"FadingOptions_FadeOutUnreachableCode", new PropertyName("TextEditor.%LANGUAGE%.Specific.FadeOutUnreachableCode")},
        {"FadingOptions_FadeOutUnusedImports", new PropertyName("TextEditor.%LANGUAGE%.Specific.FadeOutUnusedImports")},
        {"Storage_Database", new PropertyName(@"Roslyn\Internal\OnOff\Features\Database")},
        {"FeatureOnOffOptions_AddImportsOnPaste", new PropertyName("TextEditor.%LANGUAGE%.Specific.AddImportsOnPaste2")},
        {"FeatureOnOffOptions_AlwaysUseDefaultSymbolServers", new PropertyName("TextEditor.AlwaysUseDefaultSymbolServers")},
        {"FeatureOnOffOptions_AutoInsertBlockCommentStartString", new PropertyName("TextEditor.%LANGUAGE%.Specific.Auto Insert Block Comment Start String")},
        {"FeatureOnOffOptions_AutomaticallyCompleteStatementOnSemicolon", new PropertyName("TextEditor.AutomaticallyCompleteStatementOnSemicolon")},
        {"FeatureOnOffOptions_AutomaticallyFixStringContentsOnPaste", new PropertyName("TextEditor.%LANGUAGE%.AutomaticallyFixStringContentsOnPaste")},
        {"FeatureOnOffOptions_AutomaticInsertionOfAbstractOrInterfaceMembers", new PropertyName("TextEditor.%LANGUAGE%.Specific.AutoRequiredMemberInsert")},
        {"FeatureOnOffOptions_EndConstruct", new PropertyName("TextEditor.%LANGUAGE%.Specific.AutoEndInsert")},
        {"FeatureOnOffOptions_InheritanceMarginCombinedWithIndicatorMargin", new PropertyName("TextEditor.InheritanceMarginCombinedWithIndicatorMargin")},
        {"FeatureOnOffOptions_InheritanceMarginIncludeGlobalImports", new PropertyName("TextEditor.%LANGUAGE%.Specific.InheritanceMarginIncludeGlobalImports")},
        {"FeatureOnOffOptions_KeywordHighlighting", new PropertyName("TextEditor.%LANGUAGE%.Specific.Keyword Highlighting", "TextEditor.VisualBasic.Specific.EnableHighlightRelatedKeywords")},
        {"FeatureOnOffOptions_LineSeparator", new PropertyName("TextEditor.%LANGUAGE%.Specific.Line Separator", "TextEditor.VisualBasic.Specific.DisplayLineSeparators")},
        {"FeatureOnOffOptions_NavigateAsynchronously", new PropertyName("TextEditor.NavigateAsynchronously")},
        {"FeatureOnOffOptions_NavigateToDecompiledSources", new PropertyName("TextEditor.NavigateToDecompiledSources")},
        {"FeatureOnOffOptions_NavigateToSourceLinkAndEmbeddedSources", new PropertyName("TextEditor.NavigateToSourceLinkAndEmbeddedSources")},
        {"FeatureOnOffOptions_OfferRemoveUnusedReferences", new PropertyName("TextEditor.OfferRemoveUnusedReferences")},
        {"FeatureOnOffOptions_Outlining", new PropertyName("TextEditor.%LANGUAGE%.Specific.Outlining")},
        {"FeatureOnOffOptions_PrettyListing", new PropertyName("TextEditor.%LANGUAGE%.Specific.PrettyListing")},
        {"FeatureOnOffOptions_ReferenceHighlighting", new PropertyName("TextEditor.%LANGUAGE%.Specific.Reference Highlighting", "TextEditor.VisualBasic.Specific.EnableHighlightReferences")},
        {"FeatureOnOffOptions_RenameTrackingPreview", new PropertyName("TextEditor.%LANGUAGE%.Specific.Rename Tracking Preview", "TextEditor.VisualBasic.Specific.RenameTrackingPreview")},
        {"FeatureOnOffOptions_ShowInheritanceMargin", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowInheritanceMargin")},
        {"FeatureOnOffOptions_SkipAnalyzersForImplicitlyTriggeredBuilds", new PropertyName("TextEditor.SkipAnalyzersForImplicitlyTriggeredBuilds")},
        {"FeatureOnOffOptions_StringIdentation", new PropertyName("TextEditor.%LANGUAGE%.Specific.StringIdentation")},
        {"FindUsagesOptions_DefinitionGroupingPriority", new PropertyName(@"Roslyn\Internal\FindUsages\DefinitionGroupingPriority")},
        {"FormattingOptions_AutoFormattingOnReturn", new PropertyName("TextEditor.%LANGUAGE%.Specific.Auto Formatting On Return")},
        {"FormattingOptions_AutoFormattingOnSemicolon", new PropertyName("TextEditor.%LANGUAGE%.Specific.Auto Formatting On Semicolon")},
        {"FormattingOptions_AutoFormattingOnTyping", new PropertyName("TextEditor.%LANGUAGE%.Specific.Auto Formatting On Typing")},
        {"FormattingOptions_FormatOnPaste", new PropertyName("TextEditor.%LANGUAGE%.Specific.FormatOnPaste")},
        {"FormattingOptions_SmartIndent", new PropertyName("TextEditor.%LANGUAGE%.Indent Style", vbName: "TextEditor.Basic.Indent Style")},
        {"GenerateConstructorFromMembersOptions_AddNullChecks", new PropertyName("TextEditor.%LANGUAGE%.Specific.GenerateConstructorFromMembersOptions.AddNullChecks")},
        {"GenerateEqualsAndGetHashCodeFromMembersOptions_GenerateOperators", new PropertyName("TextEditor.%LANGUAGE%.Specific.GenerateEqualsAndGetHashCodeFromMembersOptions.GenerateOperators")},
        {"GenerateEqualsAndGetHashCodeFromMembersOptions_ImplementIEquatable", new PropertyName("TextEditor.%LANGUAGE%.Specific.GenerateEqualsAndGetHashCodeFromMembersOptions.ImplementIEquatable")},
        {"GenerateOverridesOptions_SelectAll", new PropertyName("TextEditor.Specific.GenerateOverridesOptions.SelectAll")},
        {"ImplementTypeOptions_InsertionBehavior", new PropertyName("TextEditor.%LANGUAGE%.ImplementTypeOptions.InsertionBehavior")},
        {"ImplementTypeOptions_PropertyGenerationBehavior", new PropertyName("TextEditor.%LANGUAGE%.ImplementTypeOptions.PropertyGenerationBehavior")},
        {"indent_size", new PropertyName("TextEditor.%LANGUAGE%.Indent Size", vbName: "TextEditor.Basic.Indent Size")},
        {"indent_style", new PropertyName("TextEditor.%LANGUAGE%.Insert Tabs", vbName: "TextEditor.Basic.Insert Tabs")},
        {"InlineDiagnosticsOptions_EnableInlineDiagnostics", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineDiagnostics")},
        {"InlineDiagnosticsOptions_Location", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineDiagnostics.LocationOption")},
        {"InlineHintsOptions_ColorHints", new PropertyName("TextEditor.%LANGUAGE%.Specific.ColorHints")},
        {"InlineHintsOptions_DisplayAllHintsWhilePressingAltF1", new PropertyName("TextEditor.Specific.DisplayAllHintsWhilePressingAltF1")},
        {"InlineHintsOptions_EnabledForParameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints")},
        {"InlineHintsOptions_EnabledForTypes", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineTypeHints")},
        {"InlineHintsOptions_ForImplicitObjectCreation", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineTypeHints.ForImplicitObjectCreation")},
        {"InlineHintsOptions_ForImplicitVariableTypes", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineTypeHints.ForImplicitVariableTypes")},
        {"InlineHintsOptions_ForIndexerParameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.ForArrayIndexers")},
        {"InlineHintsOptions_ForLambdaParameterTypes", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineTypeHints.ForLambdaParameterTypes")},
        {"InlineHintsOptions_ForLiteralParameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.ForLiteralParameters")},
        {"InlineHintsOptions_ForObjectCreationParameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.ForObjectCreationParameters")},
        {"InlineHintsOptions_ForOtherParameters", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.ForOtherParameters")},
        {"InlineHintsOptions_SuppressForParametersThatDifferOnlyBySuffix", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.SuppressForParametersThatDifferOnlyBySuffix")},
        {"InlineHintsOptions_SuppressForParametersThatMatchArgumentName", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.SuppressForParametersThatMatchArgumentName")},
        {"InlineHintsOptions_SuppressForParametersThatMatchMethodIntent", new PropertyName("TextEditor.%LANGUAGE%.Specific.InlineParameterNameHints.SuppressForParametersThatMatchMethodIntent")},
        {"InlineRename_CollapseRenameUI", new PropertyName("TextEditor.CollapseRenameUI")},
        {"InlineRename_UseInlineAdornment", new PropertyName("TextEditor.RenameUseInlineAdornment")},
        {"InlineRenameSessionOptions_PreviewChanges", new PropertyName("TextEditor.%LANGUAGE%.Specific.PreviewRename")},
        {"InlineRenameSessionOptions_RenameAsynchronously", new PropertyName("TextEditor.%LANGUAGE%.Specific.RenameAsynchronously")},
        {"InlineRenameSessionOptions_RenameFile", new PropertyName("TextEditor.%LANGUAGE%.Specific.RenameFile")},
        {"InlineRenameSessionOptions_RenameInComments", new PropertyName("TextEditor.%LANGUAGE%.Specific.RenameInComments")},
        {"InlineRenameSessionOptions_RenameInStrings", new PropertyName("TextEditor.%LANGUAGE%.Specific.RenameInStrings")},
        {"InlineRenameSessionOptions_RenameOverloads", new PropertyName("TextEditor.%LANGUAGE%.Specific.RenameOverloads")},
        {"InternalDiagnosticsOptions_CrashOnAnalyzerException", new PropertyName(@"Roslyn\Internal\Diagnostics\CrashOnAnalyzerException")},
        {"InternalDiagnosticsOptions_EnableFileLoggingForDiagnostics", new PropertyName(@"Roslyn\Internal\Diagnostics\EnableFileLoggingForDiagnostics")},
        {"InternalDiagnosticsOptions_NormalDiagnosticMode", new PropertyName(@"Roslyn\Internal\Diagnostics\NormalDiagnosticMode")},
        {"InternalFeatureOnOffOptions_AutomaticLineEnder", new PropertyName(@"Roslyn\Internal\OnOff\Features\Automatic Line Ender")},
        {"InternalFeatureOnOffOptions_BraceMatching", new PropertyName(@"Roslyn\Internal\OnOff\Features\Brace Matching")},
        {"InternalFeatureOnOffOptions_Classification", new PropertyName(@"Roslyn\Internal\OnOff\Features\Classification")},
        {"InternalFeatureOnOffOptions_EventHookup", new PropertyName(@"Roslyn\Internal\OnOff\Features\Event Hookup")},
        {"InternalFeatureOnOffOptions_FormatOnSave", new PropertyName(@"Roslyn\Internal\OnOff\Features\FormatOnSave")},
        {"InternalFeatureOnOffOptions_FullSolutionAnalysisMemoryMonitor", new PropertyName(@"Roslyn\Internal\OnOff\Features\Full Solution Analysis Memory Monitor")},
        {"InternalFeatureOnOffOptions_OOP64Bit", new PropertyName(@"Roslyn\Internal\OnOff\Features\OOP64Bit")},
        {"InternalFeatureOnOffOptions_RemoveRecommendationLimit", new PropertyName(@"Roslyn\Internal\OnOff\Features\RemoveRecommendationLimit")},
        {"InternalFeatureOnOffOptions_RenameTracking", new PropertyName(@"Roslyn\Internal\OnOff\Features\Rename Tracking")},
        {"InternalFeatureOnOffOptions_SemanticColorizer", new PropertyName(@"Roslyn\Internal\OnOff\Features\Semantic Colorizer")},
        {"InternalFeatureOnOffOptions_ShowDebugInfo", new PropertyName(@"Roslyn\Internal\OnOff\Features\ShowDebugInfo")},
        {"InternalFeatureOnOffOptions_SmartIndenter", new PropertyName(@"Roslyn\Internal\OnOff\Features\Smart Indenter")},
        {"InternalFeatureOnOffOptions_Snippets", new PropertyName(@"Roslyn\Internal\OnOff\Features\Snippets2")},
        {"InternalFeatureOnOffOptions_Squiggles", new PropertyName(@"Roslyn\Internal\OnOff\Features\Squiggles")},
        {"InternalFeatureOnOffOptions_SyntacticColorizer", new PropertyName(@"Roslyn\Internal\OnOff\Features\Syntactic Colorizer")},
        {"InternalSolutionCrawlerOptions_Solution Crawler", new PropertyName(@"Roslyn\Internal\SolutionCrawler\Solution Crawler")},
        {"JsonFeatureOptions_ColorizeJsonPatterns", new PropertyName("TextEditor.%LANGUAGE%.Specific.ColorizeJsonPatterns")},
        {"JsonFeatureOptions_DetectAndOfferEditorFeaturesForProbableJsonStrings", new PropertyName("TextEditor.%LANGUAGE%.Specific.DetectAndOfferEditorFeaturesForProbableJsonStrings")},
        {"JsonFeatureOptions_HighlightRelatedJsonComponentsUnderCursor", new PropertyName("TextEditor.%LANGUAGE%.Specific.HighlightRelatedJsonComponentsUnderCursor")},
        {"JsonFeatureOptions_ReportInvalidJsonPatterns", new PropertyName("TextEditor.%LANGUAGE%.Specific.ReportInvalidJsonPatterns")},
        {"LspOptions_MaxCompletionListSize", new PropertyName(@"Roslyn\Internal\Lsp\MaxCompletionListSize")},
        {"NavigationBarOptions_ShowNavigationBar", new PropertyName("TextEditor.%LANGUAGE%.Dropdown Bar", vbName: "TextEditor.Basic.Dropdown Bar")},
        {"QuickInfoOptions_IncludeNavigationHintsInQuickInfo", new PropertyName("TextEditor.Specific.IncludeNavigationHintsInQuickInfo")},
        {"QuickInfoOptions_ShowRemarksInQuickInfo", new PropertyName("TextEditor.%LANGUAGE%.Specific.ShowRemarks")},
        {"RegularExpressionsOptions_ColorizeRegexPatterns", new PropertyName("TextEditor.%LANGUAGE%.Specific.ColorizeRegexPatterns")},
        {"RegularExpressionsOptions_HighlightRelatedRegexComponentsUnderCursor", new PropertyName("TextEditor.%LANGUAGE%.Specific.HighlightRelatedRegexComponentsUnderCursor")},
        {"RegularExpressionsOptions_ProvideRegexCompletions", new PropertyName("TextEditor.%LANGUAGE%.Specific.ProvideRegexCompletions")},
        {"RegularExpressionsOptions_ReportInvalidRegexPatterns", new PropertyName("TextEditor.%LANGUAGE%.Specific.ReportInvalidRegexPatterns")},
        {"ServiceFeatureOnOffOptions_RemoveDocumentDiagnosticsOnDocumentClose", new PropertyName("TextEditor.%LANGUAGE%.Specific.RemoveDocumentDiagnosticsOnDocumentClose")},
        {"SignatureHelpOptions_ShowSignatureHelp", new PropertyName("TextEditor.%LANGUAGE%.Auto List Params", vbName: "TextEditor.Basic.Auto List Params")},
        {"SimplificationOptions_NamingPreferences", new PropertyName("TextEditor.%LANGUAGE%.Specific.NamingPreferences5", altName: "TextEditor.%LANGUAGE%.Specific.NamingPreferences")},
        {"SolutionCrawlerOptionsStorage_BackgroundAnalysisScopeOption", new PropertyName("TextEditor.%LANGUAGE%.Specific.BackgroundAnalysisScopeOption")},
        {"SolutionCrawlerOptionsStorage_CompilerDiagnosticsScopeOption", new PropertyName("TextEditor.%LANGUAGE%.Specific.CompilerDiagnosticsScopeOption")},
        {"SplitCommentOptions_Enabled", new PropertyName("TextEditor.%LANGUAGE%.Specific.SplitComments")},
        {"SplitStringLiteralOptions_Enabled", new PropertyName("TextEditor.%LANGUAGE%.Specific.SplitStringLiterals")},
        {"StackTraceExplorerOptions_OpenOnFocus", new PropertyName("StackTraceExplorer.Options.OpenOnFocus")},
        {"SuggestionsOptions_Asynchronous", new PropertyName("TextEditor.Specific.Suggestions.Asynchronous4")},
        {"SymbolSearchOptions_Enabled", new PropertyName(@"Roslyn\Features\SymbolSearch\Enabled")},
        {"SymbolSearchOptions_SuggestForTypesInNuGetPackages", new PropertyName("TextEditor.%LANGUAGE%.Specific.SuggestForTypesInNuGetPackages")},
        {"SymbolSearchOptions_SuggestForTypesInReferenceAssemblies", new PropertyName("TextEditor.%LANGUAGE%.Specific.SuggestForTypesInReferenceAssemblies")},
        {"tab_width", new PropertyName("TextEditor.%LANGUAGE%.Tab Size", "TextEditor.Basic.Tab Size")},
        {"TaskListOptionsStorage_ComputeTaskListItemsForClosedFiles", new PropertyName("TextEditor.Specific.ComputeTaskListItemsForClosedFiles")},
        {"TaskListOptionsStorage_Descriptors", new PropertyName("Microsoft.VisualStudio.ErrorListPkg.Shims.TaskListOptions.CommentTokens")},
        {"UseConditionalExpressionOptions_ConditionalExpressionWrappingLength", new PropertyName("TextEditor.%LANGUAGE%.Specific.ConditionalExpressionWrappingLength")},
        {"ValidateFormatStringOption_ReportInvalidPlaceholdersInStringDotFormatCalls", new PropertyName("TextEditor.%LANGUAGE%.Specific.WarnOnInvalidStringDotFormatCalls")},
        {"visual_basic_preferred_modifier_order", new PropertyName("TextEditor.VisualBasic.Specific.PreferredModifierOrder")},
        {"visual_basic_style_prefer_isnot_expression", new PropertyName("TextEditor.VisualBasic.Specific.PreferIsNotExpression")},
        {"visual_basic_style_prefer_simplified_object_creation", new PropertyName("TextEditor.VisualBasic.Specific.PreferSimplifiedObjectCreation")},
        {"visual_basic_style_unused_value_assignment_preference", new PropertyName("TextEditor.VisualBasic.Specific.UnusedValueAssignmentPreference")},
        {"visual_basic_style_unused_value_expression_statement_preference", new PropertyName("TextEditor.VisualBasic.Specific.UnusedValueExpressionStatementPreference")},
        {"WorkspaceConfigurationOptions_EnableDiagnosticsInSourceGeneratedFiles", new PropertyName("TextEditor.Roslyn.Specific.EnableDiagnosticsInSourceGeneratedFilesExperiment")},
        {"WorkspaceConfigurationOptions_EnableOpeningSourceGeneratedFilesInWorkspace", new PropertyName("TextEditor.Roslyn.Specific.EnableOpeningSourceGeneratedFilesInWorkspaceExperiment")},
    };
}
