<Module Name="rvbc2.vcxproj" Id="rvbc2" Version="0.1" xmlns="http://schemas.microsoft.com/developer/modules/2012">
  <Capability Type="module" Id="rvbc2" Version="0.1" />
  <Facet Domain="build">
    <Property Key="SupportedPlatforms" Value="AnyCPU" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset.Open" />
    <Requirement Type="toolset" Id="Microsoft.CodeAnalysis.Toolset" />
    <Requirement Id="rcsc2">
      <Binding Type="None" />
      <Microsoft.Build>
        <Array Name="ClCompile">
          <Element Value="|logging.cpp|" />
          <Element Value="|rcsc2.cpp|" />
          <Element Value="|stdafx.cpp|" />
        </Array>
        <Array Name="ClInclude">
          <Element Value="|logging.h|" />
          <Element Value="|protocol.h|" />
          <Element Value="|stdafx.h|" />
          <Element Value="|targetver.h|" />
        </Array>
      </Microsoft.Build>
    </Requirement>
    <Project Name="rvbc2.vcxproj" Guid="4a40dfe7-34b3-5931-d055-4258510ba9d1" />
  </Facet>
  <Facet Domain="sdk">
    <Artifact Name="rvbc2.exe" />
  </Facet>
  <Facet Domain="packaging">
    <Artifact Name="rvbc2.exe" />
  </Facet>
  <Facet Domain="debug">
    <Artifact Name="rvbc2.pdb" />
  </Facet>
  <Facet Domain="signing">
    <Artifact Name="rvbc2.exe" Strongname="none" />
  </Facet>
</Module>