// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
#nullable restore
#line (1,8)-(14,1) "x:\dir\subdir\Test\TestComponent.razor"

    public readonly struct Measurement
    {
        private readonly int _value;
    
        public Measurement(int value)
        {
            _value = value;
        }
    
        public readonly int GetValue()
            => _value;
    }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
