// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Test.MyComponent<
#nullable restore
#line (1,38)-(1,56) "x:\dir\subdir\Test\TestComponent.cshtml"
IComposedInterface

#line default
#line hidden
#nullable disable
            , 
#nullable restore
#line (1,20)-(1,26) "x:\dir\subdir\Test\TestComponent.cshtml"
string

#line default
#line hidden
#nullable disable
            >>(0);
            __builder.AddComponentParameter(1, nameof(global::Test.MyComponent<IComposedInterface, string>.
#nullable restore
#line (1,64)-(1,69) "x:\dir\subdir\Test\TestComponent.cshtml"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<string>(
#nullable restore
#line (1,71)-(1,86) "x:\dir\subdir\Test\TestComponent.cshtml"
_componentValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(2, nameof(global::Test.MyComponent<IComposedInterface, string>.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<string>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<string>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => _componentValue = __value, _componentValue))));
            __builder.CloseComponent();
            __builder.AddMarkupContent(3, "\r\n");
            __builder.OpenComponent<global::Test.MyComponent<
#nullable restore
#line (2,24)-(2,42) "x:\dir\subdir\Test\TestComponent.cshtml"
IComposedInterface

#line default
#line hidden
#nullable disable
            , 
#nullable restore
#line (2,50)-(2,56) "x:\dir\subdir\Test\TestComponent.cshtml"
string

#line default
#line hidden
#nullable disable
            >>(4);
            __builder.AddComponentParameter(5, nameof(global::Test.MyComponent<IComposedInterface, string>.
#nullable restore
#line (2,64)-(2,69) "x:\dir\subdir\Test\TestComponent.cshtml"
Value

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<string>(
#nullable restore
#line (2,71)-(2,86) "x:\dir\subdir\Test\TestComponent.cshtml"
_componentValue

#line default
#line hidden
#nullable disable
            ));
            __builder.AddComponentParameter(6, nameof(global::Test.MyComponent<IComposedInterface, string>.ValueChanged), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<global::Microsoft.AspNetCore.Components.EventCallback<string>>(global::Microsoft.AspNetCore.Components.EventCallback.Factory.Create<string>(this, global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => _componentValue = __value, _componentValue))));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (4,8)-(6,1) "x:\dir\subdir\Test\TestComponent.cshtml"

    string _componentValue = string.Empty;

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
