// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Test.User>(0);
            __builder.AddComponentParameter(1, "Name", 
#nullable restore
#line (1,20)-(1,28) "x:\dir\subdir\Test\TestComponent.cshtml"
UserName

#line default
#line hidden
#nullable disable
            );
            __builder.AddComponentParameter(2, "NameChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => UserName = __value, UserName));
            __builder.AddComponentParameter(3, "IsActive", 
#nullable restore
#line (1,47)-(1,59) "x:\dir\subdir\Test\TestComponent.cshtml"
UserIsActive

#line default
#line hidden
#nullable disable
            );
            __builder.AddComponentParameter(4, "IsActiveChanged", global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.CreateInferredEventCallback(this, __value => UserIsActive = __value, UserIsActive));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (3,8)-(6,1) "x:\dir\subdir\Test\TestComponent.cshtml"

    public string UserName { get; set; }
    public bool UserIsActive { get; set; }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
