// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class 
#nullable restore
#line (1,12)-(1,30) "x:\dir\subdir\Test\TestComponent.cshtml"
MyGenericComponent

#line default
#line hidden
#nullable disable
    <
#nullable restore
#line (2,12)-(2,17) "x:\dir\subdir\Test\TestComponent.cshtml"
TItem

#line default
#line hidden
#nullable disable
    > : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Test.MyGenericComponent<
#nullable restore
#line (4,28)-(4,34) "x:\dir\subdir\Test\TestComponent.cshtml"
string

#line default
#line hidden
#nullable disable
            >>(0);
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
#nullable restore
#line (6,8)-(9,1) "x:\dir\subdir\Test\TestComponent.cshtml"

    [Parameter]
    public TItem Item { get; set; }

#line default
#line hidden
#nullable disable

    }
}
#pragma warning restore 1591
