C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\Core\Analyzers\CodeStyle.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\Core\CodeFixes\CodeStyleFixes.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\Core\Tests\CodeStyleTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\CSharp\Analyzers\CSharpCodeStyle.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\CSharp\CodeFixes\CSharpCodeStyleFixes.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\CSharp\Tests\CSharpCodeStyleTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\VisualBasic\Analyzers\BasicCodeStyle.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\VisualBasic\CodeFixes\BasicCodeStyleFixes.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert CodeStyle\VisualBasic\Tests\BasicCodeStyleTests.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Core\CodeAnalysisTest\CodeAnalysisTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Core\MSBuildTask\MSBuildTask.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Core\MSBuildTaskTests\MSBuildTaskTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Core\Portable\CodeAnalysis.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\csc\csc.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\CscCore\CscCore.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Portable\CSharpCodeAnalysis.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\CommandLine\CSharpCommandLineTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\Emit\CSharpCompilerEmitTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\Semantic\CSharpCompilerSemanticTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\Symbol\CSharpCompilerSymbolTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\Syntax\CSharpCompilerSyntaxTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\CSharp\Test\WinRT\CSharpWinRTTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Extension\CompilerExtension.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Server\PortableServer\PortableServer.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Server\VBCSCompiler\VBCSCompiler.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Server\VBCSCompilerTests\VBCSCompilerTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Test\Resources\Core\CompilerTestResources.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Test\Utilities\CSharp\CSharpCompilerTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Test\Utilities\CSharp.Desktop\CSharpCompilerTestUtilities.Desktop.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\Test\Utilities\VisualBasic\BasicCompilerTestUtilities.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Portable\BasicCodeAnalysis.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Test\CommandLine\BasicCommandLineTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Test\Emit\BasicCompilerEmitTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Test\Semantic\BasicCompilerSemanticTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Test\Symbol\BasicCompilerSymbolTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\Test\Syntax\BasicCompilerSyntaxTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\vbc\vbc.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Compilers\VisualBasic\VbcCore\VbcCore.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Deployment\Roslyn.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\Core\EditorFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\CSharp\CSharpEditorFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\CSharpTest\CSharpEditorServicesTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\CSharpTest2\CSharpEditorServicesTest2.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\Next\EditorFeatures.Next.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\Test\EditorServicesTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\Test2\EditorServicesTest2.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\TestUtilities\ServicesTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\TestUtilities2\ServicesTestUtilities2.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\Text\TextEditorFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\VisualBasic\BasicEditorFeatures.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert EditorFeatures\VisualBasicTest\BasicEditorServicesTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Source\ExpressionCompiler\ExpressionCompiler.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Source\FunctionResolver\FunctionResolver.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Source\ResultProvider\NetFX20\ResultProvider.NetFX20.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Source\ResultProvider\Portable\ResultProvider.Portable.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Test\ExpressionCompiler\ExpressionCompilerTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Test\FunctionResolver\FunctionResolverTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Core\Test\ResultProvider\ResultProviderTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\CSharp\Source\ExpressionCompiler\CSharpExpressionCompiler.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\CSharp\Source\ResultProvider\NetFX20\CSharpResultProvider.NetFX20.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\CSharp\Source\ResultProvider\Portable\CSharpResultProvider.Portable.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\CSharp\Test\ExpressionCompiler\CSharpExpressionCompilerTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\CSharp\Test\ResultProvider\CSharpResultProviderTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\Package\ExpressionEvaluatorPackage.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\VisualBasic\Source\ExpressionCompiler\BasicExpressionCompiler.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\VisualBasic\Source\ResultProvider\NetFX20\BasicResultProvider.NetFX20.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\VisualBasic\Source\ResultProvider\Portable\BasicResultProvider.Portable.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\VisualBasic\Test\ExpressionCompiler\BasicExpressionCompilerTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert ExpressionEvaluator\VisualBasic\Test\ResultProvider\BasicResultProviderTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Features\Core\Portable\Features.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Features\CSharp\Portable\CSharpFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Features\VisualBasic\Portable\BasicFeatures.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\csi\csi.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\CsiCore\CsiCore.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\EditorFeatures\Core\InteractiveEditorFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\EditorFeatures\CSharp\CSharpInteractiveEditorFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\EditorFeatures\VisualBasic\BasicInteractiveEditorFeatures.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\Features\InteractiveFeatures.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\Host\InteractiveHost.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\HostTest\InteractiveHostTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\vbi\vbi.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Interactive\VbiCore\VbiCore.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Samples\CSharp\Analyzers\CSharpAnalyzers\CSharpAnalyzers\CSharpAnalyzers.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Samples\VisualBasic\Analyzers\BasicAnalyzers\BasicAnalyzers\BasicAnalyzers.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\Core\Scripting.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CoreTest\ScriptingTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CoreTest.Desktop\ScriptingTest.Desktop.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CoreTestUtilities\ScriptingTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CSharp\CSharpScripting.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CSharpTest\CSharpScriptingTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\CSharpTest.Desktop\CSharpScriptingTest.Desktop.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\VisualBasic\BasicScripting.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\VisualBasicTest\BasicScriptingTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Scripting\VisualBasicTest.Desktop\BasicScriptingTest.Desktop.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\DeployCoreClrTestRuntime\DeployCoreClrTestRuntime.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\DeployDesktopTestRuntime\DeployDesktopTestRuntime.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Diagnostics\Diagnostics.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\PdbUtilities\PdbUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Perf\Runner\Perf.Runner.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Perf\StackDepthTest\StackDepthTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Perf\tests\Perf.Tests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Perf\Utilities\Perf.Utilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Utilities\CoreClr\TestUtilities.CoreClr.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Utilities\Desktop\TestUtilities.Desktop.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Test\Utilities\Portable\TestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\BuildBoss\BuildBoss.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\BuildUtil\BuildUtil\BuildUtil.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\ProcessWatchdog\ProcessWatchdog.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\RepoUtil\RepoUtil.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\DeployCompilerGeneratorToolsRuntime\DeployCompilerGeneratorToolsRuntime.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\Source\BoundTreeGenerator\CompilersBoundTreeGenerator.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\Source\CSharpErrorFactsGenerator\CSharpErrorFactsGenerator.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\Source\CSharpSyntaxGenerator\CSharpSyntaxGenerator.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\Source\VisualBasicErrorFactsGenerator\VisualBasicErrorFactsGenerator.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\CompilerGeneratorTools\Source\VisualBasicSyntaxGenerator\VisualBasicSyntaxGenerator.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Tools\Source\RunTests\RunTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\Def\ServicesVisualStudio.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\Impl\ServicesVisualStudioImpl.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\Next\ServicesVisualStudio.Next.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\SolutionExplorerShim\SolutionExplorerShim.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\Test\ServicesVisualStudioTest.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Core\Test.Next\VisualStudioTest.Next.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\CSharp\Impl\CSharpVisualStudio.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\CSharp\Repl\CSharpVisualStudioRepl.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\CSharp\Test\CSharpVisualStudioTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\IntegrationTest\IntegrationTests\VisualStudioIntegrationTests.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\IntegrationTest\TestSetup\VisualStudioIntegrationTestSetup.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\IntegrationTest\TestUtilities\VisualStudioIntegrationTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\InteractiveServices\VisualStudioInteractiveServices.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Razor\RazorVisualStudio.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\RemoteHostClientMock\RemoteHostClientMock.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Setup\VisualStudioSetup.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Setup.Dependencies\VisualStudioSetup.Dependencies.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Setup.Next\VisualStudioSetup.Next.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\TestUtilities2\VisualStudioTestUtilities2.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\VisualBasic\Impl\BasicVisualStudio.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\VisualBasic\Repl\BasicVisualStudioRepl.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\VisualStudioDiagnosticsToolWindow\VisualStudioDiagnosticsWindow.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\VisualStudioInteractiveComponents\VisualStudioInteractiveComponents.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert VisualStudio\Xaml\Impl\XamlVisualStudio.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\Core\Desktop\Workspaces.Desktop.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\Core\Portable\Workspaces.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\CoreTest\ServicesTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\CoreTestUtilities\WorkspacesTestUtilities.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\CSharp\Portable\CSharpWorkspace.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\CSharpTest\CSharpServicesTest.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\Remote\Core\RemoteWorkspaces.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\Remote\Razor\RazorServiceHub.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\Remote\ServiceHub\ServiceHub.csproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\VisualBasic\Portable\BasicWorkspace.vbproj
C:\ProjectSimplifier\ProjectSimplifier\bin\Debug\net461\ProjectSimplifier.exe convert Workspaces\VisualBasicTest\VisualBasicServicesTest.vbproj