// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
#nullable restore
#line (1,3)-(6,1) "x:\dir\subdir\Test\TestComponent.razor"

    var text = """
    {"value":"Razor"}
    """;
    _ = text.Length;

#line default
#line hidden
#nullable disable

            __builder.OpenElement(0, "div");
#nullable restore
#line (8,8)-(10,8) 24 "x:\dir\subdir\Test\TestComponent.razor"
__builder.AddContent(1, """
    {"value":"Razor"}
    """

#line default
#line hidden
#nullable disable
            );
            __builder.CloseElement();
        }
    }
}
#pragma warning restore 1591
