// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
#nullable restore
#line 1 "x:\dir\subdir\Test\TestComponent.cshtml"
using System.Text;

#line default
#line hidden
#nullable disable
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 219
        private void __RazorDirectiveTokenHelpers__() {
        ((global::System.Action)(() => {
#nullable restore
#line 2 "x:\dir\subdir\Test\TestComponent.cshtml"
string __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 2 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object Value1 = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 3 "x:\dir\subdir\Test\TestComponent.cshtml"
StringBuilder __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 3 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object Value2 = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 4 "x:\dir\subdir\Test\TestComponent.cshtml"
int __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 4 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object Value3 = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 5 "x:\dir\subdir\Test\TestComponent.cshtml"
double __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 5 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object Value4 = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 11 "x:\dir\subdir\Test\TestComponent.cshtml"
float __typeHelper = default!;

#line default
#line hidden
#nullable disable
        }
        ))();
        ((global::System.Action)(() => {
#nullable restore
#line 11 "x:\dir\subdir\Test\TestComponent.cshtml"
global::System.Object Value5 = null!;

#line default
#line hidden
#nullable disable
        }
        ))();
        }
        #pragma warning restore 219
        #pragma warning disable 0414
        private static object __o = null;
        #pragma warning restore 0414
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
        }
        #pragma warning restore 1998
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private float Value5 { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private double Value4 { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private int Value3 { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private StringBuilder Value2 { get; set; }
        [global::Microsoft.AspNetCore.Components.InjectAttribute] private string Value1 { get; set; }
    }
}
#pragma warning restore 1591
