// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.AspNetCore.Razor.Language;
using Xunit;

namespace Microsoft.VisualStudio.Razor.LanguageClient.Cohost.Formatting;

public class CSharpSyntaxFormattingOptionsTest_Generator
{
    private static readonly (string name, string editorConfigValue)[] s_openBracePlacements =
    [
        ("BeforeOpenBraceInTypes", "types"),
        ("BeforeOpenBraceInAnonymousTypes", "anonymous_types"),
        ("BeforeOpenBraceInObjectCollectionArrayInitializers", "object_collection_array_initializers"),
        ("BeforeOpenBraceInProperties", "properties"),
        ("BeforeOpenBraceInMethods", "methods"),
        ("BeforeOpenBraceInAccessors", "accessors"),
        ("BeforeOpenBraceInAnonymousMethods", "anonymous_methods"),
        ("BeforeOpenBraceInLambdaExpressionBody", "lambdas"),
        ("BeforeOpenBraceInControlBlocks", "control_blocks"),
    ];

    /// <summary>
    /// This test can be run manually to generate exhaustive tests for CSharpSyntaxFormattingOptions.
    /// </summary>
    /// <remarks>
    /// After running this test, the file will be updated but you should expect the "expected" output to be incorrect
    /// and you'll have to manually adjust it, which is why regenerating the tests is a manual process.
    /// Or make the test generation much smarter I guess :)
    /// </remarks>
    [Fact(Skip = "This test needs to be run manually. Just remove this skip message, and run it if you want")]
    public void GenerateTests()
    {
        //lang=C#-test
        var fileHeader = """
            // <auto-generated />
            
            using System.Threading.Tasks;
            using Microsoft.AspNetCore.Razor.Test.Common;
            using Xunit;
            using Xunit.Abstractions;

            namespace Microsoft.VisualStudio.Razor.LanguageClient.Cohost.Formatting;

            public class CSharpSyntaxFormattingOptionsTest(ITestOutputHelper testOutput) : DocumentFormattingTestBase(testOutput)
            {
            """;

        //lang=C#-test
        var fileFooter = """
            }
            """;

        //lang=C#-test
        var testTemplate = """"
            [Fact]
            public async Task {TestName}()
            {
                await RunFormattingTestAsync(
                    input: """
                        @code
                        {
                        private bool IconMenuActive { get; set; } = false;
                        protected void ToggleIconMenu(bool iconMenuActive)
                        {
                        IconMenuActive = iconMenuActive;
                        }
                        }
                        """,
                    htmlFormatted: """
                        @code
                        {
                        private bool IconMenuActive { get; set; } = false;
                        protected void ToggleIconMenu(bool iconMenuActive)
                        {
                        IconMenuActive = iconMenuActive;
                        }
                        }
                        """,
                    expected: """
                        @code
                        {
                            private bool IconMenuActive { get; set; } = false;
                            protected void ToggleIconMenu(bool iconMenuActive)
                            {
                                IconMenuActive = iconMenuActive;
                            }
                        }
                        """,
                    additionalFiles:
                    [
                        (".editorconfig", """
                            root = true

                            [*.razor]
                            {NewLineOption}
                            csharp_preserve_single_line_statements = {WrappingKeepStatementsOnSingleLine}
                            csharp_preserve_single_line_blocks = {WrappingPreserveSingleLine}
                            """)
                    ]);
            }
        """";

        bool[] booleanOptions = [true, false];

        var projectPath = TestProject.GetProjectDirectory(typeof(CSharpSyntaxFormattingOptionsTest_Generator), layer: TestProject.Layer.Tooling);
        var testFileName = Path.GetFullPath(Path.Combine(projectPath, """..\Microsoft.CodeAnalysis.Razor.CohostingShared.UnitTests\Formatting\CSharpSyntaxFormattingOptionsTest.cs"""));

        var addExtraLine = false;

        using var writer = new StreamWriter(testFileName, append: false, new UTF8Encoding(encoderShouldEmitUTF8Identifier: true));
        writer.WriteLine(fileHeader);

        foreach (var newLineOption in GetNewLineOptions())
            foreach (var keep in booleanOptions)
                foreach (var preserve in booleanOptions)
                {
                    if (addExtraLine)
                    {
                        writer.WriteLine();
                    }

                    addExtraLine = true;

                    var testName = $"CSharpSyntaxFormattingOptions_Without{newLineOption.without}_{(keep ? "SingleLine" : "MultiLine")}_{(preserve ? "PreserveSingle" : "DontPreserve")}";
                    writer.WriteLine(testTemplate
                        .Replace("{TestName}", testName)
                        .Replace("{NewLineOption}", newLineOption.editorConfig)
                        .Replace("{WrappingKeepStatementsOnSingleLine}", keep.ToString().ToLowerInvariant())
                        .Replace("{WrappingPreserveSingleLine}", preserve.ToString().ToLowerInvariant()));
                }

        writer.WriteLine(fileFooter);
    }

    private static IEnumerable<(string without, string editorConfig)> GetNewLineOptions()
    {
        yield return ("BeforeMembersInObjectInitializers", "csharp_new_line_before_members_in_object_initializers = false");
        yield return ("BeforeMembersInAnonymousTypes", "csharp_new_line_before_members_in_anonymous_types = false");
        yield return ("BeforeElse", "csharp_new_line_before_else = false");
        yield return ("BeforeCatch", "csharp_new_line_before_catch = false");
        yield return ("BeforeFinally", "csharp_new_line_before_finally = false");

        foreach (var (name, editorConfigValue) in s_openBracePlacements)
        {
            var remainingPlacements = s_openBracePlacements
                .Where(placement => placement.editorConfigValue != editorConfigValue)
                .Select(placement => placement.editorConfigValue);

            yield return (name, $"csharp_new_line_before_open_brace = {string.Join(", ", remainingPlacements)}");
        }

        yield return ("BetweenQueryExpressionClauses", "csharp_new_line_between_query_expression_clauses = false");
    }
}
