// <auto-generated/>
#pragma warning disable 1591
namespace Test
{
    #line default
    using global::System;
    using global::System.Collections.Generic;
    using global::System.Linq;
    using global::System.Threading.Tasks;
    using global::Microsoft.AspNetCore.Components;
    #line default
    #line hidden
    #nullable restore
    public partial class TestComponent : global::Microsoft.AspNetCore.Components.ComponentBase
    #nullable disable
    {
        #pragma warning disable 1998
        protected override void BuildRenderTree(global::Microsoft.AspNetCore.Components.Rendering.RenderTreeBuilder __builder)
        {
            __builder.OpenComponent<global::Test.MyComponent<
#nullable restore
#line (1,21)-(1,31) "x:\dir\subdir\Test\TestComponent.cshtml"
CustomType

#line default
#line hidden
#nullable disable
            >>(0);
            __builder.AddComponentParameter(1, nameof(global::Test.MyComponent<CustomType>.
#nullable restore
#line (1,33)-(1,37) "x:\dir\subdir\Test\TestComponent.cshtml"
Item

#line default
#line hidden
#nullable disable
            ), global::Microsoft.AspNetCore.Components.CompilerServices.RuntimeHelpers.TypeCheck<CustomType>(
#nullable restore
#line (1,39)-(1,55) "x:\dir\subdir\Test\TestComponent.cshtml"
new CustomType()

#line default
#line hidden
#nullable disable
            ));
            __builder.CloseComponent();
        }
        #pragma warning restore 1998
    }
}
#pragma warning restore 1591
