// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.
// See the LICENSE file in the project root for more information.

using System.Collections.Generic;
using System.Linq;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.CodeAnalysis.CodeActions;
using Microsoft.CodeAnalysis.CodeFixes;
using Microsoft.CodeAnalysis.CSharp.ImplementAbstractClass;
using Microsoft.CodeAnalysis.Test.Utilities;
using Roslyn.Test.Utilities;
using Xunit;

namespace Microsoft.CodeAnalysis.Editor.CSharp.UnitTests.ImplementAbstractClass;

public sealed partial class ImplementAbstractClassTests
{
    private sealed record RazorGeneratedDocumentData(string HintName, string GeneratedCode);

    protected override void InitializeWorkspace(TestWorkspace workspace, TestParameters parameters)
    {
        if (parameters.fixProviderData is not RazorGeneratedDocumentData generatedDocument)
        {
            return;
        }

        var project = workspace.CurrentSolution.Projects.Single();
        var updatedProject = project.AddAnalyzerReference(
            new TestGeneratorReference(
                new Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator(
                    context => context.AddSource(generatedDocument.HintName, generatedDocument.GeneratedCode))));

        Assert.True(workspace.TryApplyChanges(updatedProject.Solution));
    }

    private static TestParameters WithRazorGeneratedDocument(string generatedCode, string hintName = "Component.razor.g.cs")
        => new(fixProviderData: new RazorGeneratedDocumentData(hintName, generatedCode));

    [Fact]
    public async Task TestImplementingAbstractClassInRazorSourceGeneratedDocument()
    {
        using var workspace = CreateWorkspaceFromOptions(
            """
            <Workspace>
                <Project Language="C#" AssemblyName="ClassLibrary1" CommonReferences="true">
                    <Document>
            abstract class BaseComponent
            {
                public abstract string GetValue();
            }

            class Placeholder
            {
            }
                    </Document>
                </Project>
            </Workspace>
            """,
            WithRazorGeneratedDocument(
                """
                // <auto-generated />

                public partial class Component : BaseComponent
                {
                }
                """));

        var project = workspace.CurrentSolution.Projects.Single();
        var sourceGeneratedDocument = Assert.Single(await project.GetSourceGeneratedDocumentsAsync(CancellationToken.None));
        Assert.Contains("Microsoft.NET.Sdk.Razor.SourceGenerators.RazorSourceGenerator", sourceGeneratedDocument.FilePath);

        var requestTree = await sourceGeneratedDocument.GetSyntaxTreeAsync(CancellationToken.None);
        var compilation = await project.GetCompilationAsync(CancellationToken.None);
        Assert.NotNull(requestTree);
        Assert.NotNull(compilation);

        var diagnostic = Assert.Single(
            compilation!.GetDiagnostics(CancellationToken.None).Where(
                diagnostic => diagnostic.Id == "CS0534" && diagnostic.Location.SourceTree == requestTree));

        var codeActions = new List<CodeAction>();
        var context = new CodeFixContext(
            sourceGeneratedDocument,
            diagnostic.Location.SourceSpan,
            [diagnostic],
            (action, _) => codeActions.Add(action),
            CancellationToken.None);

        var provider = new CSharpImplementAbstractClassCodeFixProvider();
        await provider.RegisterCodeFixesAsync(context);

        var operations = await Assert.Single(codeActions).GetOperationsAsync(CancellationToken.None);
        var changedSolutions = await ApplyOperationsAndGetSolutionAsync(workspace, operations);
        var newSourceGeneratedDocument = await changedSolutions.Item2.GetSourceGeneratedDocumentAsync(sourceGeneratedDocument.Id, CancellationToken.None);

        Assert.NotNull(newSourceGeneratedDocument);
        AssertEx.EqualOrDiff(
            """
            // <auto-generated />

            public partial class Component : BaseComponent
            {
                public override string GetValue()
                {
                    throw new System.NotImplementedException();
                }
            }
            """,
            (await newSourceGeneratedDocument!.GetTextAsync(CancellationToken.None)).ToString());
    }
}
