' <auto-generated/>

Imports System.Runtime.CompilerServices
Imports Roslyn.Test.Utilities

Friend Module InitializeTestModule
    <ModuleInitializer>
    Friend Sub Initializer()
        RuntimeHelpers.RunModuleConstructor(GetType(TestBase).Module.ModuleHandle)
    End Sub
End Module
