name: Full Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.7.20366.6
    - name: Restore
      run: ./build.sh --restore
    - name: Build
      run: ./build.sh --build
    - name: Run RoslynEx tests
      run: dotnet test
      working-directory: ./src/RoslynEx/RoslynEx.UnitTests