name: Full Pipeline

on: [ push, pull_request ]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-preview.8.20417.9
    - name: Restore
      run: ./restore.sh
    - name: Build
      run: ./build.sh
    - name: Run RoslynEx tests
      run: dotnet test --filter Category\!=OuterLoop
      working-directory: ./src/RoslynEx/RoslynEx.UnitTests
    - name: Run Roslyn tests
      run: ./build.sh --test
    - uses: actions/upload-artifact@v2
      if: failure()
      with:
        name: test-results
        path: artifacts/TestResults/
